MobileNativeFoundation/rules_xcodeproj

tools/generator/src/Environment.swift
tools/generator/src/Generator+CreateProject.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift

The `PBXProject` is cannonically accessed through `PBXProj.rootObject`.

Don't return `PBXProject` from `createProject()`

---

tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/src/Generator.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/ProcessTargetMergesTests.swift

A single library can be used by multiple executable targets, so we need to allow merging into multiple destinations.

Allow merging into multiple destinations

---

tools/generator/src/Errors.swift
tools/generator/src/Generator.swift

`LocalizedError` allows us to easily display a user facing message for errors. I've included a call to action to file a bug if a user sees a `PreconditionError`.
There will be more errors in the future, so I also moved it to its own file.

Conform `PreconditionError` to `LocalizedError`

---

tools/generator/src/Environment.swift
tools/generator/src/Generator.swift
tools/generator/test/GeneratorTests.swift

We will want to use the same instance of `Logger` outside of the `Generator` instance, so having it be part of `Environment` makes that tricky.

Pass `logger` directly to `Generator`

---

tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/Generator.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/PBXProj+Testing.swift
tools/generator/test/ProcessTargetMergesTests.swift
tools/generator/test/SetTargetConfigurations.swift
tools/generator/test/Target+Testing.swift

A test fails without #27, but knowing that will be fixed so (one way or another), I think it's fine to land this.

Set target configurations

---

tools/generator/BUILD
tools/generator/src/Errors.swift
tools/generator/src/Generator+Main.swift

This adds a `@main` conformance to `Generator` that parses some commandline arguments, creates a `Generator`, and invokes `generate()`.

Add a binary target for `generator`

---

xcodeproj/internal/target.bzl

This causes rules like `apple_dynamic_framework_import` to not be processed as targets. Projects with rules like that will still be incomplete, as we need still need to add support for adding those links and embeds.
I also added an earlier failure for when this doesn't prevent processing.

Don't generate a target for rules that don't have outputs

---

examples/ios_app/Example/BUILD
examples/ios_app/ExampleUITests/BUILD
test/fixtures/ios_app/spec.json
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj_aspect.bzl

This is somewhat of a stopgap. It's making assumptions about how outputs are propagated between rules. A more holistic approach, where we look at `target.files`, will come in the future.

Add support for `filegroup`

---

test/fixtures/fixtures.bzl
test/fixtures/generator/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+CreateFilesAndGroups.swift
xcodeproj/xcodeproj.bzl

We don't use a relative path by default because the symlinks in `bazel-WORKSPACE/external` change with each build, causing the files to become unavailable in Xcode from time to time. I'm fine with making the use of the fixture projects a little more finicky in order to have deterministic fixtures.

Set `externalDirectory` to a relative path in fixtures

---

README.md
xcodeproj/internal/installer.template.sh

It was slightly confusing for people not used to the way generators like this work. Without this new messaging people might assume they need to use the `bazel-bin/` version.

Make it clear where the generated project is

---

test/fixtures/fixtures.bzl
xcodeproj/xcodeproj.bzl

This prevents applying the transition `xcodeproj`'s other dependencies, such as `generator`. It also allows for calling the `xcodeproj` targets in `//test/fixtures` and them having the correct transition applied. This will be needed later for generated files support.

Move fixture transition to `xcodegen.targets`

---

xcodeproj/internal/target.bzl

Older rules_apple versions would put the entitlements processing as a dep of `ios_application`. This works around that.

Loosen the requirement around top-level deps slightly

---

test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
test/fixtures/ios_app/project.xcodeproj/project.pbxproj
test/fixtures/ios_app/spec.json
xcodeproj/xcodeproj.bzl

This is the Xcode default for projects (yet not when you don't set it 🤔), and it was the assumption I had all along.

Set `CLANG_ENABLE_OBJC_ARC = YES`

---

test/internal/build_settings/calculate_module_name_tests.bzl
test/internal/build_settings/get_targeted_device_family_tests.bzl
test/internal/opts/process_compiler_opts_tests.bzl
test/internal/opts/process_linker_opts_tests.bzl
test/internal/platform/generate_platform_information_tests.bzl
test/internal/target/calculate_configuration_tests.bzl
test/internal/target/process_libraries_tests.bzl
test/internal/target/process_top_level_properties_tests.bzl

Removes a Bazel warning, and they really should be quick.

Add short timeout for Stalark unit tests

---

BUILD
WORKSPACE
buildbuddy.yaml

Related to #126.
- Added dev-only dependency on `keith/buildifier-prebuilt`.
- Added two runnable targets to the root of the workspace: `//:buildifier.check` and `//:buildifier.fix`.

Add initial buildifier check and fix commands

---

test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/FilePath.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+WriteXcodeProj.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/Target+Testing.swift

This is in preperation adding more information to `FilePath` from the spec, such as if the input was generated or in an external repository.

Push `FilePath` creation out to DTO

---

test/internal/target/process_libraries_tests.bzl
xcodeproj/internal/target.bzl

Part of #82 .
This allows us to pick up static libaries produced by `cc_library`.

Use `CcInfo` instead of `apple_common.ObjC`

---

test/fixtures/generator/spec.json
tools/generator/src/FilePath.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/target.bzl
xcodeproj/xcodeproj.bzl

This allows for `//external` (in workspace) sources to be handled properly.

Split `.input` into `.project` and `.external`

---

examples/ios_app/TestingUtils/BUILD
examples/ios_app/TestingUtils/TestingUtils.swift
test/fixtures/fixtures.bzl
test/fixtures/ios_app/project.xcodeproj/project.pbxproj
test/fixtures/ios_app/spec.json
tools/generator/src/Environment.swift
tools/generator/src/FilePath.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+Main.swift
tools/generator/src/Generator.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/files.bzl
xcodeproj/xcodeproj.bzl

Part of https://github.com/buildbuddy-io/rules_xcodeproj/issues/100.
Similar to external repositories, this allows `bazel-out` to be a normal directory in the workspace (as long as `--symlink_prefix` is overridden).
We show the generated files in a special group after the external repositories.

Add `FilePath.PathType.generated` case

---

xcodeproj/internal/target.bzl
xcodeproj/xcodeproj.bzl

Part of https://github.com/buildbuddy-io/rules_xcodeproj/issues/100.
This allows one to specify `--output_groups=generated_inputs` to produce the generated files that are referenced in the Xcode project.

Expose generated input files in an output group

---

tools/generator/src/Environment.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+WriteXcodeProj.swift
tools/generator/test/AddTargetsTests.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift

This cleans up the logic in `writeXcodeProj()`, which unlocks the ability to write other internal files with non-empty content.

Refactor return type of `createFilesAndGroups()`

---

xcodeproj/internal/target.bzl

By having a function with named arguments Starlark will complain earlier when we don't provide the same values from all the various target processing functions.

Add a `_processed_target()` function to ease development

---

xcodeproj/internal/opts.bzl
xcodeproj/internal/target.bzl

This makes it match the API of the other functions, and allows it to not be the first function to set build settings.

Refactor `process_opts()` to take in `build_settings`

---

buildbuddy.yaml
examples/ios_app/BUILD
examples/ios_app/Example/BUILD
examples/ios_app/ExampleTests/BUILD
examples/ios_app/ExampleUITests/BUILD
examples/ios_app/TestingUtils/BUILD
examples/ios_app/Utils/BUILD
test/BUILD
test/fixtures/BUILD
test/fixtures/fixtures.bzl
test/fixtures/generator/spec.json
test/internal/build_settings/calculate_module_name_tests.bzl
test/internal/build_settings/get_targeted_device_family_tests.bzl
test/internal/flattened_key_values/flattened_key_values_tests.bzl
test/internal/opts/process_compiler_opts_tests.bzl
test/internal/opts/process_linker_opts_tests.bzl
test/internal/platform/generate_platform_information_tests.bzl
test/internal/target/calculate_configuration_tests.bzl
test/internal/target/process_libraries_tests.bzl
test/internal/target/process_top_level_properties_tests.bzl
test/xcodeproj_tests.bzl
tools/generator/BUILD
xcodeproj/internal/flattened_key_values.bzl
xcodeproj/internal/input_files_aspect.bzl
xcodeproj/internal/opts.bzl
xcodeproj/internal/platform.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj_aspect.bzl
xcodeproj/repositories.bzl
xcodeproj/xcodeproj.bzl

Closes #126 
- Ran `//:buildifier.fix` on the codebase.
- Addressed issues uncovered by running `//:buildifier.check`.
- Enabled CI pipeline action to run `//:buildifier.check`.

Addressed Buildifier lint issues and enabled Buildifier check in CI pipeline.

---

test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
test/fixtures/ios_app/project.xcodeproj/project.pbxproj
test/fixtures/ios_app/spec.json
tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/Generator.swift
tools/generator/src/SearchPaths.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurations.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/target.bzl
xcodeproj/xcodeproj.bzl

Part of #69, #82, #83, and #84.
This will be shown off in a future change when a `cc_binary` example is checked in.

Set user header search paths for non-Swift targets

---

test/fixtures/generator/spec.json
test/fixtures/ios_app/spec.json
xcodeproj/internal/target.bzl

We now pass around the linker inputs until we need to grab the static libraries out of it. In a future change this allows for links to be propagated through targets that don't produce their own Xcode target, like `objc_library` targets that only contain headers.
Also, in the future we will probably want to use the other values in the linker inputs, such as the dylib and framework references.

Refactor libraries collection

---

xcodeproj/internal/files.bzl
xcodeproj/internal/target.bzl

This hides the fact that we return a plain string for a project path, and allows us to change that later with less code breaks.

Add `project_file_path()`

---

test/fixtures/generator/spec.json
test/internal/opts/process_compiler_opts_tests.bzl
xcodeproj/internal/opts.bzl

Xcode prefers this as a string.

Use a string for `SWIFT_ACTIVE_COMPILATION_CONDITIONS`

---

xcodeproj/internal/files.bzl

We care if it's generated more than if it's an external source, so for files generated in an external repo, we need to report it as `.generated`.

Fix `file_path()` ordering

---

BUILD
WORKSPACE

Closes #176.
- Updated to [keith/buildifier-prebuilt 0.4.0](https://github.com/keith/buildifier-prebuilt/releases/tag/0.4.0) so that all warnings except a select few can specified.
- The `cc-native` warning wants to add a dependency on `rules_cc` that is not desired at this time.

Enable all Buildifier warnings except `cc-native`

---

buildbuddy.yaml

Integration tests are much slower than the unit tests. By splitting them off into their own workflow PR authors can get feedback on the non-integration tests faster.

Split integration tests into their own workflow

---

examples/ios_app/test/fixtures/BUILD
examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/spec.json
test/fixtures/command_line/spec.json
test/fixtures/generator/spec.json
tools/generator/src/DTO.swift
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/test/Fixtures.swift
tools/generator/test/ProcessTargetMergesTests.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/target.bzl

These values aren't used yet, but in a future change where we change the directory layout of DerivedData they will be used to set `SWIFT_INCLUDE_PATHS`.

Provide `swiftmodules` to the generator

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-fastbuild-ST-d3e756bfe7fd/Example/Example.LinkFileList
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-fastbuild-ST-d3e756bfe7fd/ExampleTests/ExampleTests.LinkFileList
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-fastbuild-ST-1b9bd654f600/examples/cc/tool/tool.LinkFileList
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min12.0-applebin_macos-darwin_x86_64-fastbuild-ST-f2aadcfcab57/examples/command_line/tool/tool.LinkFileList
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/project.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-fastbuild-ST-1b9bd654f600/tools/generator/generator.LinkFileList
test/fixtures/generator/project.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-fastbuild-ST-1b9bd654f600/tools/generator/tests.LinkFileList
test/fixtures/ios_app/project.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-fastbuild-ST-d3e756bfe7fd/examples/ios_app/Example/Example.LinkFileList
test/fixtures/ios_app/project.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-fastbuild-ST-d3e756bfe7fd/examples/ios_app/ExampleTests/ExampleTests.LinkFileList
tools/generator/src/Environment.swift
tools/generator/src/FilePath.swift
tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+CreateProject.swift
tools/generator/src/Generator+DisambiguateTargets.swift
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/Generator.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/DisambiguateTargetsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/target.bzl

Before this change there was potential for output file clashes. This happened because Bazel has nice isolation in its output directory, while Xcode's default one is very flat. Instead of trying to rename things to work with Xcode's default layout we are now matching most of Bazel's layout.
This requires setting more search paths as not everything is sitting in the same place anymore.
Part of #131.

Use a custom DerivedData directory layout

---

test/internal/opts/process_compiler_opts_tests.bzl
tools/generator/src/Generator+SetTargetConfigurations.swift
xcodeproj/internal/opts.bzl

Xcode prefers it this way. There really is no rhyme or reason to this, is there?

Set `OTHER_SWIFT_FLAGS` as a string

---

.bazelrc
examples/ios_app/CoreUtilsObjC/Answers.m
examples/ios_app/CoreUtilsObjC/BUILD
examples/ios_app/CoreUtilsObjC/CoreUtils/Answers.h
examples/ios_app/Utils/Foo.h
examples/ios_app/Utils/Foo.m
examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/generated.xcfilelist
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-fastbuild-ST-d3e756bfe7fd/Example/Example.LinkFileList
examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/spec.json
test/fixtures/command_line/spec.json
test/fixtures/ios_app/project.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-fastbuild-ST-d3e756bfe7fd/examples/ios_app/Example/Example.LinkFileList
xcodeproj/internal/target.bzl

Also updates the example to expose the failure we had.

Fix Swift clang module header search paths

---

examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/spec.json
test/fixtures/command_line/spec.json
test/fixtures/generator/spec.json
test/internal/platform/generate_platform_information_tests.bzl
tools/generator/src/DTO.swift
tools/generator/src/Generator+DisambiguateTargets.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/test/DisambiguateTargetsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/platform.bzl

There is some logic we will want to do based on the platform, so this is better than the pretty name we were getting before.

Use an enum for `Platform.os`

---

examples/BUILD

When executing integration tests, ignore any generated Xcode projects in the child workspace

---

xcodeproj/internal/collections.bzl
xcodeproj/internal/opts.bzl
xcodeproj/internal/target.bzl

This is basically the same as skylib's version, except it doesn't have the `list()` wrapper. When https://github.com/bazelbuild/bazel-skylib/blob/8334f938c1574ef6f1f7a38a03550a31df65274e/lib/collections.bzl#L64-L65 is addressed, we should move to that version.

Add `uniq()` function

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/spec.json
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/spec.json
test/fixtures/generator/project.xcodeproj/project.pbxproj
tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/SearchPaths.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/target.bzl

Before this refactor we generally tried to calculate search paths, to ensure that we correctly identified the "external/" and "bazel-out/" directories without having to parse strings. This has the benefit of technically allowing the "external/" and "bazel-out/" directories to exist in the workspace.
There are some issues with this approach though. The main one being that custom rules that set search paths aren't accounted for properly. If we instead leverage the information in `CcInfo.compilation_context` we support all sorts of rules out of the box... but have to resort parsing strings.
We were already parsing the strings for the `local_includes`, and will need to for framework includes in the future. I believe the more generic code that should just work is worth giving up the ability to …

Refactor search paths collection

---

README.md

If huge dangerous 0day exploits can all have great logos, so can something _useful_!

Add logo to project README

---

tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/test/Fixtures.swift

Part of #75.
This makes it easier to copy resources when we have paths to all of the children but not the parent.

Add `files` entries for folder-type file children

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeproj_aspect.bzl

This will be used soon to limit which dependencies become Xcode targets, which fixes issues with code generation rules.

Associate transitive `XcodeProjInfo` with the attribute it came from

---

config/string_flag.bzl

Now, `string_flag` really is interchangeable with the Skylib version.

Update `string_flag` to return a `BuildSettingInfo`

---

tools/generator/src/FilePath.swift
tools/generator/test/CreateFilesAndGroupsTests.swift

We shouldn't need to create the intermediate struct and sort, but currently `CustomDump` mixes up values and keys, making the diff output unreadable. This is at least parsable now when there is a diff failure here.

Improve diff on `createdFiles`

---

tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+WriteXcodeProj.swift
tools/generator/src/Sorting.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift

`PBXVariantGroup` is used to hold localized files. For resource bundling we need to copy these references instead of the `PBXFileReference` inside of them.
We don't have anything that creates `PBXVariantGroup`s yet, but that is coming soon in a PR to support localized files.

Add support for `PBXVariantGroup` to `File`

---

examples/ios_app/TestingUtils/BUILD
examples/ios_app/TestingUtils/merge.sh
xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/target.bzl

Part of #100.
Before this change we would create Xcode targets and set dependencies to them along every rule attribute. This was partially a side effect of the changes in input collection that requires us to propagate the aspect along all attributes.
Now we only include transitive information for attributes that should create Xcode targets.

Fix over-collection of Xcode targets

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
test/fixtures/command_line/spec.json
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Inputs.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/input_files.bzl

As we add new inputs, such as we did with the Info.plist, it was easy to forget to update the logic around adding the Bazel Generated Files target dependency. Since we have all of the information we need in `input_files.to_dto()`, I've moved the logic there so we will automatically catch these dependencies in the future.

Fix generated files target dependency detection

---

examples/ios_app/Example/BUILD
examples/ios_app/ExampleResources/BUILD
examples/ios_app/ExampleResources/dep_resources_collector.bzl
examples/ios_app/test/fixtures/spec.json
xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/resource_bundle_products.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj.bzl

While this prevents some extra Xcode targets from being created when they aren't wanted, it has an issue logged in https://github.com/buildbuddy-io/rules_xcodeproj/issues/228.

Filter resource targets better

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/modulemaps.fixed.xcfilelist
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/modulemaps.xcfilelist
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/modulemaps.fixed.xcfilelist
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/modulemaps.xcfilelist
test/fixtures/generator/project.xcodeproj/project.pbxproj
tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

For targets that don't depend on `Bazel Generated Files`, the `gen_dir` symlink might not be created yet, so search paths need to be based on `$(BUILD_DIR)` instead.

Fix non-generated build setting paths

---

WORKSPACE
xcodeproj/repositories.bzl

We only patch it for our tests, so we don't need to apply the patch globally.

Only apply Xcodeproj patch in our repo

---

xcodeproj/internal/installer.template.sh

If we don't do this, Xcode shows generated files as unreachable until after the symlink is created again and the project is reopened.

Don't blow away `gen_dir` on each install

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/generator/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

This is needed when Bazel sets a different architecture than Xcode's default.

Set `ARCHS` build setting

---

shared.bazelrc

Works around https://github.com/bazelbuild/rules_swift/issues/794.

Fix minimum OS version cache poisoning

---

xcodeproj/internal/updater.template.sh

This was failing for me locally on macOS 12.3. I believe earlier versions of macOS also ship with `python3`, so hopefully it doesn't break for anyone else.

Use python3 instead of python for compatibility with newer versions of macOS

---

examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/spec.json
test/fixtures/command_line/spec.json
test/fixtures/generator/spec.json
tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/src/Generator.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/ProcessTargetMergesTests.swift
xcodeproj/internal/flattened_key_values.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj.bzl

There is no need to send over the large `required_links` over to the generator, since we have all of the information in Starlark to perform the merge. We still send the invalid merges to the generator for better warning reporting.

Perform merge detection in Starlark

---

shared.bazelrc

This prevents action result cache misses when flipping between cache and no-cache.

Always apply `--remote_default_exec_properties`

---

test/internal/targets/BUILD.bazel
test/internal/targets/is_test_bundle_tests.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/targets.bzl

Related to #136.
- Added `targets.bzl` to encapsulate API for inspecting and acting upon a target. The hope is to move some additional functionality from target.bzl to this API.
- Implemented `targets.is_test_bundle()` to encapsulate the logic for detecting a test bundle target.

Refactor test bundle detection to `targets.bzl`

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/spec.json
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/spec.json
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
xcodeproj/internal/opts.bzl

Leaving this flag in causes weird ascii escape sequences in the build output.

Remove color diagnostics setting from parsed opts

---

xcodeproj/repositories.bzl

I saw this warning locally while working on my patch in [bazelbuild/rules_apple](https://github.com/bazelbuild/rules_apple). Basically the warning calls the function `rules_xcodeproj_dependencies` whereas the function's name is `xcodeproj_rules_dependencies`.

Fix function name typo in warning message

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/spec.json
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/spec.json
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
test/internal/opts/process_compiler_opts_tests.bzl
tools/generator/src/Generator+SetTargetConfigurations.swift
xcodeproj/internal/opts.bzl
xcodeproj/internal/target.bzl

Part of #94.
This is needed to properly support implicit PCM compilation.
We also had to set `OTHER_SWIFT_FLAGS` of the remaining `OTHER_CFLAGS` (with `-Xcc`) to pass through `cc_toolchain` set flags. This fixes the "redefining builtin macro" warning.

Set define with `GCC_PREPROCESSOR_DEFINITIONS` instead of `OTHER_CFLAGS`

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

Part of #69.
The regex was wrong for the other header paths (i.e. `textual header`).

Fix modulemap rewrite of other header paths

---

xcodeproj/internal/target.bzl

Part of #71 and #77.
We need to use `ObjCProvider` for this for now.

Fix `FRAMEWORK_SEARCH_PATHS` for headerless frameworks

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
examples/ios_app/third_party/BUILD
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/spec.json
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/spec.json
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/test/ProcessTargetMergesTests.swift
xcodeproj/internal/target.bzl

Part of #69, #71, and #77.
This adds support for `apple_static_framework_import`'s `sdk_frameworks` and `weak_sdk_frameworks` attributes.

Set `-framework` and `-weak_framework` for SDKs

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/generator/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

We need the external symlink for our search paths to external repo headers to work. Before this change we would only create the symlink as part of the Bazel Generated Files target. Now we have a new target that runs before all other targets that ensures that the symlinks exist.
Ideally this would only run if the symlinks didn't exist, but Xcode doesn't support the Input Files being symlinks, so it always runs. Thankfully it's super fast.

Fix external link for targets without generated files

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/generator/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

We might as well create all of the symlinks in one place.

Move `gen_dir` symlink creation to Setup

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

Follow-up to https://github.com/buildbuddy-io/rules_xcodeproj/pull/279.
I ran into a case where if you have a directory that contains the word `external`, it that wasn't being patched correctly, thus failing the compilation.
This PR fixes it and only excludes headers in directories that start with exactly `/bazel-out/` or `/external/` but not directories that contain `/toolexternal/` or `/externaltool/`, or have `/bazel-out/` or `/external/` later in the path.

Fix escaping to patch directories that contain the word external

---

examples/ios_app/ExampleTests/BUILD
examples/ios_app/test/fixtures/spec.json
xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/resource_bundle_products.bzl
xcodeproj/internal/target.bzl

Part of #80, #81, #103. 
This doesn't make sense, but it's clearly supported with rules_apple. This also is more fuel for me to eventually rewrite this in a way that fixes another resource completeness bug (#228).

Fix resource targets that are included via `deps`

---

test/internal/opts/process_compiler_opts_tests.bzl
xcodeproj/internal/opts.bzl

If you pass `-application-extension` to `copts`, it's now handled correctly.

Handle -application-extension copt

---

test/internal/opts/process_compiler_opts_tests.bzl
xcodeproj/internal/opts.bzl

This PR fixes an issue where `copts` for Swift code are not collected correctly and can cause build failures. Still very much a WIP, but feedback welcome!

Parse user-provided copts for Swift

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/tvos_app/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

This change both limits the numbers of env variables being passed to `bazel build` as well as fixes an issue where the Run Scripts would get different selected platforms depending on if it was a regular build or an index build, by saying that the run scripts support all platforms.

Ensure the same env variables are being used during indexing

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/tvos_app/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

The heuristics for determining which of these scripts to run is a little off. It won't run the Setup script, and indexing builds can fail if that's not run.

Force scripts to run during indexing

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/tvos_app/project.xcodeproj/project.pbxproj
tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

If the parent directories of generated files don't exist before an Xcode project is opened, then after the files are created Xcode still won't see them until the project is closed and opened again.
As a step towards making that experience better we will now pre-create those directories in the Setup target. In a later change we will invoke this target during project generation to put the project in a better state from the start.

Create generated file parent directories during Setup

---

doc/faq.md
xcodeproj/internal/fixtures.bzl
xcodeproj/internal/installer.template.sh
xcodeproj/internal/xcodeproj.bzl

To make initial experiences nicer, we now run the `Bazel Generated Files` scheme as part of initial project creation. This won't be run each time the project is generated, only if the `gen_dir` isn't found.
To disable this behavior, you can set `pre_generate_files = False` on your `xcodeproj` target. In that case, it will only run the `Setup` scheme, which will ensure that Xcode behaves nicely once the generated files are created, without having to close and re-open the project.
Longer term we might want to reduce the number of files pre-generated, as this step might take a long time. Also, Build with Bazel might have different requirements.

Pre-generate files during initial project creation

---

.bazelrc
BUILD
WORKSPACE
examples/BUILD

Related to bazel-contrib/rules_bazel_integration_test#47.

Upgrade `rules_bazel_integration_test` to use `bazel-contrib` release.

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/spec.json
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/spec.json
test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
test/fixtures/tvos_app/project.xcodeproj/project.pbxproj
test/fixtures/tvos_app/spec.json
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Path+Extensions.swift
tools/generator/test/PathExtensionsTests.swift
xcodeproj/internal/input_files.bzl
xcodeproj/internal/xcodeproj.bzl

Resolves https://github.com/buildbuddy-io/rules_xcodeproj/issues/300
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/474794/163598017-db25143f-c870-48ee-9ddb-945231fb673c.png)|![image](https://user-images.githubusercontent.com/474794/163598029-123a3200-4f60-4c21-a382-2390ad9e489b.png)|

Include `BUILD` files in Xcode's Project navigator

---

examples/command_line/tool/BUILD
test/fixtures/command_line/project.xcodeproj/project.pbxproj
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/generated.rsynclist
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/modulemaps.fixed.xcfilelist
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/modulemaps.xcfilelist
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-fastbuild-ST-6f61ef8fe0bd/examples/command_line/tool/tool.LinkFileList
test/fixtures/command_line/project.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min12.0-applebin_macos-darwin_x86_64-fastbuild-ST-f2aadcfcab57/examples/command_line/tool/tool.LinkFileList
test/fixtures/command_line/spec.json

This still causes there to be two configurations of lib_swift and lib_impl, but at least it's not because of the minimum OS version anymore.

Use the same minimum OS version for macOS app and test

---

test/fixtures/cc/spec.json
xcodeproj/internal/target.bzl

Fixes #306.
This is why `depset` exists.

Fix explosive memory use of inefficient `_process_dependencies()`

---

test/internal/opts/process_compiler_opts_tests.bzl
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/SearchPaths.swift
xcodeproj/internal/opts.bzl
xcodeproj/internal/target.bzl

By specifying `SYSTEM_HEADER_SEARCH_PATHS` in Xcode build settings.
Partially addresses https://github.com/buildbuddy-io/rules_xcodeproj/issues/82.
Allows [Yams](https://github.com/jpsim/Yams) to compile.

Support `includes` in cc_library

---

test/internal/xcodeproj_tests/xcodeproj_tests_tests.bzl
xcodeproj/internal/xcodeproj_tests.bzl

With multiple fixtures per package there were name collisions.

Fix xcodeproj_tests  test names

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/gen_dir
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/gen_dir

These should have been deleted with #319.

Remove missed gen_dir

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

This is the same as `$GEN_DIR` for normal builds, but is different for Index Builds. `PBXBuildFile`s will use the `$GEN_DIR` version, so indexing might get messed up until they are normally generated. It's the best we can do though as we need to use the `gen_dir` symlink.

Copy generated files to `$BUILD_DIR/bazel-out`

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateProject.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/Fixtures.swift

Indexing will use a different `--output_base`, so we need to move this symlink into `$BUILD_DIR`, which is also different for indexing.

Move `bazel-out` symlink to `$BUILD_DIR`

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/AddTargetsTests.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/installer.template.sh
xcodeproj/internal/xcodeproj.bzl

Fixes #323.
This merges the "Setup" and "Bazel Generated Files" targets into a "Bazel Dependencies" target. This target is a dependency of every other target. And most importantly, it now has a different run script to fetch external repositories if there are no generated files.

Fetch Bazel External Repositories as part of build

---

xcodeproj/internal/configuration.bzl
xcodeproj/internal/product.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/target_id.bzl

First part of many to split apart target.bzl

[Pt1] Start to split up target.bzl

---

tools/generator/src/Environment.swift
tools/generator/src/Generator+AddBazelDependenciesTarget.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/installer.template.sh

We now only set `externalFileListPath` as an `outputFileListPaths` if there are external files. If a project doesn't have external or generated files we no longer create the `Bazel Dependencies` target. Finally, if there is no `Bazel Dependencies` target, we don't try to run its scheme during install.

Handle projects with no external dependencies

---

examples/command_line/Tests/SwiftGreetingsTests.swift
examples/command_line/lib/BUILD
examples/command_line/lib/lib.swift
examples/command_line/lib/private_lib.c
examples/command_line/lib/private_lib.h
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/generated.rsynclist
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/modulemaps.fixed.xcfilelist
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/modulemaps.xcfilelist
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-4fb8349bf067/examples/command_line/Tests/LibSwiftTests.__internal__.__test_bundle.LinkFileList
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-4fb8349bf067/examples/command_line/tool/tool.LinkFileList
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/generated.rsynclist
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/modulemaps.fixed.xcfilelist
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/modulemaps.xcfilelist
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-fastbuild-ST-8946c8252059/examples/command_line/Tests/LibSwiftTests.__internal__.__test_bundle.LinkFileList
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-fastbuild-ST-8946c8252059/examples/command_line/tool/tool.LinkFileList
test/fixtures/command_line/bwx_spec.json
xcodeproj/internal/target.bzl
xcodeproj/repositories.bzl

Related to #94.
This adds support for `private_deps`.
| Before | After |
| - | - |
| <img width="665" alt="CleanShot 2022-04-24 at 20 57 45@2x" src="https://user-images.githubusercontent.com/158658/165008544-93166848-015f-4fa4-bb70-496c9b228f59.png"> | <img width="454" alt="CleanShot 2022-04-24 at 20 58 39@2x" src="https://user-images.githubusercontent.com/158658/165008554-c08e516d-a0a3-4367-b192-185772e06495.png"> |

Use `SwiftInfo` `compilation_context`

---

xcodeproj/internal/target.bzl

Passing `None` means to take the inputs as is from `transitive_infos`, which is what we want for `_skip_target`.

Fix incorrect passing of `attrs_info`

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj.bzl

Similar to our generated inputs collection, we can now specify output groups to cause the building of desired outputs. This is needed for Build with Bazel.
We currently support two modes: build (`b`) and indexing (`i`). The build mode will collect outputs needed by Xcode for a build, run, or test to work. The indexing mode will collect outputs needed by Xcode's indexing processes.
For example, this will build the files needed for indexing of `PathKit`:
```
bazel build --output_groups='i @com_github_kylef_pathkit//:PathKit darwin_arm64-fastbuild'
```

Add output file collection

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
tools/generator/src/BuildMode.swift
tools/generator/src/Generator+AddBazelDependenciesTarget.swift
tools/generator/src/Generator+CreateProject.swift
tools/generator/test/CreateProjectTests.swift

The `Generate Files`/`Fetch External Repositories` script is now called `Bazel Build` when building with Bazel. The script differs by adding additional `--output_group` flags based on the contents of the `$(BAZEL_BUILD_OUTPUT_GROUPS_FILE)` file. We currently don't create this file, so nothing new happens yet, but we will in the future to cause this run script to actually build what is being requested of the current build, using the new output file collection output groups.

Build requested output groups in "Bazel Build"

---

test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
tools/generator/src/Environment.swift
tools/generator/src/Generator+CreateXCSchemes.swift
tools/generator/src/Generator+CreateXCSharedData.swift
tools/generator/src/Generator+CreateXcodeProj.swift
tools/generator/src/Generator.swift
tools/generator/test/CreateXCSharedDataTests.swift
tools/generator/test/CreateXcodeProjTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift

Related to #101.
- Added stub for `createXCSchemes`.
- Added implementation for `createXCSharedData`.
- Updated `createXcodeProj` to accept the shared data.
- Added basic test for `createXCSharedData`.
- Updated test for `createXcodeProj` to include shared data.
The logic for creating the schemes will be in the next PR.

Add basic plumbing for implementing the generation of Xcode schemes

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

This is just to better match Xcode's behavior.

Move `-filelist` to be before other linker settings

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

This resolves some PCM related warnings, but also makes handling these types of targets easier in Build with Bazel mode.
Note, this change does cause the resource bundles to have `OTHER_LDFLAGS` set, but it does no harm, and for bundles that do have executables it would be needed anyway.

Use Objective-C instead of Swift for compile stub

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+SetTargetConfigurations.swift

While these don't see to need it like `CODE_SIGN_ENTITLEMENTS` does, it makes it more clear these are using copied generated files, and it sets a nice pattern to prevent issues from popping up in the future (especially if XCBuild decides to care about these files).

Use `$(GEN_DIR)` for more files referenced by build settings

---

xcodeproj/repositories.bzl

Found via setting `--incompatible_disallow_empty_glob`
`PriorityQueueModule` does not exist in Swift collections 1.0.2

Remove non-existent PrioritityQueue target from Swift collections

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+CreateProject.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/PBXProductType+Extensions.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/Fixtures.swift

When launching an application with Xcode, it sets `DYLD_LIBRARY_PATH` to include the `BUILT_PRODUCTS_DIR` of every target in the build graph of the target being run. For our projects, this is a lot of paths, and with enough targets it can cause a crash in `dlyd` here: https://github.com/apple-oss-distributions/dyld/blob/419f8cbca6fb3420a248f158714a9d322af2aa5a/dyld/DyldProcessConfig.cpp#L1027
```
Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x00000001228f8000
Exception Codes: 0x0000000000000002, 0x00000001228f8000
VM Region Info: 0x1228f8000 is in 0x1228f8000-0x122930000;  bytes after start: 0  bytes before end: 229375
REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
mapped file …
```

Work around `DYLD_LIBRARY_PATH` issue

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/tvos_app/bwx.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/tvos_app/bwx.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
tools/generator/src/Generator+CreateFilesAndGroups.swift

So it seems this one does need to use `GEN_DIR` as well, it was just masked by a different change.
Fixes a bug caused by #375.

Fix off-by-one Info.plist handling

---

WORKSPACE
buildbuddy.yaml

Related to cgrindel/bazel-starlib#140.
This PR should allow `bazel test //...` to be successful.

Upgrade `rules_bazel_integration_test` to 0.7.0

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO.swift
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/src/Outputs.swift
tools/generator/test/ProcessTargetMergesTests.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/output_files.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/target.bzl

These will be used by Build with Bazel to copy the outputs to the places needed by Xcode during build/run/test.

Pass output files to generator

---

doc/design/high-level.md
examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddBazelDependenciesTarget.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/installer.template.sh

This is temporary until https://github.com/bazel-contrib/rules_bazel_integration_test/issues/62 is addressed.

Rename "Bazel Dependencies" target to remove space

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+WriteXcodeProj.swift
tools/generator/test/Fixtures.swift

This ensures that the swiftmodule file are copied out of the Intermediates and into the Products directory.

Force Swift compile to happen if files are copied

---

xcodeproj/internal/linker_input_files.bzl

Seems that `objc.library` already includes these libraries.

Remove redundant `objc.cc_library` processing

---

test/internal/opts/process_compiler_opts_tests.bzl
xcodeproj/internal/opts.bzl

This addresses a compilation error when building a generated project using Build with Xcode.
```
error: values for '-debug-prefix-map' must be in the format 'original=remapped', but '-sdk' was provided
```
When options came through like the following:
```
-debug-prefix-map
__BAZEL_XCODE_DEVELOPER_DIR__=DEVELOPER_DIR
```
the `__BAZEL_XCODE_DEVELOPER_DIR__=DEVELOPER_DIR` value was being filtered out leaving the `-debug-prefix-map` without its required second value.
This fix adds `-debug-prefix-map` to the set of options that should be skipped for processing.

Add -debug-prefix-map to _SWIFTC_SKIP_OPTS

---

examples/ios_app/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ExampleObjcTests.__internal__.__test_bundle.xcscheme
examples/ios_app/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ExampleTests.__internal__.__test_bundle.xcscheme
examples/ios_app/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ExampleUITests.__internal__.__test_bundle.xcscheme
examples/ios_app/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/ExampleObjcTests.__internal__.__test_bundle.xcscheme
examples/ios_app/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/ExampleTests.__internal__.__test_bundle.xcscheme
examples/ios_app/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/ExampleUITests.__internal__.__test_bundle.xcscheme
test/fixtures/command_line/bwb.xcodeproj/xcshareddata/xcschemes/LibSwiftTests.__internal__.__test_bundle.xcscheme
test/fixtures/command_line/bwx.xcodeproj/xcshareddata/xcschemes/LibSwiftTests.__internal__.__test_bundle.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/tests.xcscheme
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/tests.xcscheme
test/fixtures/tvos_app/bwb.xcodeproj/xcshareddata/xcschemes/ExampleTests.__internal__.__test_bundle.xcscheme
test/fixtures/tvos_app/bwb.xcodeproj/xcshareddata/xcschemes/ExampleUITests.__internal__.__test_bundle.xcscheme
test/fixtures/tvos_app/bwx.xcodeproj/xcshareddata/xcschemes/ExampleTests.__internal__.__test_bundle.xcscheme
test/fixtures/tvos_app/bwx.xcodeproj/xcshareddata/xcschemes/ExampleUITests.__internal__.__test_bundle.xcscheme
tools/generator/src/Generator+CreateXCSchemes.swift
tools/generator/test/CreateXCSchemesTests.swift

This unsets the executable for the launch action of a test target scheme.

Prevent error when "running" a test scheme

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
xcodeproj/internal/bazel_integration_files/create_lldbinit.sh

Ideally indexing results would bring you to the same location as the Project navigator, but until we fix that (if we even can), this change adds indexing based `bazel-out/` and `external/` directories to `target.source-map`.

Fix breakpoints for indexing based paths

---

xcodeproj/internal/output_files.bzl

This makes it easier for future changes that want to look at these files.

Leave spaces in output group map filenames

---

examples/ios_app/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/BazelDependencies.xcscheme
test/fixtures/cc/bwb.xcodeproj/xcshareddata/xcschemes/BazelDependencies.xcscheme
test/fixtures/command_line/bwb.xcodeproj/xcshareddata/xcschemes/BazelDependencies.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/BazelDependencies.xcscheme
test/fixtures/tvos_app/bwb.xcodeproj/xcshareddata/xcschemes/BazelDependencies.xcscheme
tools/generator/src/Generator+CreateXCSchemes.swift
tools/generator/test/CreateXCSchemesTests.swift

The `BazelDependencies` scheme wouldn't touch the `$BAZEL_BUILD_OUTPUT_GROUPS_FILE` file, which means the `BazelDependencies` target would rebuild whatever was last built, instead of only generated files. Now the `BazelDependencies` scheme deletes the `$BAZEL_BUILD_OUTPUT_GROUPS_FILE` file.

Prevent extra output group building with `BazelDependencies` scheme

---

xcodeproj/internal/output_group_map.bzl

This should fix some errors due to files containing spaces in their path not being copied correctly.

Fix merging logic with spaces

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
xcodeproj/internal/input_files.bzl

This prevents the `generated_inputs` output group from having unnecessary files in it. This filtering is very redundant, and error prone (as shown by this and previous changes applying missing filtering). This will get addressed with the forthcoming input file collection refactor.

Apply filtering logic to `generated` `extra_files`, and `xccurrentversions` as well

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
tools/generator/src/BuildMode.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/Generator.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurations.swift

This reduces rsync churn for targets without Info.plists, like `cc_test` targets.

Stop generating Info.plists when building with Bazel

---

examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/ExampleResources.xcscheme
examples/ios_app/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/ExternalResources.xcscheme
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateProducts.swift
tools/generator/src/PBXProductType+Extensions.swift
tools/generator/test/Fixtures.swift

This partially reverts e5ccba4edd16dd13335a8ceaa6457c7648c1173a for bundles. Seems Xcode will use the `BUILT_PRODUCTS_DIR` of the app if this product association isn't setup. We might be able to fix this another way in the future.

Fix copying of resource bundles

---

examples/ios_app/TestingUtils/BUILD

Should have been updated in https://github.com/buildbuddy-io/rules_xcodeproj/pull/372.

Fix TestingUtils expected answer

---

tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Outputs.swift

This makes the transition to consolidated targets easier, as they won't have access to the actual outputs, but still need to know if there are outputs of certain types.

Convert output `nil` checks to computed properties

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

Filter out non-header files from Compile Source phase

---

tools/generator/src/Environment.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+DisambiguateTargets.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/Generator+SetTargetDependencies.swift
tools/generator/test/DisambiguateTargetsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurations.swift

For now this just has the single `targets` property. Consolidated targets will add more properties to it.

Add `DisambiguatedTargets` wrapper type

---

test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
tools/generator/src/BuildSettingConditional.swift
tools/generator/src/DTO.swift
tools/generator/test/BuildSettingConditionalTests.swift

`BuildSettingConditional` will be used by consolidated targets, along with `BuildSetting`s, to specify per-configuration build settings.

Add `BuildSettingConditional`

---

tools/generator/src/BuildSettingConditional.swift
tools/generator/test/BuildSettingConditionalTests.swift

So that a conditional isn't both equal and less than itself at the same time.
I'm not sure if this would ever manifest itself in a real way, but it violates the `Comparable` contract.

Fix `BuildSettingConditional` comparisons against itself

---

tools/generator/src/BuildSettingConditional.swift
tools/generator/test/BuildSettingConditionalTests.swift

Xcode prefers `sdk` before `arch`.

Reorder build setting conditionals

---

tools/generator/src/BuildSettingConditional.swift

Similar to #476.
Longer term `environment` will be removed in favor of using `Platform.name`.

Sort `nil` version of device `environment` lower

---

examples/multiplatform/Lib/BUILD
examples/multiplatform/Lib/Lib.swift
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.rsynclist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.rsynclist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwx_spec.json

Generated files are one of the trickiest things to handle with consolidated targets, so we should have an example of it in our fixtures.

Use a generated file in the multiplatform example

---

test/fixtures/cc/bwb.xcodeproj/xcshareddata/xcschemes/@examples_cc_external___lib_impl.xcscheme
test/fixtures/cc/bwb.xcodeproj/xcshareddata/xcschemes/__examples_cc_lib2_lib_impl.xcscheme
test/fixtures/cc/bwb.xcodeproj/xcshareddata/xcschemes/__examples_cc_lib_lib_impl.xcscheme
test/fixtures/cc/bwx.xcodeproj/xcshareddata/xcschemes/@examples_cc_external___lib_impl.xcscheme
test/fixtures/cc/bwx.xcodeproj/xcshareddata/xcschemes/__examples_cc_lib2_lib_impl.xcscheme
test/fixtures/cc/bwx.xcodeproj/xcshareddata/xcschemes/__examples_cc_lib_lib_impl.xcscheme
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/Lib_(iOS).xcscheme
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/Lib_(macOS).xcscheme
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/Lib_(tvOS).xcscheme
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/Lib_(watchOS).xcscheme
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/Lib_(iOS).xcscheme
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/Lib_(macOS).xcscheme
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/Lib_(tvOS).xcscheme
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/Lib_(watchOS).xcscheme
tools/generator/src/PBXTarget+Extensions.swift
tools/generator/test/PBXTarget+ExtensionsTests.swift

Part of https://github.com/buildbuddy-io/rules_xcodeproj/issues/421.
Non-toplevel targets need to use the target name, not the product name. This is only an issue when the target name is disambiguated.

Fix `buildableName` for disambiguated non-toplevel targets

---

test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
tools/generator/src/Environment.swift
tools/generator/src/Generator+ConsolidateTargets.swift
tools/generator/src/Generator.swift
tools/generator/test/ConsolidateTargetsTest.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/Target+Testing.swift

`Generator.consolidateTargets()` has tests, but isn't used yet, to make the PRs more reviewable.

Add `Generator.consolidateTargets()`

---

tools/generator/src/Generator+DisambiguateTargets.swift
tools/generator/test/DisambiguateTargetsTests.swift

Fixes #450.
Before this change we would add more to target names than needed, in particular we would add architecture when environment was enough, or add environment when minimum OS version was enough.

Disambiguate targets less

---

tools/generator/src/Generator+DisambiguateTargets.swift
tools/generator/test/DisambiguateTargetsTests.swift

This changes the configuration to be on it's own in the name:
```
A (iOS) (abcde)
```
instead of:
```
A (iOS, abcde)
```
This is needed to support consolidated targets, which will have something like this when a configuration needs to be displayed:
```
A (iOS, tvOS) (abcde)
```

Move Configuration distinguisher logic up a level

---

test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/Lib_(macOS,_iOS,_tvOS).xcscheme
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/Lib_(watchOS).xcscheme
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/Lib_(macOS,_iOS,_tvOS).xcscheme
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/Lib_(watchOS).xcscheme
tools/generator/src/Generator+ConsolidateTargets.swift
tools/generator/test/ConsolidateTargetsTest.swift

Xcode gets confused when a watchOS App target depends on a consolidated iOS/watchOS dependency, so we just don't let it get into that situation.

Fix watchOS consolidation bug

---

tools/generator/src/Generator+CreateFilesAndGroups.swift

A project that has a custom rule which generates a `xcassets` with a `AppIcon.appiconset` fails to build due to the fact that `rsynclist` contained the generated `xcassets` but `generated_inputs` didn't. We need to filter out the folders from the generated files list for this to work correctly.

Filter folders from rsynclist

---

tools/generator/src/BuildSettingConditional.swift
tools/generator/src/DTO.swift
tools/generator/src/Generator+ConsolidateTargets.swift
tools/generator/test/ConsolidateTargetsTest.swift
tools/generator/test/DisambiguateTargetsTests.swift

Before this change, if you have minimum OS differences in your tree, and environment differences, you would get 3 consolidated targets instead of two (one proper consolidation and then 2 non-consolidated target). Now the consolidation tries to group like targets together more. Things can still get odd if you somehow have unique configurations of a target, as this just performs a simple sort and bucket for now.

Group sub-consolidations

---

xcodeproj/internal/xcodeproj.bzl

Before this change every input would be an implicit output. Right now that is fine, but if we add inputs that we don't need to change, then this change is needed.

Fix over-specifying of transition computed outputs

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+SetTargetConfigurations.swift

Part of https://github.com/buildbuddy-io/rules_xcodeproj/issues/415.
This is needed for SwiftUI Previews.

Correctly filter `-g` from PCM compilation

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/ld.sh
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/ld.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/ld.sh
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/ld.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/ld.sh
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/ld.sh
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
xcodeproj/internal/bazel_integration_files/ld.sh
xcodeproj/internal/bazel_integration_files/swiftc.py

This is the same logic that we use in the ld stub, for the same reason: the `PATH` and `DEVELOPER_DIR` isn't set correctly for us, so we have to infer what `DEVELOPER_DIR` is. We also force the use of the default toolchain, which means this currently doesn't work correctly with custom toolchains.

Use the correct version of swiftc for BwB SwiftUI Previews

---

test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.rsynclist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.rsynclist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwx_spec.json
xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/provisioning_profiles.bzl
xcodeproj/internal/top_level_targets.bzl

We don't ever do anything with the files, so they don't need to be in the Project navigator.

Stop adding provisioning profiles to Project navigator

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

UI test bundles need to be code signed to launch.

Fix running UI tests when Building with Bazel

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddBazelDependenciesTarget.swift

We no longer perform the `Fix Info.plists` script during Index Build. This allows initial indexing to get further, before the project is built the first time.

Improve BwB initial indexing

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
xcodeproj/internal/bazel_integration_files/copy_outputs.sh

Bazel built zips have zeroed out timestamps. So if any unarchived items had the same modified size as before a change, rsync wouldn't copy them over. We now set the timestamps to be the time we unzip.

Fix non-`--define=apple.experimental.tree_artifact_outputs=1` syncing bug

---

test/internal/platform/BUILD
test/internal/platform/platform_info_to_dto_tests.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/platform.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/top_level_targets.bzl

This is needed for the `AppleResourceInfo` collection rework.

Convert `platform` into a Starlark module

---

xcodeproj/internal/resource_bundle_products.bzl

When resource bundles have multiple owners, which can happen if the same resource bundle is at multiple levels (e.g. includes in the top level bundle and inside another bundle), the `depset` wouldn't deduplicate the bundle paths. We now do a second deduplication pass.

Properly deduplicate `resource_bundles`

---

xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/providers.bzl

With the resource file collection rework, we no longer need the special logic around excluded dependencies.

Remove no longer needed `InputFileAttributesInfo.excluded`

---

xcodeproj/internal/providers.bzl

Was accidentally committed while working on a refactor.

Remove unused `INPUT_FILE_ATTRIBUTES`

---

xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Better reflects the reason we are tracking them.

Rename `required_links` to `non_mergable_targets`

---

xcodeproj/internal/input_files.bzl

`input_files.collect` requires `attrs_info` to not be `None`.

Simplify transitive `attrs_info` check

---

xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/provisioning_profiles.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeprojinfo.bzl
xcodeproj/xcodeproj.bzl

The new name better reflects its new purpose.

Rename `InputFileAttributesInfo` to `XcodeProjAutomaticTargetProcessingInfo`

---

xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This will make generalized target generation easier.

Use `process_non_xcode_target` for resource bundles

---

xcodeproj/internal/resources.bzl

This was causing project generations to fail for me in a project I'm testing it with.

Remove extra parameter from function

---

xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/targets.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This moves the logic of determining if a target should become an Xcode target out of a hard coded function and into the provider.
It also slightly changes the behavior only generating targets by default for the rules we provide default information for. This causes "unsupported" rules like `swift_proto_library` to no longer become incomplete Xcode targets. A later change will adjust the generator to handle these use cases better.

Add `XcodeProjAutomaticTargetProcessingInfo.should_generate_target`

---

xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This is to support a future use case where we want to merge linker inputs for a slightly different use case related to Focused Projects.

Refractor `linker_input_files.merge`

---

xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/product.bzl

This will be used by future Focused Projects work.

Refactor `linter_input_files.get_primary_static_library` to return a `File`

---

xcodeproj/internal/providers.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This enables a sort of automatic Focused Project Build with Xcode mode, where it builds part of the build tree with Bazel that we can't translate properly into an Xcode target.
This isn't perfect yet though, as some of the dependencies of those targets might get made into Xcode targets from different branches in the build graph. Xcode based indexing also doesn't run for those targets, so the need for importing Bazel's index is higher. But since this unblocks some builds, it's worth getting in now and iterating on it.

Include outputs of non-Xcode projects in the generated inputs output group

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx_spec.json
test/internal/opts/process_compiler_opts_tests.bzl
tools/generator/src/Generator/SetTargetConfigurations.swift
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/opts.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl

Followup to https://github.com/buildbuddy-io/rules_xcodeproj/pull/586. Part of https://github.com/buildbuddy-io/rules_xcodeproj/issues/415.
- No longer set C related flags for Swift targets, as they aren't used and are instead passed to `OTHER_SWIFT_FLAGS` with `-Xcc` prefixes
- Set Swift PCM flags exactly as rules_swift does
- Correctly retrieve copts for `objc_library` targets by checking for `ObjcProvider` and changing the action that is queried based on that (this check will have to change once `ObjcProvider` is removed)
- Only set objc based flags for objc based actions
- Stop uniquing flags, as Bazel doesn't either

Apply compiler options the same as Bazel

---

xcodeproj/internal/input_files.bzl

Fixes issues with `ios_static_framework` and the like.

Stop assuming all `AppleBundleInfo` rules provide `AppleResourceInfo`

---

examples/command_line/tool/BUILD
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx_spec.json
xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl

Adds logic to support the `codesignopts` property on rules
as part of Support `macos_command_line_application` #99

Support `codesignopts`

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/top_level_targets.bzl

This ensures that header-less `apple_static_framework_import` etc. work.
The method for collecting these files probably won't work as-is when we add support for `ios_framework` etc. We will need to filter out files that will be produced by Xcode targets.

Add framework files to `extra_files`

---

xcodeproj/internal/files.bzl
xcodeproj/internal/input_files.bzl

Part of #237.
Also rename it to `normalized_file_path` and move it to `files.bzl`. This will allow its use outside of `input_files.bzl`.
`.xcdatamodel` isn't included because we need to access the underlying files, similar to localized files.

Expand `_normalized_file_path` to more folder types

---

xcodeproj/internal/installer.template.sh

The only file that remains is `generated.copied.xcfilelist`.

Fix One Time Setup check after generated files rework

---

test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
tools/generator/src/Extensions/Sorting.swift

Use parent sort key as well, since multiple resources can be named the same thing in consolidated targets.

Make file sorting more deterministic

---

WORKSPACE
examples/multiplatform/Lib/BUILD
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/external.xcfilelist
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/external.xcfilelist
test/fixtures/multiplatform/bwx_spec.json

Add `apple_dynamic_xcframework_import` example

---

test/fixtures/generator/BUILD
test/internal/bazel_labels/BUILD.bazel
test/internal/bazel_labels/absolute_tests.bzl
test/internal/bazel_labels/parse_tests.bzl
test/internal/xcode_schemes/collect_top_level_targets_tests.bzl
test/internal/xcode_schemes/model_tests.bzl
tools/generator/BUILD
tools/generator/xcodeproj_targets.bzl
xcodeproj/internal/bazel_labels.bzl
xcodeproj/internal/workspace_name_resolvers.bzl
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/xcodeproj.bzl

- Add `workspace_name_resolvers` module to expose `repository_name()` and `package_name()`. 
- This was added so that a different implementation could be injected into unit tests.
- Add `bazel_labels` module to normalize label values provided to `xcodeproj` and `xcode_schemes`. 
- The `make_bazel_labels` function allows for the injection of a custom `workspace_name_resolvers` module. 
- In a later PR, we will add code to validate that the provided labels exist.
- Update `xcode_schemes` module to include `make_xcode_schemes`. 
- This allows a custom `bazel_labels` module to be injected.
- Update `xcodeproj` macro to accept and process `schemes`. 
- This logic combines any targets provided directly to the macro and any top-level targets specified in the schemes.
- Add …

Update `xcodeproj` macro to process Xcode schemes

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx_spec.json
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/search_paths.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This applies this change from rules_swift: https://github.com/bazelbuild/rules_swift/blob/3bc7bc164020a842ae08e0cf071ed35f0939dd39/swift/internal/compiling.bzl#L1239-L1241.

Add missing header search paths

---

tools/generator/src/Generator/WriteXcodeProj.swift

Fixes #648.
If a project doesn't have generated, external, or compile stub files, we didn't create the proper internal directory before trying to copy over the compiler stubs. We now create the requires parent directories.

Fix project generation for simple projects

---

tools/generator/src/Generator/AddBazelDependenciesTarget.swift

Fixes #651.
We need to always add the `BazelDependencies` target when building with Bazel.

Fix simple BwB projects

---

test/internal/bazel_labels/normalize_tests.bzl
test/internal/xcode_schemes/collect_top_level_targets_tests.bzl
xcodeproj/internal/bazel_labels.bzl

If the label is for the default repository, omit the repository name.

Update `bazel_labels.normalize` to use shorthand notation

---

doc/faq.md
examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO/Project.swift
tools/generator/src/Generator/Generator.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/xcodeproj.bzl

It's a valid setup to have a "stub" top level target, so we shouldn't warn on this. I've added something to the FAQ though, for those expecting a merge that didn't happen.

Remove invalid merges warning

---

.swiftformat
.swiftlint.yml
swiftlint

- `swiftformat`: Do not perform any indenting as it indents multi-line string values. The `--indentstrings false` only ensures that the string is not indented more than the start line.
- `swiftlint`: First pass at config. It excludes test directories and disables some rules that are not relevant for this repository. There are other warnings and errors. However, they may be legitimate. If we enable a CI check, we will want to address those.

Fix `.swiftformat` configuration and add first pass for `swiftlint`

---

tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/SetTargetConfigurations.swift

`swiftformat --config .swiftformat --rules braces,wrapMultilineStatementBraces --verbose .`
It turns out #677 was not quite right. I only ran `braces` in that PR. I should have run `braces` along with `wrapMultilineStatementBraces` as the `wrapMultilineStatementBraces` takes precedence over `braces`.

Apply `wrapMultilineStatementBraces` for `swiftformat`

---

examples/command_line/tool/BUILD
examples/command_line/tool/Launchd.plist
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/command_line/bwx_spec.json
test/internal/launchd_plists/BUILD
test/internal/launchd_plists/get_file_from_objc_provider_tests.bzl
xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/launchd_plists.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/top_level_targets.bzl

Add support for both BwB and BwX for the `launchdplists` rules_apple attribute.
The `launchdplists` property takes a list of `.plist` labels which are then merged by rules_apple into a single `.plist`. This `.plist` is then embedded into the `macos_command_line_application` binary.
rules_apple embeds the launchd plist into the `__TEXT` section of the binary under the section `__launchd_plist` ([see here](https://github.com/bazelbuild/rules_apple/blob/56c54f25253b616bdd852b569023a437a4f95768/apple/internal/macos_binary_support.bzl#L188-L194))
Closes #99

Add support for `launchdplists`

---

tools/generator/src/Generator/ConsolidateTargets.swift

There is no need to merge these, as the consolidation logic will reject targets with different resource bundle targets, since they also show up in `dependencies`.

Simplify `ConsolidatedTarget.resourceBundleDependencies` calculation

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO/Project.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This will allow us to properly create schemes for hosted targets, such as Watch Apps or Application Extensions.

Add `Project.targetHosts` to the DTO

---

examples/ios_app/Example/BUILD
examples/ios_app/Example/Launch.storyboard
examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx_spec.json

Adds a `launch_storyboard` to the ios_app example. Related to #96

Add `launch_storyboard` to ios example

---

tools/generator/src/Extensions/PBXProductType+Extensions.swift

Part of #104.
This represents a stub app bundle that doesn't have a compile phase, and shouldn't have its own scheme.

Add `.messagesApplication` to `hasCompilePhase` and `shouldCreateScheme`

---

examples/multiplatform/Lib/BUILD
examples/multiplatform/Lib/Info.plist
examples/multiplatform/iOSApp/BUILD
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx_spec.json
xcodeproj/internal/files.bzl
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/search_paths.bzl

We still don't support `*_framework` rules (that's for a future Milestone), but dbd2112b07c429626e310dad67934a36fdae9f85 broke projects that use those rules. Now those projects continue to build, just statically linking like before.

Fix `ios_framework` issue

---

examples/multiplatform/AppClip/AppClip.swift
examples/multiplatform/AppClip/Assets.xcassets/AccentColor.colorset/Contents.json
examples/multiplatform/AppClip/Assets.xcassets/AppIcon.appiconset/Contents.json
examples/multiplatform/AppClip/Assets.xcassets/Contents.json
examples/multiplatform/AppClip/BUILD
examples/multiplatform/AppClip/ContentView.swift
examples/multiplatform/AppClip/Entitlements.entitlements
examples/multiplatform/AppClip/Info.plist
examples/multiplatform/AppClip/PreviewContent/Preview Assets.xcassets/Contents.json
examples/multiplatform/xcodeproj_targets.bzl
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-28ac48b4d0bf/examples/multiplatform/AppClip/AppClip.LinkFileList
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-e7c08a7bb9db/examples/multiplatform/AppClip/AppClip.LinkFileList
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-787a8770ecb8/examples/multiplatform/AppClip/AppClip.LinkFileList
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-6fabcb83ef01/examples/multiplatform/AppClip/AppClip.LinkFileList
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
test/fixtures/multiplatform/bwx_spec.json

Add App Clip example

---

test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/BazelLabel.swift
tools/generator/test/BazelLabel+TestExtensions.swift
tools/generator/test/BazelLabelTests.swift

I implemented the type such that it parses early. If I implemented exactly like `TargetID`, the client of the type would not know if they had a valid value or not. In other words, I wanted to ensure that a `label.name` would not fail.
Once this is merged, I can update the rest of the code to use it.

Introduce `BazelLabel` type

---

examples/command_line/tool/BUILD
examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-0139d977e630/examples/command_line/tool/tool.link.params
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-59a3e2f8ef60/examples/command_line/tool/tool.link.params
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/simple/bwb.xcodeproj/project.pbxproj
test/fixtures/simple/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/FilePathResolver.swift
tools/generator/test/Fixtures.swift

The codesign digest settings were causing Rosetta to fail. Having `$(PROJECT_DIR)` in build settings was causing `link.params` to fail.

Fix running of `//examples/command_line/tool`

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO/Project.swift
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/xcodeproj.bzl

Fixes #705.
We now correctly include the `BazelDependencies` target.
This isn't perfect, there is still situations which we should include `BazelDependencies` but we aren't, but they can be addressed with further Focused Projects work.

Fix simple BwX projects with unfocused targets

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/AddTargetsTests.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurationsTests.swift
tools/generator/test/SetTargetDependenciesTests.swift
xcodeproj/internal/target_properties.bzl

Part of #633.
This fixes some compilation error for BwX Focused Projects (e.g. rules_spm). It also unlocks the ability to no longer have to copy swiftmodules into Derived Data, which will be a followup change.

Use `$BAZEL_OUT` for Bazel generated swift modules

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/simple/bwb.xcodeproj/project.pbxproj
test/fixtures/simple/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/test/Fixtures.swift

Ideally we would only add quotes if the variable being expanded has spaces, but I couldn't quite work out how to do that.

Fix handling of spaces in link.param environment variables

---

xcodeproj/internal/providers.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeprojinfo.bzl

With recent changed we no longer need to copy swiftmodules for compilation or linking.

Stop copying unfocused swiftmodules

---

test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-0139d977e630/examples/command_line/tool/tool.link.params
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-59a3e2f8ef60/examples/command_line/tool/tool.link.params
tools/generator/src/DTO/Target+LinkerFlags.swift

Move `-exported_symbols_list` to be after loads

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-a0d0e3b8f217/Example/Example.link.params
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-a0d0e3b8f217/ExampleObjcTests/ExampleObjcTests.__internal__.__test_bundle.link.params
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-a0d0e3b8f217/ExampleTests/ExampleTests.__internal__.__test_bundle.link.params
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-dbg-ST-5534cb307cb8/examples/cc/tool/tool.link.params
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-0139d977e630/examples/command_line/Tests/LibSwiftTests.__internal__.__test_bundle.link.params
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-0139d977e630/examples/command_line/tool/tool.link.params
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-dbg-ST-5534cb307cb8/tools/generator/generator.link.params
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-dbg-ST-5534cb307cb8/tools/generator/test/tests.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-28ac48b4d0bf/examples/multiplatform/AppClip/AppClip.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-28ac48b4d0bf/examples/multiplatform/WidgetExtension/WidgetExtension.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-28ac48b4d0bf/examples/multiplatform/iMessageApp/iMessageAppExtension.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-28ac48b4d0bf/examples/multiplatform/iOSApp/iOSApp.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-e7c08a7bb9db/examples/multiplatform/AppClip/AppClip.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-e7c08a7bb9db/examples/multiplatform/WidgetExtension/WidgetExtension.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-e7c08a7bb9db/examples/multiplatform/iMessageApp/iMessageAppExtension.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-e7c08a7bb9db/examples/multiplatform/iOSApp/iOSApp.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/tvos-arm64-min15.0-applebin_tvos-tvos_arm64-dbg-ST-d6d3bf2233f2/examples/multiplatform/tvOSApp/tvOSApp.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/tvos-x86_64-min15.0-applebin_tvos-tvos_x86_64-dbg-ST-ae85ff5caa67/examples/multiplatform/tvOSApp/tvOSApp.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/watchos-arm64_32-min7.0-applebin_watchos-watchos_arm64_32-dbg-ST-01fecab27ffc/examples/multiplatform/watchOSAppExtension/watchOSAppExtension.link.params
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/watchos-x86_64-min7.0-applebin_watchos-watchos_x86_64-dbg-ST-2fd25852cc8a/examples/multiplatform/watchOSAppExtension/watchOSAppExtension.link.params
tools/generator/src/DTO/Target+LinkerFlags.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/test/Fixtures.swift

This will allow us to stop copying over unfocused archives in BwX mode.

Link to Bazel generated archives via `$BAZEL_OUT`

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
xcodeproj/internal/input_files.bzl
xcodeproj/internal/xcodeproj.bzl

We how force the `BazelDependencies` target if there are any Bazel generated files, which better matches what we were trying to do with the flag.

Improve `force_bazel_dependencies` check

---

xcodeproj/internal/top_level_targets.bzl

`AppleExecutableBinary.objc` doesn't have the linking information I thought it did.

Fix linking of some Apple binaries

---

xcodeproj/internal/providers.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Part of #633.
With recent changes this is no longer needed, as we link directly to the archives that exist in `$BAZEL_OUT`.

Stop copying unfocused archives

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/macos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/macos_app/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/swiftc.py
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/bazel_integration_files/copy_outputs.sh
xcodeproj/internal/bazel_integration_files/swiftc.py

Search paths (for Indexing) and linker flags (for Debugging) now point into `$BAZEL_OUT`.
The `Copy Bazel Outputs` script hasn't been removed, as it will be used later for diagnostics replay.

Stop copying swiftmodules in BwB mode

---

xcodeproj/internal/linker_input_files.bzl

Fixes #764.
It seems that the same library can be in collected multiple times.

Fix duplicate `LinkerInputs.staticLibraries` error

---

test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/command_line/bwx_spec.json
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwx_spec.json
xcodeproj/internal/info_plists.bzl
xcodeproj/internal/launchd_plists.bzl
xcodeproj/internal/top_level_targets.bzl

The `ObjcProvider` can be found under `AppleExecutableBinary.objc`.

Properly set `Info.list` for command line tools

---

xcodeproj/internal/output_files.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/xcodeproj.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This reverts 923861d14d32164766d6f1d2b85445749c79d82e and 3d79475e95d9f50cf61450274debab4375ddb65d.
While we didn't want to copy these, and we no longer copy any generated files, we still need to declare that we need them built.

Still declare unfocused outputs as generated inputs

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/SetTargetConfigurations.swift

This is because when this is set, Xcode uses the entitlements as provided instead of modifying them, which is needed in BwX mode.

Only set `CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION` in BwB

---

xcodeproj/internal/top_level_targets.bzl

Part of #779.
This handles custom rules that don't set `minimum_deployment_os_version `.

Default `minimum_deployment_os_version` to `minimum_os_version`

---

test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
xcodeproj/internal/compilation_providers.bzl
xcodeproj/internal/linker_input_files.bzl

Unfocused libraries were going down the "top level" path accidentally.

Stop extracting top level values for unfocused libraries

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl

It's only used in the top-level target case.

Default `avoid_deps`

---

xcodeproj/internal/compilation_providers.bzl

This doesn't pop up for top level targets with a single dep (which is all of our examples), but if we were to perform merging of providers at lower levels (which will be needed for a later change), then we currently need to "upgrade" `CcInfo` to `ObjcProvider` to get all of the linking information.

Properly merge mixed provider linking contexts

---

test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwx_spec.json
xcodeproj/internal/input_files.bzl

It can be useful to see the output of a `genrule`/custom rule.

Include generated `{Info,Launchd}.plist` files in Project navigator

---

xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj.bzl

This will be used in a future change for better forced-unfocused target detection.

Add `linker_input_files.get_library_static_libraries`

---

tools/extensionpointidentifiers_parser/extensionpointidentifiers_parser.py
xcodeproj/internal/top_level_targets.bzl

Using the Bazel generated Info.plist to calculate `ExtensionPointIdentifier` adds an implicit dependency on `AssetCatalogCompile`. We only need to "merge" the hand provided Info.plists, which we do by processing multiple Info.plists for a target, in order.

Calculate `ExtensionPointIdentifier` without compiling XCAssets

---

xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/target_search_paths.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This will allow for the eventual de-stringification of `xcode_target`.

Convert `process_search_paths` to a Starlark module

---

tools/generator/src/Extensions/XCScheme+Extensions.swift
tools/generator/src/Generator/XCSchemeInfo+BuildActionInfo.swift
tools/generator/src/Generator/XCSchemeInfo+HostInfo.swift
tools/generator/src/Generator/XCSchemeInfo+TargetInfo.swift
tools/generator/src/Generator/XCSchemeInfo+TestActionInfo.swift

- Implement `Hashable` for `XCScheme.BuildableReference`, `XCSchemeInfo.HostInfo`, and `XCSchemeInfo.TargetInfo`.
- Update `XCSchemeInfo.BuildActionInfo` and `XCSchemeInfo.TestActionInfo` to store their `targetInfos` as `Set<XCSchemeInfo.TargetInfo>`.

Keep unique set of TargetInfo values in XCSchemeInfo structs

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
test/internal/platform/platform_info_to_dto_tests.bzl
tools/generator/src/DTO/Platform.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/BuildSettingConditionalTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/SetTargetConfigurationsTests.swift
tools/generator/test/Target+Testing.swift
tools/generator/test/XcodeScheme+ExtensionsTests.swift
xcodeproj/internal/platform.bzl
xcodeproj/internal/processed_target.bzl

This is needed to set it for resource bundles while unblocking the de-stringification of `xcode_target`.

Set `*_DEPLOYMENT_TARGET` in `generator`

---

xcodeproj/internal/fixtures.bzl
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_rule.bzl
xcodeproj/xcodeproj.bzl

This allows the rule to be named `xcodeproj` instead of `_xcodeproj`, which will help when we add Stardoc.

Split `xcodeproj` macro and rule into separate files

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

`xcode_target` now has all of the same information available, so we don't need two sources of truth.

Reuse `xcode_target` in place of `target` struct

---

tools/generator/src/DTO/Target.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/Generator.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/input_files.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Fixes #632.
Dependencies of unfocused targets are now "islands". Their scheme will build them in whatever mode is being used for the project, but their dependencies will be built with Bazel. These targets also won't be set as dependencies of other targets, preventing them from being built twice in BwX mode.

Stop building dependencies of unfocused targets twice in BwX mode

---

test/fixtures/generator/BUILD
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/external.xcfilelist
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/external.xcfilelist
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-dbg-ST-02316c4eb12c/tools/generator/generator.link.params
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-dbg-ST-02316c4eb12c/tools/generator/test/tests.link.params
test/fixtures/generator/bwx_spec.json
tools/generator/BUILD
tools/generator/xcodeproj_targets.bzl

This is mainly to have an example of `unfocused_targets` in the fixtures. While we don't have Bazel index importing we want to minimize the use of focused targets, as we don't have indexing for unfocused targets.

Set `unfocused_targets` for `generator`

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/simple/bwb.xcodeproj/project.pbxproj
test/fixtures/simple/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddTargets.swift
tools/generator/test/Fixtures.swift

The old way didn't wrap with quotes if it started with the build setting.

Fix more cases of link variables with spaces in build settings

---

examples/cc/BUILD
examples/command_line/BUILD
examples/ios_app/BUILD
examples/ios_app/test/fixtures/BUILD
examples/macos_app/BUILD
examples/multiplatform/BUILD
examples/simple/BUILD
examples/tvos_app/BUILD
examples/watchos_app/BUILD
test/fixtures/cc/BUILD
test/fixtures/command_line/BUILD
test/fixtures/macos_app/BUILD
test/fixtures/multiplatform/BUILD
test/fixtures/simple/BUILD
test/fixtures/tvos_app/BUILD
xcodeproj/internal/fixtures.bzl
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_rule.bzl

There has been some confusion on what targets should or need to be set on `xcodeproj.targets`. They should only be top-level targets, and not any of their dependencies. Setting non-top-level targets will result in misconfigured targets appearing in the project.

Rename `xcodeproj.targets` to `top_level_targets`

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
test/internal/platform/platform_info_to_dto_tests.bzl
tools/generator/src/BuildSettingConditional.swift
tools/generator/src/DTO/Platform.swift
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/src/Generator/DisambiguateTargets.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/BuildSettingConditionalTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/SetTargetConfigurationsTests.swift
tools/generator/test/Target+Testing.swift
tools/generator/test/XcodeScheme+ExtensionsTests.swift
xcodeproj/internal/platform.bzl

This also removes the need for a separate `environment` property.

Convert `Platform.name` into strongly typed `Platform.variant`

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
examples/multiplatform/watchOSAppExtension/BUILD
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
test/internal/platform/platform_info_to_dto_tests.bzl
test/internal/target/process_top_level_properties_tests.bzl
tools/generator/src/DTO/Platform.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/BuildSettingConditionalTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/SetTargetConfigurationsTests.swift
tools/generator/test/Target+Testing.swift
tools/generator/test/XcodeScheme+ExtensionsTests.swift
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/platform.bzl
xcodeproj/internal/top_level_targets.bzl

This should be set to the compilation minimum os version. The actual _deployment_ version is set in the `Info.plist`, which is handled by Bazel.

Correctly set `*_DEPLOYMENT_TARGET`

---

tools/generator/src/Extensions/XcodeScheme+Extensions.swift

Update error message with `alias` language when resolving labels for custom schemes.

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
xcodeproj/internal/input_files.bzl
xcodeproj/internal/resources.bzl
xcodeproj/internal/xcodeproj_rule.bzl

We now no longer show extra files for non-Xcode targets. This mainly means you don't get a bunch of extra `BUILD` files in Focused Projects.

Handle `extra_files` correctly with Focused Projects

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/macos_app/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
xcodeproj/internal/bazel_integration_files/copy_outputs.sh

To work around an Xcode "serial queue" bug, we need to make a "meaningful change" to swift modules.
https://ios-dev-at-scale.slack.com/archives/C5QA0UGR1/p1659130548904439?thread_ts=1654971314.938379&cid=C5QA0UGR1
I know this is all still commented code, but I plan to uncomment it in the future when implementing #402.

Handle `forced_swift_compile_file` better

---

tools/generator/src/Generator/XCSchemeInfo+BuildActionInfo.swift
tools/generator/src/Generator/XCSchemeInfo+LaunchActionInfo.swift
tools/generator/src/Generator/XCSchemeInfo+ProfileActionInfo.swift
tools/generator/src/Generator/XCSchemeInfo+TargetInfo.swift
tools/generator/src/Generator/XCSchemeInfo+TestActionInfo.swift
tools/generator/src/Generator/XCSchemeInfo.swift

- Simplify the collection of `TargetInfo` values.
- Apply `isTopLevel` filter to all collected `TargetInfo` values.
- Update `init?(resolveHostsFor:topLevelTargetInfos:)` to expect a `Sequence` of `TargetInfo` values.

Ensure `topLevelTargetInfos` is a unique `Set` in `XCSchemeInfo`

---

tools/generator/src/DTO/Target.swift
tools/generator/src/Generator/ProcessTargetMerges.swift
tools/generator/test/Fixtures.swift
tools/generator/test/ProcessTargetMergesTests.swift

The library being merged into a top level target might have a different minimum os version. Now that 1ab36b4c6814faa73849c71e9d02a20181c13336 has landed, we need to account for the differences.

Merge `Target.platform`

---

tools/generator/src/Extensions/Dictionary+Extensions.swift
tools/generator/src/Extensions/Optional+Extensions.swift
tools/generator/test/Dictionary+ExtensionTests.swift
tools/generator/test/Optional+ExtensionsTests.swift

- Add default context info to `Dictionary.value(for:context:message:)`, if no context or message is provided. The default context includes the function name, filename, and line number.
- Add default error message to `Optional.orThrow()`. The default error message includes the function name, filename, and line number.

Add default context info to `Dictionary` and `Optional` helpers

---

xcodeproj/internal/resources.bzl

This prevents incorrect files from appearing in the Project navigator, possibly at the expense of needed files appearing at all. This should only be an issue in BwX mode though.

Fix handling of odd `AppleResourceInfo` structures

---

xcodeproj/internal/resources.bzl

Fixes the type to match other label types.

Use `Label` type for `fozen_bundle.label`

---

tools/generator/src/Extensions/Platform+Extensions.swift
tools/generator/src/Generator/XCSchemeInfo+HostInfo.swift
tools/generator/src/Generator/XCSchemeInfo+TargetInfo.swift
tools/generator/test/Platform+ExtensionsTests.swift
tools/generator/test/XCSchemeInfo+HostInfoTests.swift

- Implement `compatibleWith()` for a `Sequence` of `Platform` values.
- Move `HostInfo` resolution logic to `HostInfo` file.
- Add unit tests for host resolution logic.

Implement best host logic when a host is not one of the top-level targets

---

test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx_spec.json
test/internal/xcode_schemes/model_tests.bzl
tools/generator/src/Generator/XcodeScheme+BuildFor.swift
tools/generator/xcodeproj_targets.bzl
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcode_schemes_internal.bzl

- Added a custom `build_target` with a `build_for` to `//tools/generator:xcodeproj`. This tests that the value is written by Starlark code and read by the Swift code.

Update Starlark to create `build_target` and `build_for`

---

test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
tools/generator/src/DTO/XcodeScheme.swift
tools/generator/src/Generator/XcodeScheme+BuildFor.swift
tools/generator/test/XCSchemeInfoTests.swift
tools/generator/test/XcodeScheme+BuildForTests.swift
tools/generator/test/XcodeSchemeTests.swift

Related to #573 
- Add `isEnabled` and `isDisabled` helpers to `XcodeScheme.BuildFor.Value`.
- Add `enableIfNotIDisabled()` to `XcodeScheme.BuildFor.Value`.
- Add logic to set `analyzing` for all targets.
- Add logic to set `archiving` for all targets with `running` enabled.

Add `archiving` and `analyzing` logic for `buildFor`

---

tools/generator/src/Extensions/XCScheme+Extensions.swift
xcodeproj/repositories.bzl

- Upgrade `tuist/XcodeProj` to version that includes `Hashable` implementation for `XCScheme.BuildableReference`.
- Remove `Hashable` implementation for `XCScheme.BuildableReference`

Upgrade `tuist/XcodeProj`

---

test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx_spec.json
test/internal/xcode_schemes/model_tests.bzl
tools/generator/src/Extensions/XCScheme+Extensions.swift
tools/generator/test/XCScheme+ExtensionsTests.swift
tools/generator/xcodeproj_targets.bzl
xcodeproj/internal/xcode_schemes.bzl

I failed to pass the custom values to the `XCScheme.LaunchAction`. This PR rectifies the issue.
- Pass custom command line arguments and environment variables.
- Added a custom environment variable to `tools/generator` custom scheme.
- Remove `working_directory` from `xcode_schemes.launch_action()`. It turns out that `XCScheme.LaunchAction` does not expose a `customWorkingDirectory` attribute. (#933).

Pass through custom arguments and environment variables to launch action

---

xcodeproj/internal/target_properties.bzl
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcode_schemes_internal.bzl

In preparation for generating the docs with `stardoc`, this PR fixes a few violations that were causing failures in parsing the docs.

Fix docstring formatting

---

WORKSPACE
buildbuddy.yaml
doc/BUILD.bazel
doc/rules-experimental.md
doc/rules-xcodeproj.md
xcodeproj/BUILD
xcodeproj/internal/BUILD

Addresses #214.
This PR adds the basic stardoc tooling in order to generate documentation for the public rules. This will allow to better understand the API that we provide. Some follow-up PRs might be needed to get more accurate documentation for certain rules that aren't yet properly documented.
Most of the tooling was inspired by the [`rules_apple`](https://github.com/bazelbuild/rules_apple/tree/master/doc/BUILD.bazel) implementation.

Add stardoc to generate rules docs

---

xcodeproj/internal/xcodeproj_rule.bzl

This is to make it easier to blanket unfocus some targets, which might might only conditionally exist.

Allow unfocusing "invalid" labels

---

test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-dbg-ST-5a06a31acc4f/tools/generator/generator.link.params
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/targets/darwin_x86_64-dbg-ST-e7deb5c809c7/tools/generator/generator.link.params
test/fixtures/generator/bwx_spec.json
tools/generator/src/Generator/ProcessTargetMerges.swift
tools/generator/test/Fixtures.swift
tools/generator/test/ProcessTargetMergesTests.swift
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl
xcodeproj/internal/xcodeprojinfo.bzl

This can result in multiple targets building the same code in BwX mode, but if that isn't desired a minimal target can be inserted to mimic the previous behavior.
This change makes working with SwiftUI Previews nicer, as you can create a demo application for each `swift_library`.

Remove single merge restriction on target merging

---

xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

If top-level targets have multiple dependencies, and they all remain focused targets, then the top-level target will be un-merged, with a compile stub.

Allow top-level targets to have multiple dependencies

---

doc/BUILD.bazel
doc/rules-xcodeproj.md
xcodeproj/BUILD
xcodeproj/xcodeproj.doc.bzl

Borrowed this workaround to improve the `xcodeproj` docs from [rules_apple](https://github.com/bazelbuild/rules_apple/blob/d7b8f7d45c9bb0533aee2ed7410d111a0d060f71/apple/ios.doc.bzl#L17-L19).

Create xcodeproj.doc to import rules instead of macro to improve generated docs with stardoc

---

xcodeproj/internal/opts.bzl

Without this, defines with quotes in them wouldn't be handled properly.

Properly escape `pcm_defines`

---

doc/rules-xcodeproj.md
examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx_spec.json
examples/tvos_app/Example/BUILD
test/fixtures/macos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx_spec.json
xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/top_level_targets.bzl

Related to #949.
Goal: Xcode finds the application icon and uses it for Xcode schemes.

Ensure application icons are specified correctly in Xcode project

---

tools/generator/src/Generator/XCSchemeInfo+LaunchActionInfo.swift
tools/generator/src/Generator/XCSchemeInfo+TargetInfo.swift
tools/generator/test/XCSchemeInfo+LaunchActionInfoTests.swift
tools/generator/test/XCSchemeInfo+TargetInfoTests.swift

Related to #906.
- Move the macro expansion logic to `XCSchemeInfo.TargetInfo` so that it can be shared with `XCSchemeInfo.TargetInfo` (subsequent PR).

Refactor macro expansion logic

---

doc/design/custom-xcode-schemes.md
doc/design/high-level.md

This is to make it clear that these are not living documents, but a snapshot in time when a design was being proposed. They are historical, and useful to know why something was implemented the way that it was. The implementations might/probably will change in the future without the documents being updated.

Add last updated dates to design docs

---

xcodeproj/internal/default_automatic_target_processing_aspect.bzl

Needed because of https://github.com/bazelbuild/rules_apple/commit/ef23d852551146403a95b02a42044bfb05dfc42c / https://github.com/bazelbuild/rules_apple/commit/e21eb921977fa908618bd2cd9caf009496f01390.

Fix Resource bundle detection

---

doc/BUILD.bazel
doc/rules-xcodeproj.md
xcodeproj/BUILD
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Also adjust the docs to use the macro again. This adds clarity around `schemes` and is needed for future changes to the macro.

Add more docs to `xcodeproj` macro

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/macos_app/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/simple/bwb.xcodeproj/project.pbxproj
test/fixtures/simple/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/CreateProject.swift
tools/generator/test/CreateProjectTests.swift

This var simply points to `$(SRCROOT)` and helps users who have relied on
this variable prior to using
rules_xcodeproj

Add `BAZEL_WORKSPACE_ROOT` build setting var

---

xcodeproj/internal/runner.template.sh

Before adding the abstraction of a runner it was relatively “easy” to build output groups yourself outside of Xcode. But now that there is a lot of ceremony handled by the runner, it's not so easy. This change makes it so you can add `--build_output_groups output_groups,here` to have the runner build those output groups instead of generate the project. The end result is that a command like the following:
```
bazel run //tools/generator:xcodeproj -- --build_output_groups some_output_group
```
will execute a command like this:
```
bazel --noworkspace_rc --bazelrc=tools/generator/generator.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc --bazelrc=.bazelrc build --config=rules_xcodeproj_build //tools/generator:xcodeproj.generator --output_groups=some_output_group
```

Add ability to build output groups from command-line

---

xcodeproj/internal/output_files.bzl
xcodeproj/internal/xcodeproj_rule.bzl

This allows building all of the bazel-generated files of a project with a single output group. The main use for this is populating a Remote Build Cache with artifacts for developers.

Add `all_targets` output group

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/cc/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/macos_app/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/macos_app/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/simple/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/tvos_app/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/bazel_integration_files/xcodeproj.bazelrc

This prevents output from the generator from appearing.

Remove `--ui_event_filters` from `rules_xcodeproj_generator`

---

xcodeproj/internal/runner.template.sh

Now that the runner being built has bazel output, and the generator being built has bazel output, adding this simple blank line really helps with readability.
New output:
```console
$ bazel run --config=cache //tools/generator:xcodeproj
INFO: Invocation ID: a1c9163b-bce2-4594-b773-65f56d79d83f
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/a1c9163b-bce2-4594-b773-65f56d79d83f
INFO: Analyzed target //tools/generator:xcodeproj (1 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //tools/generator:xcodeproj up-to-date:
bazel-bin/tools/generator/xcodeproj-runner.sh
INFO: Elapsed time: 0.225s, Critical Path: 0.00s
INFO: 2 processes: 2 internal.
INFO: Running command line: bazel-bin/tools/generator/xcodeproj-runner.sh
INFO: Streaming build results to: …
```

Improve readability of installer output

---

xcodeproj/internal/xcodeproj_rule.bzl

This enables the use of runfiles in those tools, though we currently don’t use runfiles.

Use `DefaultInfo.files_to_run` instead of `ctx.executable`

---

xcodeproj/internal/xcodeprojinfo.bzl

We will just include the two configurations in the project instead. Later we can hopefully consolidate them into a single target.

Skip `apple_universal_binary` targets

---

.gitattributes

This will collapse them by default in PRs and remove the files from language statistics. Reviewers can still check the diffs in the PR as needed.

Mark fixtures as generated

---

examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/cc/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/simple/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh

Typo in f32a22ceeab5d97c6bdcc39bcf5508f3f57e62b1.

Fix path for `create_xcode_overlay.sh`

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/targets/applebin_watchos-watchos_arm64_32-dbg-ST-0aca4f826326/watchOSAppExtension/watchOSAppExtension.link.params
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/targets/applebin_watchos-watchos_x86_64-dbg-ST-41d33441c9e6/watchOSAppExtension/watchOSAppExtension.link.params
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/targets/applebin_watchos-watchos_arm64_32-dbg-ST-e7f8a06fd4b6/watchOSAppExtension/watchOSAppExtension.link.params
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/targets/applebin_watchos-watchos_x86_64-dbg-ST-4f1fd91c92ee/watchOSAppExtension/watchOSAppExtension.link.params
examples/integration/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/targets/applebin_macos-darwin_x86_64-dbg-ST-c70783d5b209/tools/generator/generator.link.params
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/targets/applebin_macos-darwin_x86_64-dbg-ST-9d72e44f2a37/tools/generator/generator.link.params
test/fixtures/generator/bwx_spec.json
tools/generator/src/Generator/ProcessTargetMerges.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

This reverts commit e79802565ce0618a829feb01c214072bb8ff257c: https://github.com/buildbuddy-io/rules_xcodeproj/pull/937#issuecomment-1232177691.
Allowing a target to be both merged and unmerged can commonly result in colliding output paths for swiftmodules.
It also improves the target merging to prevent all versions of a target from merging, to prevent issues with target consolidation.

Revert "Remove single merge restriction on target merging (#937)"

---

doc/BUILD.bazel

Was broken in 4d80eac7dab4ff56ec4fba10e448e15d6ed6f156.

Fix `//doc:update` to work without convenience symlinks

---

xcodeproj/internal/xcodeproj_rule.bzl

Typo in cd98712b7bb7e69f52f7fd836d3da10ac63d1fd6.

Fix BwX unfocused target linking

---

xcodeproj/internal/xcodeprojinfo.bzl

After https://github.com/buildbuddy-io/rules_xcodeproj/pull/1004, when using a `device_and_simulator` rule, the project generation fails with the following error:
```bash
ERROR: .../xcodeproj/BUILD.bazel:53:21: in device_and_simulator rule //bazel/xcodeproj:targets:
Traceback (most recent call last):
File "/private/var/tmp/_bazel_patrickb/9c146a5e97098b318f66f519df2b642d/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/device_and_simulator_rule.bzl", line 89, column 29, in _device_and_simulator_impl
merge_xcodeprojinfos([
File "/private/var/tmp/_bazel_patrickb/9c146a5e97098b318f66f519df2b642d/external/com_github_buildbuddy_io_rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 421, column 31, in merge_xcodeprojinfos
info_fields = _skip_target(
File …
```

Fix error when merging `XcodeProjInfo` with `deps_attr`

---

xcodeproj/internal/xcodeproj_macro.bzl

Without the bazelrc files and rules_xcodeproj_generator config set, the generated project would be incorrect anyway.

Prevent `//...` building of project

---

.gitignore
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/cc/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/simple/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
tools/generator/test/Fixtures.swift
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/input_files.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/output_group_map.bzl
xcodeproj/internal/runner.template.sh
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_rule.bzl
xcodeproj/repositories.bzl

Fixes #1029.
We use a `new_local_repository` to ensure this continues to work with `--noexperimental_check_external_repository_files`.

Use an external repository for top_level_cache_buster

---

examples/integration/.bazelrc

`--define=apple.experimental.tree_artifact_outputs=1` is set in `xcodeproj.bazelrc`.

Remove unneeded config setting

---

buildbuddy.yaml

The `Test` workflow also builds everything.

Remove redundant `Build` Workflow

---

README.md

We already include it in the release notes, and this is one less piece of information that can be stale (and look, it was stale right now!).

Remove README WORKSPACE snippet

---

doc/rules-xcodeproj.md
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/xcodeproj_targets.bzl
xcodeproj/internal/xcode_schemes.bzl

Resolves #933.
Now that we have updated xcodeproj to contain https://github.com/tuist/XcodeProj/pull/720 we can set the value of the custom working
directory for LaunchActions

Re-enable `working_directory` for `launch_action`

---

doc/rules-xcodeproj.md
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcodeproj_macro.bzl

These shouldn't have been public API, and are now properly private.

Remove `{un,}focus_schemes` from `xcode_schemes` module

---

doc/rules-xcodeproj.md
xcodeproj/xcodeproj.bzl

Before 1.0 this might still have breaking changes, but it's good to add to the docs now.

Add `XcodeProjInfo` provider to public API

---

test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx_spec.json
tools/generator/xcodeproj_targets.bzl

These now work again (on my machine 😉) with the removal of the Bazel convenience symlinks.

Update `generator` launch arguments

---

xcodeproj/internal/runner.template.sh

While `bazel_build.sh` should still have `--xcode_version`, to ensure that Bazel uses the version of Xcode you are building inside of, setting `--xcode_version` based on `xcode-select` can counter-act some people's use of `--xcode_config`. We leave the `--repo_env` though to at least try to fix https://github.com/bazelbuild/bazel/issues/8902.

Revert runner set `--xcode_version`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/runner.template.sh
xcodeproj/internal/xcodeproj.template.bazelrc
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_rule.bzl
xcodeproj/repositories.bzl

Before this change `bazel query 'deps(...)'` could fail because our `rules_xcodeproj_top_level_cache_buster` wasn't set up properly. Now we have a minimal custom repository rule to ensure that always works. We could modify the file inside of the rule, but that won't get picked up if `--noexperimental_check_external_repository_files` is used, so we use `--override_repository` to work around that.

Use `--override_repository` for `top_level_cache_buster`

---

docs/BUILD.bazel

This makes it so only the `Docs` Workflow fails when there are docs issues.

Make the docs `diff_test` manual

---

xcodeproj/repositories.bzl

This is required to get Bazel-built index-while-building working with `--@build_bazel_rules_swift//swift:universal_tools`.

Update rules_swift to 1.2.0 and rules_apple to 1.1.2

---

README.md
docs/bazel.md
docs/design/custom-xcode-schemes.md
examples/cc/BUILD
examples/integration/AppClip/BUILD
examples/integration/BUILD
examples/integration/WidgetExtension/BUILD
examples/integration/iOSApp/Source/BUILD
examples/integration/tvOSApp/Source/BUILD
examples/integration/watchOSApp/BUILD
examples/integration/watchOSAppExtension/BUILD
examples/integration/xcodeproj_targets.bzl
examples/simple/BUILD
tools/generator/BUILD
tools/generator/xcodeproj_targets.bzl
xcodeproj/BUILD
xcodeproj/defs.bzl
xcodeproj/experimental.bzl
xcodeproj/internal/docs/bazel.header.md
xcodeproj/internal/docs/xcode_schemes.bzl
xcodeproj/xcodeproj.bzl

As recommend by best practices, and followed by more modern rulesets:
- https://bazel.build/rules/deploying#rules
- https://github.com/bazel-contrib/rules-template/blob/main/mylang/defs.bzl
- https://github.com/bazelbuild/rules_jvm_external/blob/00ddb84c67b58d52c89b659cf9fcceea16995a32/defs.bzl
- https://github.com/bazelbuild/rules_python/blob/a364fcac97b7ccadb5c5a703ec8ce2f2ecef0d97/python/defs.bzl
- https://github.com/bazelbuild/rules_java/blob/07691fb9cb85bfa5dd03e3361db9810dbac44c36/java/defs.bzl

Move public rules and macros to `xcodeproj/defs.bzl`

---

examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/SetTargetConfigurations.swift

Fixes #1123.
It appears the default `CODE_SIGNING_ALLOWED` changed in Xcode 14
https://developer.apple.com/forums/thread/708659

Disable codesigning for bundles in BwX

---

BUILD
test/fixtures/generator/BUILD
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
tools/generator/BUILD
tools/generator/xcodeproj_targets.bzl

`./swiftlint` attempts to call globally installed binary but it work only on a specific environment as Xcode runs pre-build script in a limited PATH, so for now removing swiftlint script from xcodeproj of generator.
`//example/simple:xcodeproj` is still available as an example of `xcodeproj-pre_build` usage and for an integration test.

Remove swiftlint from pre-build script

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/CreateProject.swift
tools/generator/test/CreateProjectTests.swift

Some things, such as `LD_RUNPATH_SEARCH_PATHS`, don't support relative paths.

Include `$(PROJECT_DIR)` in `BAZEL_*` build settings

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/clang.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/clang.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/clang.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/clang.sh
xcodeproj/internal/bazel_integration_files/clang.sh

This PR updates the clang stub to handle version argument.
Xcode invokes the stub with the following arguments:
`-v -E -dM -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk -x c -c /dev/null
`
This support is required to implement Thread sanitizer (and other sanitizers) covered in https://github.com/buildbuddy-io/rules_xcodeproj/pull/1127.

Add version handling in the clang stub

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/app.exclude.rsynclist
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
tools/generator/src/Generator/CreateFilesAndGroups.swift
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/xcodeproj.template.bazelrc
xcodeproj/internal/xcodeproj_runner.bzl

Related to the Base PR: https://github.com/buildbuddy-io/rules_xcodeproj/pull/1127
- Adds `/*.app/Frameworks/libclang_rt.tsan*.dylib` to the exclude list. It's a wildcard because clang has different dylib per target os and target architecture. 
- This also requires passing --features=tsan to make it fully work and hence the bazelrc was modified and a new config build:rules_xcodeproj_tsan was added to address this.
What will be covered in the next PR(s)?
- Symlinking of the lib directory. (context: https://github.com/buildbuddy-io/rules_xcodeproj/pull/1127)

Add tsan config

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
examples/simple/test/fixtures/bwb_spec.json
examples/simple/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/Product.swift
tools/generator/src/DTO/Target+LinkerFlags.swift
tools/generator/src/DTO/Target.swift
tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/ProcessTargetMerges.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurationsTests.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/product.bzl

Bazel can refer to binaries of frameworks in one location (pre-bundle) and the finished bundle in another location. We also weren't handling merged targets perfectly, which could have issues for unfocused test hosts (I need to look into this and apply a separate fix after this).

Track when products have more than out bazel output path

---

tools/generator/src/DTO/SearchPaths.swift
tools/generator/src/Generator/ProcessTargetMerges.swift

This is needed to support framework targets (which are top-level).

Keep top-level `frameworkIncludes` when merging

---

tools/generator/src/Generator/SetTargetConfigurations.swift

Places it closer to the other code signing stuff.

Move where we set per-target `CODE_SIGNING_ALLOWED`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
tools/generator/src/Generator/SetTargetConfigurations.swift
xcodeproj/internal/bazel_integration_files/copy_outputs.sh

Xcode adds `$BUILD_DIR` to `DYLD_LIBRARY_PATH` for SwiftUI Previews, to make framework based previews work. We don't have our outputs in a flat hierarchy though, and this doesn't account for external frameworks. Our workaround is to copy all dependent frameworks into `$BUILD_DIR` to make them available. For BwX we will adjust `LD_RUNPATH_SEARCH_PATHS` in a future change.

Copy dependent frameworks for BwB framework SwiftUI Previews

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx_spec.json
xcodeproj/internal/linker_input_files.bzl

This is to match Bazel's behavior: https://github.com/fmeum/bazel/blob/a55ad95a81a3a0129f66ea36276b92e878852613/src/main/java/com/google/devtools/build/lib/rules/objc/ObjcProvider.java#L386-L404
Ideally in the future we wouldn't be calculating this ourselves, because if Bazel changes its behavior, we will get out of sync.

Stop avoiding frameworks

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx_spec.json
examples/sanitizers/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwx_spec.json
examples/simple/test/fixtures/bwb_spec.json
examples/simple/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/Product.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
xcodeproj/internal/product.bzl
xcodeproj/internal/resource_target.bzl

When there were resource bundles this would break. Broke in 74ec1431367e1d8f4c05931ada26429f2ecfbb7f.

Fix BwX SwiftUI Previews output group selection

---

tools/generator/src/DTO/FilePath.swift
tools/generator/src/Generator/SetTargetConfigurations.swift

The search path will now correctly be either `$BUILD_DIR` or `bazel-out/` based. In BwX mode with unfocused targets, the same original path might produce both paths.

Adjust `FRAMEWORK_SEARCH_PATHS` to account for framework targets

---

tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/test/ConsolidateTargetsTest.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/Target+Testing.swift

This is needed for upcoming framework support.

Stop including framework target outputs in `allExcludableFiles`

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/test/ConsolidatedTargetTests.swift

In BwB mode we don't need to list any dynamic frameworks, since we aren't embedding them.

Stop including frameworks in excluded files in BwB mode

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
tools/generator/src/DTO/Inputs.swift
xcodeproj/internal/input_files.bzl

`hdrs` will be used to support framework level headers, which don't use `CcInfo` for their source of truth.

Move `hdrs` into `srcs

---

buildbuddy.yaml

The generator tests can take a bit, and can be done in parallel to the generator project generation validation.

Make Workflows more parallel

---

examples/sanitizers/AddressSanitizerApp/AddressSanitizerApp.swift
examples/sanitizers/AddressSanitizerApp/AddressSanitizerExamples.swift
examples/sanitizers/AddressSanitizerApp/BUILD
examples/sanitizers/AddressSanitizerApp/ContentView.swift
examples/sanitizers/AddressSanitizerApp/Info.plist
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/targets/applebin_ios-ios_x86_64-dbg-ST-9fcfb6a7af56/AddressSanitizerApp/AddressSanitizerApp.link.params
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizerApp.xcscheme
examples/sanitizers/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/targets/applebin_ios-ios_x86_64-dbg-ST-7aac51e4b353/AddressSanitizerApp/AddressSanitizerApp.link.params
examples/sanitizers/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/AddressSanitizerApp.xcscheme
examples/sanitizers/test/fixtures/bwx_spec.json
examples/sanitizers/xcodeproj_targets.bzl

This PR adds the Address Sanitizer Example Application. This was marked as a TODO in this PR (https://github.com/buildbuddy-io/rules_xcodeproj/pull/1155).
The enclosed screenshot demonstrates that asan works as expected in the BwB mode.
TODO:
- There was a suggestion of enhancing the custom scheme support with the `diagnostics` option. This will be added in a separate PR.

Add Address Sanitizer Example Application

---

xcodeproj/internal/xcodeprojinfo.bzl

We already pass `is_top_level_target = True`, so the value is never looked at. This fixes `merge_xcodeprojinfos`.

Stop requiring `rules_kind` with `_skip_target`

---

xcodeproj/internal/opts.bzl

This reverts commit 05a797078fe81af491496dcc4b7f305fc2d4b9d5. This change was causing issues with indexing. I don't have time to determine why, and having this appear twice in the build command is NBD.

Revert "Ignore `-enable-bare-slash-regex` (#1073)"

---

xcodeproj/internal/opts.bzl

This reverts commit cde3617d67fceb718cc585c01b8cb673a1b9b202.
Turns out the real issue was #1173.

Revert "Revert "Ignore `-enable-bare-slash-regex` (#1073)" (#1172)"

---

tools/generator/src/Generator/SetTargetConfigurations.swift

727681df4f91e2e2f38c35f78cea9f6f001430e3 didn't account for the fact that `swift_binary` targets don't produce their own `.swiftmodule`.

Fix `swift_binary`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/libtool.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/libtool.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/libtool.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/libtool.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/libtool.sh
xcodeproj/internal/bazel_integration_files/libtool.sh

Apparently "\0 \0" is valid dependency file contents. This reduces some
extra invocations since we're not using this file right now.

Reduce unneeded invocations in libtool stub

---

xcodeproj/internal/xcodeproj_rule.bzl

Previously it wouldn't detect the situation of only listing unfocused labels.

Fix `force_bazel_dependencies` logic

---

tools/generator/src/DTO/Outputs.swift

Allow `swift.module.swiftsourceinfo` to be `None`

---

examples/cc/.bazelversion
examples/integration/.bazelversion
examples/sanitizers/.bazelversion
examples/simple/.bazelversion

This makes it easier to update the targeted Bazel version.

Change example `.bazelversion`s to symlinks

---

tools/generator/src/Extensions/PBXProductType+Extensions.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

This gives us a better icon in Xcode.

Use `productType: .framework` for `.staticFramework`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/installer.template.sh
xcodeproj/internal/runner.template.sh
xcodeproj/internal/xcodeproj_rule.bzl

This is to ensure the generator run and the in-Xcode build are as similar as possible.

Apply the same `env -i` command in the runner

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/output_files.bzl

This ensures that generated source files are downloaded when buiding
with "Builds without the Bytes".

Add a new output group for generated source files

---

tools/swiftc_stub/main.swift

We need to parse the JSON in order to determine the exact paths to dependency files, since Xcode adds a hash to the end of partials.
Also apply some code cleanup.

Fix swiftc stub for incremental compilation

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/import_indexstores.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/bazel_integration_files/import_indexstores.sh
xcodeproj/internal/xcodeproj.template.bazelrc

Fixes #1126.
This matches Xcode's behavior, allowing indexing to be accelerated by SwiftUI Preview builds.

Import SwiftUI Preview built indexstores

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/test/DisambiguateTargetsTests.swift

The idea about keeping them around was that we would use them for copying diagnostics and then modifying a file to force a "recompile". There are other ways to achieve that though, so these scripts are just plain overhead right now.

Remove `Copy Bazel Outputs` scripts from non-product targets

---

tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/SetTargetConfigurations.swift

In the future this flag can apply to more than just project paths.

Rename `forceAbsoluteProjectPath` to `forceFullBuildSettingPath`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/SetTargetConfigurations.swift

This just caused symlinks for root level files to be used instead of the root level files themselves.

Remove `"."` header search path adjustment

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh

It's already set in `xcodeproj.template.bazelrc`.

Remove unneeded `--experimental_convenience_symlinks=ignore`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh

We no longer parse the output log, so we don't care how the output is formatted (i.e. 6cf9028a82492ceaca7d83111ff52e1ff8081aef).

Remove unneeded `--symlink_prefix=/`

---

xcodeproj/internal/BUILD
xcodeproj/internal/xcodeproj_rule.bzl

This was left over from a very old way of doing fixtures.

Remove unused `//xcodeproj/internal:install_path`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/installer.template.sh
xcodeproj/internal/runner.template.sh

This helps work around when the Bazel server caches `DEVELOPER_DIR` in a different directory, like `~/Downloads`.

Add `$DEVELOPER_DIR` to `USE_CLANG_CL` key

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/installer.template.sh
xcodeproj/internal/runner.template.sh

This works around the fact that Bazel caches paths for each Xcode version, meaning a rename of Xcode will result in build failures: https://github.com/bazelbuild/bazel/blob/40dc549ec449b61831a59cfacbcaa8dfa65343e6/src/main/java/com/google/devtools/build/lib/exec/local/XcodeLocalEnvProvider.java#L54

Restart Bazel server if `$DEVELOPER_DIR` changes

---

examples/cc/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
examples/simple/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/SwiftBin.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
tools/generator/src/Extensions/XCSchemeEnvironmentVariables+Extensions.swift

We could set `$BUILD_WORKSPACE_DIRECTORY` to something other than `$SRCROOT`, so this is more correct.

Use `$(BUILD_WORKSPACE_DIRECTORY)` in schemes

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddTargets.swift

This reverts commit 5f8c7df80a07970289ac9a7fd638ab37c2363e27.
The change broke "Off-by-one Index Build". We will have to figure out how to do this while still preserving that functionality.

Revert "Remove `Copy Bazel Outputs` scripts from non-product targets (#1238)"

---

xcodeproj/internal/xcodeproj_rule.bzl

It really should be `host`, but I guess that is finally going away soon.

Change `host` config back to `exec`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/installer.template.sh
xcodeproj/internal/runner.template.sh

This way it's still cleaned with `bazel clean`, but there is no chance of recursive symlinks.
The name has an underscore, so it shouldn't conflict with another external repo when using `--experimental_sibling_repository_layout`.

Move nested output base down into `execroot`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/CreateProject.swift
tools/generator/test/CreateProjectTests.swift

When copying over frameworks for SwiftUI Previews, if a framework is used by both a watchOS app and the iOS app (highly likely) they would both try to copy to the same location. This can result in runtime errors as the wrong version might be copied last. Since we don't copy Bazel generated files anymore, this is safe to do: all of the files generated by Xcode will be in the same configuration, or Xcode will know to use the other configuration (such as when bundling a watchOS app).

Apply normal configuration segregation to `BUILD_DIR`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
xcodeproj/internal/bazel_integration_files/BUILD
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

This is in preparation of extracting the core part of the script to another script, called `bazel_build.sh`, which will be used by a new script `generate_index_build_bazel_dependencies.sh`.
Also moved the `cd` into the script.

Rename `bazel_build.sh` to `generate_bazel_dependencies.sh`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
xcodeproj/internal/bazel_integration_files/BUILD
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

This extracts the core `bazel build` invocation logic from `generate_bazel_dependencies.sh`, which will allow it to be reused in a future `generate_index_build_bazel_dependencies.sh`.

Extract `bazel_build.sh`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh

If they ever have inclosed whitespace, this different expansion is needed. We also want them set before `--config`, to allow that to override them.

Adjust expansion of `build_pre_config_flags`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

Even when we add `generate_index_build_bazel_dependencies.sh`, we will share some of this logic.

Move `output_base` calculation into `bazel_build.sh`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/runner.template.sh

While people should filter env variables to make their builds as hermetic as possible, they can do it themselves in `tools/bazel` or `bazelw`. All that we really need to do is set a standard `PATH`, to ensure hits between the runner invoked build and the Xcode invoked build.

Remove env variable filtering

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/CreateProject.swift
tools/generator/test/CreateProjectTests.swift

`$(BAZEL_EXTERNAL)` needs to reference the the path that the Project navigator references, which is the non-symlink version.
Also only use set `_SRCROOT` if we need to use `standardizepath`.

Reference the correct directory with `BAZEL_EXTERNAL`

---

examples/cc/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
examples/simple/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/SwiftBin.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
tools/generator/src/Extensions/XCScheme+Extensions.swift

If after project generation `bazel clean` is performed, minimally removing the execution root, Xcode would fail to `cd` into `$PROJECT_DIR`. So we now create that directory ahead of time in the pre-build scheme script.

Ensure `$PROJECT_DIR` exists for `BazelDependencies`

---

xcodeproj/internal/output_files.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Before this change, when building an App, only the App's various versions of Info.plist would be generated. The original intent was that all versions of every transitive dependency would be generated.

Include all transitive Info.plist

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

Regressed with 5aec77f2831a70164406d461811bedab7a46e6aa.
This is needed, otherwise you can get a build error like this:
> error: Build input file cannot be found: '/Users/brentley/Developer/rules_xcodeproj/examples/integration/bazel-output-base/execroot/_rules_xcodeproj/build_output_base/execroot/\_\_main\_\_/iOSApp/Source/CoreUtilsObjC/CoreUtils/CoreUtils.pch'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'FrameworkCoreUtilsObjC' from project 'Integration')

Use full build setting path for XCBuild tracked files

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
shared.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/xcodeproj.template.bazelrc

Also stop setting `run:rules_xcodeproj_generator --remote_download_outputs=all`. This leads to warnings if people set BwtB settings themselves. They will just have to work around https://github.com/bazelbuild/bazel/issues/11920 on their own. This also allows us to immediately benefit if that is eventually fixed.

Use `--remote_download_outputs=toplevel` for projects

---

examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
examples/sanitizers/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/Generator/CreateFilesAndGroups.swift
xcodeproj/internal/top_level_targets.bzl

Part of #237.
We already add it to the `xl` and `bp` output groups. This prevents us from generating the Info.plist during Index Build. This also makes the BEP smaller as it doesn't reference the Info.plist twice.

Stop adding adjusted Info.plist to `generated`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh

Example (notice the pattern in the header doesn't say `//tools/generator:xcodeproj.generator`): https://app.buildbuddy.io/invocation/94d67a3c-eb20-4894-9eb3-ea3895e083db
Re-implements #1131.

Set pattern override for BuildBuddy

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwx_spec.json
xcodeproj/internal/top_level_targets.bzl

Similar to an App Clip, a watchOS app does not need to build the hosting app. This makes a future BwB optimization easier.

Unset iOS app as watchOS app host target

---

tools/generator/src/Generator/CreateProject.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/src/Generator/Main.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/fixtures.bzl
xcodeproj/internal/xcodeproj_rule.bzl

There are some things that we want to do differently when we generate a fixture based project. Mainly it's making paths relative, but in the future we might want to do more.

Inform the generator that it's creating a fixture

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/CreateProject.swift

This is needed to support conditional `PROJECT_DIR` values. `SRCROOT` can't be relative to `PROJECT_DIR` in that case.

Only set relative `projectDirPath` for fixtures

---

docs/bazel.md
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppUnitTests_Scheme.xcscheme
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/iOSAppUnitTests_Scheme.xcscheme
examples/integration/test/fixtures/bwx_spec.json
examples/integration/xcodeproj_targets.bzl
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/internal/xcode_schemes/model_tests.bzl
tools/generator/src/DTO/XcodeScheme.swift
tools/generator/src/Extensions/XCScheme+Extensions.swift
tools/generator/src/Extensions/XcodeScheme+Extensions.swift
tools/generator/src/Generator/XCSchemeInfo+TestActionInfo.swift
tools/generator/test/XCScheme+ExtensionsTests.swift
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcode_schemes_internal.bzl

Adds pre_post_action attributes to `test_action` for custom actions run on the test scheme.

Add pre_post_actions to TestActions

---

xcodeproj/internal/compilation_providers.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/lldb_contexts.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/platform.bzl
xcodeproj/internal/target_search_paths.bzl
xcodeproj/internal/xcode_targets.bzl

When using `--starlark_cpu_profile`/`pprof` same named functions, even internal ones, are seen as the same function. By giving them unique names it makes the statistics easier to read.

Rename internal Starlark functions for easier profiling

---

docs/bazel.md
xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/xcodeproj_aspect.bzl

This removes lots of `dir(ctx.rule.attr)` calls. I added a TODO to do even better in the future.

Slightly optimize `_transitive_infos`

---

xcodeproj/internal/installer.template.sh
xcodeproj/internal/runner.template.sh

We don't need to call `bazel info` in the installer script, since we already call it in the runner. Instead we can just pass the info from the runner to the installer.

Remove a `bazel info` call

---

xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

We have the output path in `$BAZEL_OUT` and the execution root in `$PROJECT_DIR`.

Remove `bazel info` call from within Xcode

---

tools/generator/src/FilePathResolver.swift
tools/generator/test/GeneratorTests.swift

Fixes #1359.
Regressed with 5febe757f6c771e32b82bf640f3db5b2f65d34ab.
We were hashing `FilePathResolver` as part of `MemoizationKey`, to ensure that if there were multiple versions of `FilePathResolver` then the values wouldn't conflict. That itself isn't much of an issue, except in BwX mode that would include a large `xcodeGeneratedFiles` dictionary. Changing `FilePathResolver` to a class and embedding the memoization into the instance side-steps this issue. In the future `FilePathResolver` will be in Starlark, removing all of this anyway...

Fix horrible BwX `FilePathResolver` performance

---

tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/GeneratorTests.swift

Regressed with 5aec77f2831a70164406d461811bedab7a46e6aa.
`.srcRoot` now means Bazel's execution root. So just like `mainGroup`, we need this to be an absolute path all the time now.

Fix `local_repository` regression

---

xcodeproj/internal/bazel_integration_files/copy_outputs.sh

Xcode messes with these, so reduce the churn.

Exclude `*.framework/Module` from rsync

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/bazel_integration_files/copy_outputs.sh
xcodeproj/internal/xcodeproj.template.bazelrc

When multiple frameworks try to symlink their dependency frameworks into `$BUILD_DIR`, `ln` can error out. To work around this we add `@loader_path/SwiftUIPreviewsFrameworks` to the `@rpath` when building for previews, and then create the symlinks at `$TARGET_BUILD_DIR/$WRAPPER_NAME/SwiftUIPreviewsFrameworks`.

Fix BwB SwiftUI Previews framework symlink error

---

xcodeproj/internal/xcodeproj_rule.bzl

Only break open the `depset` once. We store it as a dictionary for a future change that needs it that way.

Optimize `transitive_dependency` usage

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/runner.template.sh
xcodeproj/internal/xcodeproj.template.bazelrc

Also fix use of `--` in the bazel command (e.g. `bazel run --config=cache //:xcodeproj -- --generator_output_groups=all_targets 'build --show_result=1 --'` now works).

Allow overriding `--show_result` in command-line API

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/watchOSAppExtension/watchOSApp.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/SetTargetDependencies.swift
xcodeproj/internal/bazel_integration_files/BUILD

watchOS 2 app extensions need to be embedded in the app bundle for Previews to work.

Fix watchOS 2 app SwiftUI Previews

---

xcodeproj/internal/bazel_integration_files/bazel_build.sh

This ensures that indexing will use the correct version of external files as well as generated files.

Add entry for external files to `bazel-out-overlay.yaml` as well

---

xcodeproj/internal/library_targets.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

This removes another use of the `//xcodeproj/internal:build_mode` build setting.

Move "should include outputs in DTO" decision up to the `xcodeproj` rule

---

xcodeproj/internal/library_targets.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

This removes another use of the `//xcodeproj/internal:build_mode` build setting.

Move "should include BwB output groups" decision up to the `xcodeproj` rule

---

examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj_aspect.bzl
xcodeproj/internal/xcodeprojinfo.bzl

For targets that will always be private dependencies, and thus will be culled out later, we can detect some of them and don less work.

Short-circuit some `XcodeProjInfo` creation

---

xcodeproj/internal/fixtures.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/xcodeproj_aspect.bzl
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_rule.bzl

We get around this by creating two versions of the aspect, and two versions of `xcodeproj` rules (two use the different versions of the aspect). I'm choosing to do it this way , because some things are much more optimal being done at the aspect level instead of at the final rule level (e.g. unfocused Xcode targets require additional work in BwX mode that we don't do in BwB mode).

Remove `xcodeproj_aspect` dependency on `//xcodeproj/internal:build_mode`

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
examples/sanitizers/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwx_spec.json
examples/simple/test/fixtures/bwb_spec.json
examples/simple/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/Outputs.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/xcode_targets.bzl

Made redundant with 0ad6162d7c97e218d07c4892b864ceaaff150e5a.

Remove redundant product output path in spec.json

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
examples/sanitizers/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwx_spec.json
examples/simple/test/fixtures/bwb_spec.json
examples/simple/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/Project.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurationsTests.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

For now this makes the spec.json larger, but that can get reduced in the future by making `copy_outputs.sh` generated by Bazel with the paths directly embedded into it, on demand as part of the `bp` output group.

Set `PREVIEW_FRAMEWORK_PATHS` in Starlark

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_spec.json
xcodeproj/internal/xcode_targets.bzl

When `absolute_path = False` and `use_build_dir = False`, there is no need to sue the function (expect for header search paths, to get the `.` -> `$(PROJECT_DIR)` behavior).

Optimize away some `build_setting_path` usage

---

xcodeproj/internal/files.bzl

The Bazel execution root has symlinks for project files.

Respect `absolute_path` for project files as well

---

tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/AddTargetsTests.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurationsTests.swift

It's only static functions now. A followup change will change it to a namespace (decoupling the instance properties).

Simplify `FilePathResolver` more

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
shared.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/opts.bzl
xcodeproj/internal/xcodeproj.template.bazelrc

I personally believe this should be enabled by default in rules_swift, but until then we can do it.
Also ignore `-module-cache-path` in copts.

Set `--features=swift.use_global_module_cache`

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
examples/integration/test/fixtures/bwx_spec.json
xcodeproj/internal/linker_input_files.bzl

We don't need these in the generated project. They are either intermediate files, or we collect them another way.

Remove additional linker inputs processing 

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/test/Fixtures.swift

I don't know why, but the module in lldb can sometimes not be set. Regardless, we can just not try to set settings if that is the case.

Fix lldb error when `module` is `None`

---

xcodeproj/repositories.bzl

This speeds up `spec.json` parsing by ~19%.

Upgrade ZippyJSON to 1.2.10

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/xcodeproj.template.bazelrc

This will normally half the number of paths output in the BEP.

Remove `important_outputs` from BEP

---

xcodeproj/internal/bazel_integration_files/bazel_build.sh

For builds with lots of outputs, they may have hundreds of `namedSetsOfFiles` events. This can take a couple seconds to send to a BES service. We shouldn't hold up the build to send these events.

Make BES upload async inside of Xcode

---

examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddBazelDependenciesTarget.swift

This is already the case for the Bazel build script and removes the warning that Xcode throws due to the fact that inputs and outputs are not defined.

Set pre and post scripts to always be out of date by default

---

xcodeproj/internal/bazel_integration_files/copy_outputs.sh

Fixes #1476.
For now we do a simple `find` + `touch`. We could pass the exact paths, since we know them at analysis, but I'm saving that for a future improvement.

Fix delta update of iOS 16+ apps with extensions

---

README.md

With a link to the blog post that mentions it.

Add Mercari as a rules_xcodeproj user

---

test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb_project_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx_project_spec.json
tools/generator/xcodeproj_targets.bzl

They now account for the new way that specs are passed, and default to `opt` to make it easier when adjusting for profiling.

Adjust generator launch arguments

---

test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
tools/generator/src/DTO/XcodeScheme.swift
tools/generator/src/Extensions/XCScheme+Extensions.swift
tools/generator/src/Generator/XCSchemeInfo+ProfileActionInfo.swift

This way profiling works runs the same as launching, which is expected until we support custom `profile_action`s.

Default Profile action's `customWorkingDirectory` based on Launch action

---

xcodeproj/internal/xcodeproj_rule.bzl

It's a slight performance win to not sort.

Stop sorting targets when not generating fixtures

---

examples/cc/test/fixtures/bwb_targets_spec.json
examples/cc/test/fixtures/bwx_targets_spec.json
examples/integration/test/fixtures/bwb_targets_spec.json
examples/integration/test/fixtures/bwx_targets_spec.json
examples/sanitizers/test/fixtures/bwb_targets_spec.json
examples/sanitizers/test/fixtures/bwx_targets_spec.json
examples/simple/test/fixtures/bwb_targets_spec.json
examples/simple/test/fixtures/bwx_targets_spec.json
test/fixtures/generator/bwb_targets_spec.json
test/fixtures/generator/bwx_targets_spec.json
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Soon we will generate the `link.params` file on the fly, and the linkopts won't be in the spec at all. Until then though, we need to remove these from the spec to allow for Bazel 5 and 6 to generate the same fixtures.

Stop writing linkopts for fixtures

---

xcodeproj/internal/fixtures.bzl
xcodeproj/internal/runner.template.sh
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_runner.bzl

This is to make the difference between Bazel 5 and 6 less noisy.

Set `--incompatible_unambiguous_label_stringification=false` for fixtures

---

xcodeproj/internal/xcode_targets.bzl

This is needed while we still compare Bazel 5 and 6 fixtures.

Filter Bazel 6 `BAZEL_CURRENT_REPOSITORY` local define for fixtures

---

buildbuddy.yaml

This makes each of the actions more clear on what they are accomplishing. It also allows for a smaller change when adding multiple Bazel versions to the mix.

Use YAML anchors in `buildbuddy.yaml`

---

buildbuddy.yaml

Ideally not specifying the `arch` would use both archs, but until then, we manually set a few of the actions to run on arm64 instead of x86_64.

Run some Workflow actions on arm64 machines

---

examples/integration/CommandLine/CommandLineToolLib/BUILD
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_targets_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx_targets_spec.json
tools/generator/src/FilePathResolver.swift
xcodeproj/internal/files.bzl

For example, if a header search path was set like this `-Ibazel-out`, we would incorrectly detect that as rooted in `$SRCROOT`.

Fix path references to `bazel-out` and `external` directories

---

xcodeproj/internal/bazel_integration_files/create_lldbinit.sh
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

In the future this will be called from more locations, so  it's best if the logic is fully consolidated.

Move all `.lldbinit` logic into `create_lldbinit.sh`

---

examples/cc/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UniversalCommandLineTool (arm64).xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UniversalCommandLineTool (x86_64).xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
tools/generator/src/Extensions/XCScheme+Extensions.swift
tools/generator/test/XCScheme+ExtensionsTests.swift
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

This will allow the script to customize based on the target being launched. It also ensures that the file is up to date on every launch, regardless if a build happened.

Create `bazel.lldbinit` in launch pre-action

---

examples/cc/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/UniversalCommandLineTool (arm64).xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/UniversalCommandLineTool (x86_64).xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTests.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
examples/sanitizers/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
tools/generator/src/Extensions/XCScheme+Extensions.swift

I keep forgetting that BwX mode needs `.lldbinit` for unfocused targets.

Fix BwX `.lldbinit` creation

---

examples/cc/test/fixtures/bwb_project_spec.json
examples/cc/test/fixtures/bwb_targets_spec.json
examples/cc/test/fixtures/bwx_project_spec.json
examples/cc/test/fixtures/bwx_targets_spec.json
examples/integration/test/fixtures/bwb_project_spec.json
examples/integration/test/fixtures/bwb_targets_spec.json
examples/integration/test/fixtures/bwx_project_spec.json
examples/integration/test/fixtures/bwx_targets_spec.json
xcodeproj/internal/input_files.bzl

We don't use them as sources in the generator. We still want them in the project navigator for easy editing though, so we are adding them to `extra_files` instead.

Stop including `CcInfo` headers in `srcs`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwb_targets_spec.json
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx_targets_spec.json
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_targets_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx_targets_spec.json
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb_targets_spec.json
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx_targets_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_targets_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_targets_spec.json
test/internal/opts/process_compiler_opts_tests.bzl
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/opts.bzl

On the linking side, we should just let whatever is set in `link.params` come through. On the compiling side, we will move the flags into `OTHER_CFLAGS` and eventually it will be in `compile.params`.

Remove special handling for C++ standard library

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
examples/integration/test/fixtures/bwb_project_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
examples/integration/test/fixtures/bwx_project_spec.json
xcodeproj/internal/input_files.bzl

This makes the headers maps from https://github.com/line/rules_apple_line work with BwX mode.

Pick up additional `CcInfo` headers in BwX mode

---

tools/BUILD
tools/params_processors/BUILD
tools/params_processors/link_params_processor.py
tools/xccurrentversions_parser/xccurrentversions_parser.py
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

This allows passing through static library arguments, without having to calculate them ourselves.

Migrate linkopt processing to execution phase

---

xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/xcode_targets.bzl

Since we no longer create the arguments ourselves, this is a step towards removing all tracking of static libraries.

Remove some distinction of force_load static libraries
