- xcodeproj/internal/xcode_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
This is just extra data we don't need to store, and it's also an incorrect mapping (executable -> framework). In the future we will map executable -> executable, so we want the mappings to be correct.
> Remove framework executable name from `xcode_generated_paths`

- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/opts.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeproj_aspect.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
Part of #715.
There is no real way to handle a VFS overlay in BwX mode, as the paths in it will all be Bazel execution root related.
> Error in BwX mode if using VFS overlays

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb_targets_spec.json
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
- xcodeproj/internal/xcode_targets.bzl
Part of #715.
This also fixes Swift `defines` from accidentally being set on the PCMs for the `swift_library` that set it.
> Stop filtering `-Xcc` flags

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- tools/params_processors/link_params_processor.py
- xcodeproj/internal/xcode_targets.bzl
With this we stop setting `FRAMEWORK_SEARCH_PATHS` and set `PREVIEWS_LD_RUNPATH_SEARCH_PATHS__YES` to the values instead.
> Set framework search paths via compile and link flags

- xcodeproj/repositories.bzl
Split up the `rules_swift` bump from https://github.com/buildbuddy-io/rules_xcodeproj/pull/1502.
> Bump rules_swift to 1.5.1

- tools/params_processors/link_params_processor.py
This will result in slight duplication, but since these files are generated on the fly, that is fine, and it lowers the chance of filtering something incorrect.
> Remove `link.params` `-L__BAZEL_XCODE_` filter

- MODULE.bazel
- examples/cc/MODULE.bazel
- examples/cc/external/MODULE.bazel
- xcodeproj/extensions.bzl
- xcodeproj/repositories.bzl
This PR adds initial support for bzlmod. I still have to test it with an example project, but the basic infrastructure should be ready.
bzlmod is only really ready to be used starting in Bazel 6.0. For this reason, the `MODULE.bazel` depends on rules_apple 2.0.0, which is also the release that requires Bazel 6. I will need to first check the newest version of rules_apple and rules_swift into the Bazel Central Registry, and then we can proceed testing the rules_xcodeproj integration.
> Add support for bzlmod

- xcodeproj/internal/opts.bzl
This tries to limit the filtering to allow other use copts to go through. We could remove the filtering altogether, but since these are set in the spec.json and the project.pbxproj, it can bloat projects with hundreds or thousands of targets.
> Be more specific with system framework search path filtering

- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
We were correctly detecting these in the Swift `-Xcc` case, but not the normal C/C++ case.
> Add support for additional include flag forms

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwb_targets_spec.json
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx_targets_spec.json
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- xcodeproj/internal/opts.bzl
- xcodeproj/internal/xcode_targets.bzl
Added benefit is that Swift targets now correctly no longer have header search paths set.
> Use `CcInfo.compilation_context` to get proper header search paths

- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
- xcodeproj/internal/xcode_targets.bzl
`has_includes` no longer overshoots for source-less targets (top-level targets that just link targets together).
> Parse compiler flags to determine `framework_includes`

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- tools/generator/src/Generator/AddBazelDependenciesTarget.swift
- tools/generator/src/Generator/Environment.swift
- tools/generator/src/Generator/Generator.swift
- tools/generator/src/Generator/SetAdditionalProjectConfiguration.swift
- tools/generator/test/GeneratorTests.swift
Fixes a regression introduced with 6934ecaf002828ab2487a079b5b8017a7046dc3b.
> Move `RESOLVED_EXTERNAL_REPOSITORIES` from `BazelDependencies` to project

- xcodeproj/internal/bazel_integration_files/create_lldbinit.sh
For a while now `$BAZEL_OUT` and `$build_bazel_out` have been the same thing, since we no longer support relative project paths outside of fixtures.
> Remove unnecessary extra `./bazel-out` `target.source-map` entry

- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
- xcodeproj/internal/xcode_targets.bzl
This reverts commit 0433881b9014309023a9b97cf82ca0af1ab95156.
We weren't picking up all of the framework paths, causing `link.parms` to be incorrect.
> Revert "Parse compiler flags to determine `framework_includes` (#1584)"

- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
- xcodeproj/internal/xcode_targets.bzl
This reverts commit 788fa50135dc8d822347fab9e9b767cdf6788a1d.
We now add the remaining paths in `framework_search_paths` to `ordered_framework_search_paths`, to account for paths that are link-only.
> Revert "Revert "Parse compiler flags to determine `framework_includes` (#1584)" (#1591)"

- examples/cc/test/fixtures/bwb_project_spec.json
- examples/cc/test/fixtures/bwx_project_spec.json
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwx_project_spec.json
- examples/sanitizers/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwx_project_spec.json
- test/fixtures/generator/bwb_project_spec.json
- test/fixtures/generator/bwx_project_spec.json
- test/internal/bazel_labels/normalize_tests.bzl
- xcodeproj/internal/bazel_integration_files/bazel_build.sh
- xcodeproj/internal/bazel_labels.bzl
Fixes #1598.
Tested:
- Bazel 5.4
- Bazel 6.0 with `--noincompatible_unambiguous_label_stringification`
- Bazel 6.0 with `--noincompatible_unambiguous_label_stringification`
- Bazel 6.0 with `--enable_bzlmod`
> Fix label and path handling when bzlmod is enabled

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwb_targets_spec.json
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx_targets_spec.json
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb_targets_spec.json
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- xcodeproj/internal/xcode_targets.bzl
They only need to be absolute for BwX Swift targets.
> Stop making header search paths absolute

- xcodeproj/internal/bazel_labels.bzl
Part of #1598.
Removes the need for the Bazel 6 check. Also will work better once Bazel allows caller-relative label creation.
> Refactor `bazel_labels.normalize()`

- .bcr/config.yml
- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
This PR adds the configuration files and templates necessary to get the [Publish To BCR](https://github.com/bazel-contrib/publish-to-bcr) GitHub app to work with rules_xcodeproj.
There are few steps to make sure this works correctly:
> Add BCR app config

- MODULE.bazel
- WORKSPACE
- bazel_6.bazelrc
- buildbuddy.yaml
- docs/update_docs.sh
- examples/integration/.bazelrc
- examples/sanitizers/.bazelrc
- shared.bazelrc
- tools/bazel
- xcodeproj/extensions.bzl
- xcodeproj/internal/runner.template.sh
- xcodeproj/repositories.bzl
Since bzlmod is the future, we should default to it where possible. CI for now will have explicit bzlmod based tests until everything is working with bzlmod.
> Enable bzlmod for development

- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/integration/test/fixtures/bwb_targets_spec.json
- xcodeproj/internal/lldb_contexts.bzl
This removes extraneous search paths from being included.
> Use parsed framework search paths for `lldb_context`

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/top_level_targets.bzl
Prevents retaining the actual `xcode_target`s.
> Refactor `get_xcode_library_targets`

- examples/integration/iOSApp/Test/ObjCUnitTests/BUILD
- examples/integration/iOSApp/Test/ObjCUnitTests/ObjCUnitTests.m
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
This proves that the VFS overlay works with `-I` in addition to `-iquote`.
> Adjust example to rely on `-I` to find Swift generated header

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- tools/generator/src/Generator/CreateProject.swift
- tools/generator/test/CreateProjectTests.swift
- xcodeproj/internal/xcodeproj_rule.bzl
For some reason VFS overlays don't resolve symlinks correctly, so they need to have the fully resolved versions in them.
> Fix xcode-overlay.yaml handling of `/private/var` paths

- xcodeproj/internal/linker_input_files.bzl
- xcodeproj/internal/xcode_targets.bzl
This is some refactoring as work towards removing `linker_inputs` in the future.
> Reduce scope of `linker_inputs`

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/linker_input_files.bzl
This makes it clear that they are used outside of the module.
> Rename public `compilation_providers` attributes

- examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- tools/generator/src/DTO/Platform.swift
- tools/generator/src/Generator/CreateFilesAndGroups.swift
- tools/generator/test/Fixtures.swift
lldb reports the target triple for the UI test runner, instead of the tests, which can result in mismatches on the os version portion of the triple. The main purpose of using the triple was to get the os and arch matching, so I've removed the os version from our matching logic.
> Fix BwB UI Test Swift debugging

- examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
- tools/generator/src/Generator/CreateFilesAndGroups.swift
- tools/generator/test/Fixtures.swift
```
error: module importing failed: Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Applications/Xcode_14.2.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 169, in reload
_bootstrap._exec(spec, module)
File "<frozen importlib._bootstrap>", line 613, in _exec
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/Users/matt.robinson/Library/Developer/Xcode/DerivedData/Test-UI-Test-Target-glkvogdjirfkwghjfkgtlxpygokw/Build/Intermediates.noindex/swift_debug_settings.py", line 16, in <module>
_TRIPLE_MATCH = re.compile(r"([^-]+-[^-]+)(-\D+)[^-]*(-.*)?")
NameError: name 're' is not defined
```
> Fix missing `import re` in `swift_debug_settings.py`

- buildbuddy.yaml
- tools/set_bazel_5.sh
Also settings missed `normal_resources`.
> Set `USE_BAZEL_VERSION` for Bazel 5 Workflows

- MODULE.bazel
- WORKSPACE
- xcodeproj/repositories.bzl
Until I can figure out a way to not have the `load("@rules_pkg//` in build files causing loading errors like this:
> ERROR: Skipping '@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:extra_common_flags': error loading package '@rules_xcodeproj\~override//xcodeproj': Unable to find package for @[unknown repo 'rules_pkg' requested from @rules_xcodeproj\~override]//:mappings.bzl: The repository '@[unknown repo 'rules_pkg' requested from @rules_xcodeproj\~override]' could not be resolved: No repository visible as '@rules_pkg' from repository '@rules_xcodeproj\~override'.
> Make `rules_pkg` a non-dev dependency for now

- examples/cc/test/fixtures/bwb_targets_spec.json
- examples/cc/test/fixtures/bwx_targets_spec.json
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx_targets_spec.json
- examples/sanitizers/test/fixtures/bwb_targets_spec.json
- examples/sanitizers/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/platform/platform_info_to_dto_tests.bzl
- tools/generator/src/DTO/Inputs.swift
- tools/generator/src/DTO/LinkerInputs.swift
- tools/generator/src/DTO/Platform.swift
- tools/generator/src/DTO/Product.swift
- tools/generator/src/DTO/Target.swift
- xcodeproj/internal/platform.bzl
- xcodeproj/internal/xcode_targets.bzl
Part of #237.
Also don't set some optional properties in json.
This is to reduce the size of `targets_spec.json` to increase generation speed.
> Use single letter json keys in `targets_spec.json`

- examples/cc/test/fixtures/bwb_project_spec.json
- examples/cc/test/fixtures/bwx_project_spec.json
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwx_project_spec.json
- examples/sanitizers/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwx_project_spec.json
- test/fixtures/generator/bwb_project_spec.json
- test/fixtures/generator/bwx_project_spec.json
- tools/generator/src/DTO/Project.swift
- xcodeproj/internal/xcodeproj_rule.bzl
Part of #237.
Also, we now use `json.encode` instead of string formatting, hopefully being more memory efficient.
> Stop sending defaults in `project_spec.json`

- buildbuddy.yaml
We don't need _every_ test to run in _every_ combination. The `examples/integration` is good enough for the examples, and we want the Starlarks tests to run there as well.
> Remove a couple Bazel 6 Workflows

- xcodeproj/internal/xcodeprojinfo.bzl
Was incorrectly using `should_bundle_resources` as a way of checking the build mode.
> Change `bazel_build_mode_error` check

- xcodeproj/internal/bazel_integration_files/calculate_output_groups.py
- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
If building a resource bundle, currently it won't have any output groups set (eventually it probably should have generated inputs?). This causes the "Couldn't determine labels and target ids from PIFCache" path to incorrectly get hit. Now we just exit the `Bazel Build` early.
> Allow not having output groups set

- tools/generator/src/Generator/AddTargets.swift
- tools/generator/src/Generator/ConsolidateTargets.swift
Currently resource bundles don't generate any files (though they should if they depend on generated files). Until they do, we don't need to have an extra build phase.
> Stop creating a `BazelDependencies` script for resource bundles

- docs/bazel.md
- xcodeproj/internal/providers.bzl
Since we are going to be releasing 1.0 soon, we need to be clear that these APIs aren't stable yet.
> Add unstable API warning to public providers

- xcodeproj/internal/runner.template.sh
- xcodeproj/internal/xcodeproj_runner.bzl
We use the version that Bazel is using, either that it sets by default, or you've set explicitly.
> Set `--xcode_version` in runner

- README.md
Resolves #561.
This is similar to what rules_apple does. If we drop support for certain Bazel, macOS, rules_*, or Xcode versions, we can add a new row to this table.
> Update compatibility table to anticipate multiple ranges

- xcodeproj/internal/xcodeproj_rule.bzl
It used to be the case that only swiftmodule search paths were an issue, but linker output paths matter as well, which non-Swift targets have.
I think there is a way to lift this restriction in the future, with further removal of `xcodeGeneratedPaths` from `generator`, but for now this fixes certain project generations.
> Restrict target merging for non-Swift targets as well

- xcodeproj/internal/bazel_integration_files/create_lldbinit.sh
If `~/.lldbinit-Xcode` exists, it will be used instead of `~/.lldbinit`.
> Account for `~/.lldbinit-Xcode` in `create_lldbinit.sh`

- README.md
- docs/design-goals.md
- docs/faq.md
- docs/usage.md
We can't use them in stardoc generated docs, as it mangles the encoding of them...
> Use curly quotes where possible in docs

- .bcr/config.yml
By having it be me, I can amend release commits easier. Later we should be able to use an organization fork instead, so any maintainers can amend the release commits.
> Adjust BCR Publish releaser

- shared.bazelrc
We don't need to set this in our `.bazelrc` anymore, since it's the default since rules_swift 1.5.0.
> Remove repo `--features=swift.use_global_module_cache`

- xcodeproj/internal/bazel_integration_files/import_indexstores.sh
When using `--features=swift.file_prefix_map`, the paths will start with `./` instead of the execution root.
> Fix handling of relative paths in index unit files

- xcodeproj/internal/bazel_integration_files/import_indexstores.sh
In very odd situations, most likely because of other bugs, `ARCHS` can be set to two architectures. This will 100% result in an invalid import, so let’s pick the first one, which is most likely the correct one.
> Use the first arch if multiple are set

- xcodeproj/internal/xcodeproj_rule.bzl
Fixes #1768.
If an `ios_framework` target depends on a sourceless `objc_library` target, the `objc_library` won’t be in `focused_targets`. We incorrectly only filtered `target_merge_dests` when `has_unfocused_targets`, but that’s not set when we filter out sourceless targets (though maybe we should?). Always filtering them fixes generation.
> Fix project generation when merge target becomes unfocused

- examples/cc/MODULE.bazel
- xcodeproj/repositories.bzl
But don’t force it on Bzlmod users, as it doesn’t contain anything we _need_.
> Upgrade rules_apple to 2.1.0

- examples/integration/Lib/BUILD
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
- examples/integration/test/fixtures/bwx_project_spec.json
- xcodeproj/internal/default_automatic_target_processing_aspect.bzl
Fixes #1779.
Previously we were only generating this file for binary rules. Now we do the same for bundle rules as well.
> Fix `*_framework.exported_symbols_list` in BwX mode

- xcodeproj/internal/xcodeproj_rule.bzl
> Fix `extra_files` logic for merged target when using focused targets

- examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- xcodeproj/internal/xcodeproj.template.bazelrc
This is only a speed up if sandboxing is used, which is the default for us currently (outside of worker actions, like `SwiftCompile`).
> Use the `--reuse_sandbox_directories` flag

- examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- xcodeproj/internal/xcodeproj.template.bazelrc
This reverts commit 928cb34e819300747980396b2b617d4a15ef7a92.
Ran into errors like this:
> ERROR: /Users/brentley/Developer/rules_xcodeproj/tools/generator/BUILD:20:14: Linking tools/generator/libgenerator.library.a [for tool] failed: I/O exception during sandboxed execution: /Users/brentley/Developer/rules_xcodeproj/bazel-output-base/rules_xcodeproj/build_output_base/sandbox/darwin-sandbox/45/execroot/com_github_buildbuddy_io_rules_xcodeproj/bazel-out (No such file or directory)
When I was running `./test/update_all_fixtures.sh`.
> Revert "Use the `--reuse_sandbox_directories` flag (#1784)"

- xcodeproj/internal/xcode_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
Currently we hardcode it to be the same single “Debug” configuration, but the logic works for multiple once we have them.
> Handle multiple Xcode configurations in `xcodeproj_rule.bzl`

- xcodeproj/internal/opts.bzl
Fixes #1809.
Both `cc_library` and `objc_library` tokenize their `copts` attributes. We use the undocumented `ctx.tokenize`, but if that goes away we could use something like https://github.com/bazelbuild/bazel/blob/1d73d72a45598e38c51b2618bb6fe4f27b390cb8/src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl#L795-L853.
> Fix CC `copts` tokenization

- test/internal/bazel_labels/normalize_tests.bzl
- xcodeproj/internal/bazel_labels.bzl
- xcodeproj/internal/workspace_name_resolvers.bzl
`native.package_relative_label` can only be used from a `BUILD` thread, so it needs to be abstracted away like our other label functions, in order to test Starlark that uses it.
> Move `native.package_relative_label` into `workspace_name_resolvers`

- xcodeproj/internal/runner.template.sh
Fixes #1847 (along with a change to the wrapper script to have a valid `PATH`).
> Properly invoke `bazelisk` in `runner.sh`

- examples/cc/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UniversalCommandLineTool (arm64).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UniversalCommandLineTool (x86_64).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
- examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
- examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
- examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
- test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
- test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
- tools/generator/src/Extensions/XCScheme+Extensions.swift
Part of #1284.
Currently this isn’t needed, but with a future change that remaps the paths in the dSYMS, this will fix some relative path issues in BwB mode.
Extracted from #1767.
> Run `copy_dsyms.sh` with Launch action as well

- test/fixtures/generator/bazel-6/bwb_replacements.txt
- test/fixtures/generator/bazel-6/bwx_replacements.txt
- tools/generator/xcodeproj_targets.bzl
This results in cache misses, since the paths are absolute to the machine they are run on. Ideally we can come up with a way to handle the relative paths (like launching `Instruments.app/Contents/MacOS/Instruments` from the Bazel execution root), but for now this makes it easier for me to profile things.
> Fix source code viewing in Instruments for `generator`

- xcodeproj/internal/bazel_integration_files/copy_dsyms.sh
To improve some lldb handling of relative source paths, we create a plist file inside the dSYM file with `DBGSourcePathRemapping` which will remap relative paths to absolute paths (see [documentation](https://lldb.llvm.org/use/symbols.html#id2)).
This logic has been added to the `copy_dsyms.sh` script, which will be run as Launch and Profiling pre-actions.
> Patch dSYM path

- tools/params_processors/link_params_processor.py
- xcodeproj/internal/xcode_targets.bzl
Fixes #855.
Closes #1857.
It seems the `Args` object that the linker creates might not always result in a params file being created. So now we force that to happen, and account for possibly multiple `Args` files being created, and for them to mention params files themselves.
> Use sub-params files for linker params processing

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- tools/generator/src/DTO/Inputs.swift
- tools/generator/src/Generator/ConsolidateTargets.swift
- tools/generator/test/ConsolidatedTargetTests.swift
- tools/generator/test/Fixtures.swift
Part of #1854.
In BwB mode we don’t embed the resource files, so we don’t need to account for them.
> Remove resource files from conditional source files in BwB mode

- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
Before we would check Swift-only flags in the CC path, and vice versa.
> Check VFS overlay flags more efficiently

- xcodeproj/internal/runner.template.sh
- xcodeproj/repositories.bzl
We need to use the outer output base, so `Index Build` can find the generator as well.
> Fix output base hashing

- MODULE.bazel
- xcodeproj/extensions.bzl
- xcodeproj/repositories.bzl
This is mainly to make the label look nicer in outputs.
> Move `@rules_xcodeproj_generated` to its own module extension

- xcodeproj/internal/xcodeproj_rule.bzl
Fix the case where `len(src_ids) > 1` considers a merge not possible despite one or more of the sources being not present in Xcode already because of `should_create_xcode_target = False` or otherwise.
> Ensure target merge src is present in Xcode

- tools/generator/src/DTO/BuildSetting.swift
- tools/generator/src/Extensions/XcodeScheme+Extensions.swift
- tools/generator/src/Generator/SetTargetConfigurations.swift
This was found with SwiftLint's upcoming improved dead code analysis.
Let me know if some of this stuff should be kept for future use.
Signed-off-by: JP Simard <jp@jpsim.com>
> Remove unused Swift declarations in `tools/generator/...`

- xcodeproj/repositories.bzl
Not bumping in `MODULE.bazel` because we don’t require any of the changes.
> Upgrade rules_apple to 2.2.0

- xcodeproj/internal/xcodeproj_rule.bzl
Fixes https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/1912#issuecomment-1484594604.
This reverts commit ed31d6916858f3099ba1a95750f5309913370a8d.
> Revert "Ensure target merge src is present in Xcode (#1903)"

- xcodeproj/internal/input_files.bzl
Before this change the extra files would be associated with the next target(s) down the dependency tree. This now allows you to properly unfocus the source files of targets that won't become Xcode targets.
> Associate non-Xcode target source files with the correct label

- xcodeproj/internal/xcodeproj_rule.bzl
Break the assumption that `target_merge_dests` contains a single dest to a single src mapping since we’ll want to merge multiple src into a single dest in the future.
TODO: Add concrete handling in `xcode_targets` for merging multiple source `xcode_target`s.
Work towards https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/1724.
> Add ability to have dest merge from multiple srcs

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/linker_input_files.bzl
Part of #1922.
This is the case for dynamic libraries. For now these targets don’t create Xcode targets, but work in both BwX and BwB mode.
> Support targets not having any static libraries

- buildbuddy.yaml
Framework linking is different between Bazel 5 and 6, so we can’t compare the fixtures between them anymore.
> Stop validating Bazel 5 fixtures

- MODULE.bazel
- WORKSPACE
- examples/integration/iOSApp/Resources/ExampleResources/BUILD
- xcodeproj/internal/bazel_integration_files/BUILD
- xcodeproj/internal/files.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/resources.bzl
- xcodeproj/internal/xcode_targets.bzl
We don’t need to check every folder type extension for every case. This was noticed as a hot spot in Starlark profiles.
> Improve `normalized_file_path` efficiency

- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
- examples/integration/test/fixtures/bwx_project_spec.json
- test/internal/target/process_top_level_properties_tests.bzl
- tools/generator/src/DTO/FilePath.swift
- tools/generator/src/Generator/CreateFilesAndGroups.swift
- tools/generator/test/Fixtures.swift
- xcodeproj/internal/files.bzl
- xcodeproj/internal/resources.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
`generated.xcfilelist` only needs to include files that are in the navigator, and actually only those that are referenced in `PBXBuildFile`s.
This also removes the need for `file_path.include_in_navigator`.
> Stop adding folder-nested generated files to `extra_files`

- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/internal/target/process_top_level_properties_tests.bzl
- tools/generator/src/DTO/FilePath.swift
- xcodeproj/internal/files.bzl
- xcodeproj/internal/resources.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
The distinction from `is_folder` only (currently) needs to exist in the generator.
> Remove `file_path.force_group_creation`

- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/internal/target/process_top_level_properties_tests.bzl
- tools/generator/src/DTO/FilePath.swift
- tools/generator/src/DTO/Inputs.swift
- tools/generator/src/DTO/Project.swift
- xcodeproj/internal/files.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/resources.bzl
- xcodeproj/internal/xcode_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
Instead we send over folder file paths in their own attributes, and apply `isFolder` in `generator`.
This is progress towards being able to remove the `file_path` construct on the Starlark side entirely.
> Remove `file_path.is_folder`

- tools/generator/src/Generator/Main.swift
New error looks like this:
```
ERROR: Internal precondition failure:
Error decoding "bazel-out/darwin_x86_64-dbg-ST-18efdd23c365/bin/external/rules_xcodeproj_generated/generator/generator_xccurrentversions":
At codingPath []: The given data was not valid JSON.
Please file a bug report at https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/new?template=bug.md
```
> Improve error message when decoding fails

- xcodeproj/internal/bazel_integration_files/calculate_output_groups.py
Previously we might have incorrectly picked up a stale XCBuildData folder. This could have us build the wrong thing, or get a hung build if Xcode deleted the folder (which it now can do in Xcode 14.3).
> Wait for Xcode to write `XCBuildData`

- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
Regressed with e4b289af0c869fbf8dfdc48f784f44d27ea268bf.
Since we now always have one element, we need to make sure it’s more than 1.
> Fix empty `output_groups` check

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwb_project_spec.json
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx_project_spec.json
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_project_spec.json
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx_project_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_project_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_project_spec.json
- tools/generator/src/DTO/Project.swift
- tools/generator/src/Generator/AddBazelDependenciesTarget.swift
- tools/generator/src/Generator/Environment.swift
- tools/generator/src/Generator/Generator.swift
- tools/generator/test/Fixtures.swift
- tools/generator/test/GeneratorTests.swift
- xcodeproj/internal/bazel_integration_files/bazel_build.sh
- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
- xcodeproj/internal/xcodeproj_rule.bzl
Before this change, if something would cause your target ids to change, like a config change, and you didn’t regenerate your project, building with Xcode could silently do nothing on a build. Now `bazel_build.sh` can properly detect this, buy verifying that all requested target ids are known by the `xcodeproj` target.
> Verify that the requested target ids were valid

- tools/generator/src/DTO/Project.swift
- tools/generator/src/Generator/CreateProject.swift
- xcodeproj/internal/bazel_integration_files/bazel_build.sh
- xcodeproj/internal/runner.template.sh
We don’t need to filter `$PATH`, because resolving to the downloaded `bazel` is fine, and will only happen if a `tools/bazel` isn’t being used (as that would be at the front of the path instead).
We don’t need to unset `BAZELISK_SKIP_WRAPPER`, because we are either resolving to `tools/bazel`, in which case it has no effect (and we probably actually want it set anyway), or we are resolving directly to bazel (in which case it has no effect), or we are resolving to bazelisk (in which case there wasn’t a wrapper anyway, so it should be set for efficiency sake).
We don't need to explicitly set `BAZEL_REAL` in `bazel_build.sh`, since we aren’t using `env -i`. And because of this, we only set `BAZEL_REAL` as a build setting if needed.
> Simplify `bazel_path` resolution

- docs/bazel.md
- xcodeproj/internal/providers.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
For example, before this change we couldn’t focus `@com_github_krzyzanowskim_cryptoswift//:CryptoSwift` in `examples/integration`.
> Allow {un,}focusing of non-Xcode targets

- xcodeproj/internal/xcodeproj_rule.bzl
Before:
```
INFO: From GenerateXcodeProj external/_main~internal~rules_xcodeproj_generated/generator/tools/generator/xcodeproj/xcodeproj.xcodeproj:
WARNING: Was unable to consolidate target groupings "[@@//tools/generator/test:tests.__internal__.__test_bundle applebin_macos-darwin_arm64-dbg-ST-4bf02e38abc1], [@@//tools/generator/test:tests.__internal__.__test_bundle applebin_macos-darwin_arm64-opt-ST-49992506bac4]" since they have conditional dependencies (e.g. `deps`, `test_host`, `watch_application`, etc.)
```
After:
```
INFO: From Generating "tools/generator/generator.xcodeproj":
WARNING: Was unable to consolidate target groupings "[@@//tools/generator/test:tests.__internal__.__test_bundle applebin_macos-darwin_arm64-dbg-ST-4bf02e38abc1], …
```
> Improve progress message for project generation

- examples/cc/test/fixtures/bwb_project_spec.json
- examples/cc/test/fixtures/bwx_project_spec.json
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwx_project_spec.json
- examples/rules_ios/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwx_project_spec.json
- test/fixtures/generator/bwb_project_spec.json
- test/fixtures/generator/bwx_project_spec.json
- xcodeproj/internal/xcodeproj_macro.bzl
- xcodeproj/internal/xcodeproj_runner.bzl
The canonical version works, so we can let the runner provide this label.
> Stop providing `runner_label` to the runner

- xcodeproj/internal/files.bzl
Ran `--starlark_cpu_profile` in one of our apps and noticed a small optimization we can do. This skips early if `extension not in path` to avoid an unnecessary `.partition()` call.
Before:
After:
I noticed that `file_path` has increased from `48.99s` to `58.45s` after this change but I couldn't find evidence for any change in behaviour here. I sent to a file all paths hitting both `return` statements in this code and I couldn't find any delta.
Still, I believe since things improve at the `normalized_file_path` level we can always come back and improve `file_path` in a separate PR. Open to suggestions here though!
> Skip unnecessary partition call in normalized_file_path

- xcodeproj/internal/xcodeproj_runner.bzl
Why
- This value of `adjust_schemes_for_swiftui_previews` should be `True` according to the docs, but in the  `xcodeproj_runner` rule it's set to False. 
What 
- Change default value of `adjust_schemes_for_swiftui_previews` to `True` in `xcodeproj_runner`
> Change default value of `adjust_schemes_for_swiftui_previews` to True

- xcodeproj/internal/runner.template.sh
- xcodeproj/repositories.bzl
If someone generated a project before 1a45cceea54ee37aa0bf15a7f847eab10c1f3e6a, and their project is under a `//build` package, they can run into an error like this:
```
mkdir: /tmp/rules_xcodeproj/generated/26a7aae8a172d3845d4cafea37027a39/generator/build: Not a directory
```
The fix is to delete `/tmp/rules_xcodeproj/generated/26a7aae8a172d3845d4cafea37027a39/generator`, but instead we will just change the path to make sure people can upgrade from 1.3.3 to 1.4.0 without issues.
> Change generated repository path

- xcodeproj/internal/compilation_providers.bzl
It’s expensive (CPU and memory) to create compilation contexts if they aren’t needed.
> Stop calling `create_compilation_context` if no deps

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- xcodeproj/internal/bazel_integration_files/import_indexstores.sh
- xcodeproj/internal/installer.template.sh
- xcodeproj/internal/runner.template.sh
This allows Instruments to find the modified dSYM in Xcode’s DerivedData.
> Prevent spotlight from indexing our Bazel output bases

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
This was off if the optimization level was different from the default, and the target didn’t have both C and C++ sources.
> Fix CC optimization level flag calculations

- docs/bazel.md
- xcodeproj/internal/default_automatic_target_processing_aspect.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/providers.bzl
- xcodeproj/internal/provisioning_profiles.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeproj_aspect.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
The next step will be to remove the aspect and instead calculate this information if a different provider doesn’t exist that gives it to us. We don’t need this information to go to downstream targets, so we don’t need to hold onto its memory.
> Further improve `XcodeProjAutomaticTargetProcessingInfo` memory usage

- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests_CommandLineArgs_Scheme.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppUnitTests_Scheme.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
- examples/integration/test/fixtures/bwb_targets_spec.json
- xcodeproj/internal/xcodeproj_rule.bzl
We were looking at dependencies for too many targets. We only have to consider the dependencies for targets that can themselves display SwiftUI previews.
Also fixes the list of target types that can include SwiftUI Previews.
> Short circuit `_calculate_swiftui_preview_targets`

- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
This is to remove the call to `uniq`, which was noticed as a hot spot in Starlark CPU profiling.
> Use `depset` for `extra_files` processing

- xcodeproj/internal/bazel_integration_files/create_lldbinit.sh
Closes #2035.
Updates the `grep` command to use `^` and `$` to match the entire line, if no match is found it adds the command to the end of the file.
Additionally, adss an extra step before we append the lldbinit content to ensure the file contains a new line.
```sh
tail -c 1 "$lldbinit" | read || echo >> "$lldbinit"
```
This will read last char of lldbinit but only runs echo to add a new line iff the read fails (i.e. EOF found before new line)
```sh
cat ~/.lldbinit                                                                                                 
command echo "hello world"%
command echo "hello world"
command source ~/.lldbinit-rules_xcodeproj
```
```sh
cat ~/.lldbinit                                                                                                 
command …
```
> Fix `create_lldbinit.sh` not appending content to a new line

- xcodeproj/internal/xcodeproj_rule.bzl
We only need to look at these label strings if we have focused labels or owned extra files.
> Prevent calculating `label_strs` if not needed

- tools/generator/src/DTO/FilePath.swift
- tools/generator/src/DTO/Inputs.swift
- tools/generator/src/DTO/Project.swift
- tools/generator/src/Extensions/Path+Extensions.swift
- tools/generator/src/Generator/CreateFilesAndGroups.swift
- tools/generator/test/Fixtures.swift
We already normalize paths in Starlark, so `filePath.path.isFolderTypeFileSource` is a no-op check.
This does codify (for now) that localized files or CodeData files can never have their folders be folders, they will always be recognized as folder type files. Later, after refactoring `createFilesAndGroups`, we can fix this to allow those to be unstructured files as well.
> Remove `FilePath.forceGroupCreation`

- tools/generator/src/Extensions/XcodeScheme+Extensions.swift
- tools/generator/src/Generator/TargetResolver.swift
Takes a certain large project’s `createCustomXCSchemes()` time from 26.8s to 313ms (85x faster!).
> Resolve `TargetResolver.labelTargetInfos` eagerly

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/top_level_targets.bzl
This value is only used in the aspect that creates it, so we don’t need to hold onto the memory for it in the provider.
> Stop retaining `implementation_compilation_context` in `XcodeProjInfo`

- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/resources.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcode_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
We should retain the minimum needed in the `XcodeProj` provider.
> Stop retaining some of `input_files` in `XcodeProj`

- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/output_files.bzl
- xcodeproj/internal/resource_target.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
We should retain the minimum needed in the `XcodeProj` provider.
> Stop retaining some of `output_files` in `XcodeProj`

- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- tools/generator/src/Extensions/Sorting.swift
Regressed with 9041dc2af622df7b3c0221add5ff1cbf07dc5b1b.
We are caching the non-fully created tree result in `PBXFileElement.namePathSortString`, so we need a new cache for `PBXBuildFile` explicitly, which can take into account the parent.
> Fix more sorting non-determinism

- xcodeproj/internal/bazel_integration_files/import_indexstores.sh
Post rules_swift 1.6.0 release, "DEVELOPER_DIR" remapping was enabled by default.
I was debugging a different indexing issue and hence came across an observation where this is not remapped to local machine dev directory.
I also haven't seen any issue with rules_xcodeproj indexing so in case this is not needed, happy to abandon it.
Before this change:
[ContentView.o-3P4ZTLDW8HNC.zip](https://github.com/MobileNativeFoundation/rules_xcodeproj/files/11278087/ContentView.o-3P4ZTLDW8HNC.zip)
After this change:
[ContentView.o-3P4ZTLDW8HNC.zip](https://github.com/MobileNativeFoundation/rules_xcodeproj/files/11278090/ContentView.o-3P4ZTLDW8HNC.zip)
> Fix `import_indexstores.sh` when using `swift.remap_xcode_path`

- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/output_files.bzl
In BwB mode we don’t need the BwX mode output groups, and vice versa.
> Stop producing unneeded output groups

- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/output_files.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
While this can make them less generic, it makes it a lot easier to read this code.
> Rename some variables to be clear on what build_mode they apply to

- xcodeproj/internal/input_files.bzl
With other changes I think this is no longer needed (fixtures have no changes), and this reduces memory usage (even though it’s not retained, it’s adding more memory to the Starlark side it seems). I believe the original reason for having it was something involving `*_import` based rules.
> Remove unneeded `target.files.to_list()`

- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- tools/generator/src/Extensions/Sorting.swift
Old way wouldn’t take into account parent of parents, because it would end up hitting the `PBXFileElement` cache. Solution is to move the `PBXBuildFile` cache into `PBXFileElement` and use a different property recursively.
> Actually fix `PBXBuildFile` sorting

- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/output_files.bzl
- xcodeproj/internal/target_properties.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
I should have done this a long time ago, but there used to be some more logic around these lists. This is mainly a CPU win, but also a huge readability win.
> Pre-filter `transitive_infos`

- xcodeproj/internal/input_files.bzl
Doesn’t create an intermediate list, and stops looping early.
> Compute `has_generated_files` more efficiently

- xcodeproj/internal/input_files.bzl
> Use `EMPTY_DEPSET` for `_output_group_list` when unused

- xcodeproj/internal/xcodeproj_rule.bzl
> Use `args()` for `_write_target_ids_list`

- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
Makes it clear it’s only used in BwX mode.
> Rename `unfocused_libraries` to `bwx_unfocused_libraries`

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwb_targets_spec.json
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx_targets_spec.json
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb_targets_spec.json
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb_targets_spec.json
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/top_level_targets.bzl
The default is `"NO"`. Results in smaller projects and reduced Starlark memory usage.
> Stop setting `ENABLE_BITCODE = "NO"`

- tools/generator/src/Generator/SetTargetConfigurations.swift
When we have multi-language targets, this check would be incorrect. The `isEmpty` checks, along with the source file check, are all that is needed to make this work correctly.
> Remove an `isSwift` check

- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx_project_spec.json
- examples/integration/test/fixtures/bwx_targets_spec.json
- examples/rules_ios/test/fixtures/bwb_targets_spec.json
- tools/generator/src/DTO/Inputs.swift
- tools/generator/test/Fixtures.swift
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/xcode_targets.bzl
Since we set `GCC_PREFIX_HEADER` in Starlark, we don’t need to special case it in the generator. Reduces Starlark memory usage.
> Add pch files to `extra_files`

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/lldb_contexts.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
We no longer use `implementation_compilation_context` to get compiler opts in Bazel 6+. We only use it for `framework_includes`. So we don’t need to merge all of the other fields, or create a new `cc_compilation_context`, when we are Bazel 6+.
> Only merge `framework_includes` in Bazel 6+

- xcodeproj/internal/xcode_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
Also rename `bwx_unfocused_dependencies` to `bwx_unfocused_dependencies` to make it clear it’s only for BwX mode.
> Stop looping over `transitive_dependencies` in BwB mode

- xcodeproj/internal/xcode_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
Transition `_swift_params`, `_c_params`, & `_cxx_params` to non-underscore prefix since they're used external to `xcode_targets.bzl`.
> Rename `xcode_target._*_params` to `xcode_target.*_params`

- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/processed_target.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
Should have been removed with 1cf5e8c897e7c7774a7bfeb418de618f653fe28c.
> Stop storing `automatic_target_info` in `processed_target`

- xcodeproj/internal/xcodeproj_rule.bzl
Replacement for https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/2145.
> Correct multi-destination src merge

- xcodeproj/internal/xcode_targets.bzl
Ensure we don’t add/access `None` to a couple places in the `xcode_target` merging logic.
Error 1:
```
ERROR: /private/var/tmp/_bazel_matt.robinson/0e64031a9efbb95e4728094ee9457143/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj_generated/generator/tests/ios/app/foo/BUILD:12:10: in xcodeproj rule @rules_xcodeproj_generated//generator/tests/ios/app/foo:foo:
Traceback (most recent call last):
File "/private/var/tmp/_bazel_matt.robinson/0e64031a9efbb95e4728094ee9457143/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl", line 1596, column 25, in _xcodeproj_impl
) = _process_targets(
File "/private/var/tmp/_bazel_matt.robinson/0e64031a9efbb95e4728094ee9457143/rules_xcodeproj.noindex/build_output_base/external/rules_xcodep …
```
> Ensure target product file is present for merges

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- tools/generators/README.md
- tools/generators/legacy/src/Generator/AddBazelDependenciesTarget.swift
Most projects have external and generated files, and we don’t really need a conditional name for this run script. This also helps future incremental generation work.
> Simplify and rename `Bazel Build` run script

- tools/generators/legacy/src/Generator/AddBazelDependenciesTarget.swift
- tools/generators/legacy/src/Generator/CreateFilesAndGroups.swift
- tools/generators/legacy/src/Generator/Environment.swift
- tools/generators/legacy/src/Generator/Generator.swift
- tools/generators/legacy/test/CreateFilesAndGroupsTests.swift
- tools/generators/legacy/test/GeneratorTests.swift
Forgot this with a49fcc292ebb5a76b88d8b0bad9c888c62ce12b5.
> Always create `{external,generated}.xcfilelist` files

- xcodeproj/internal/top_level_targets.bzl
These targets shouldn’t be included in `top_level_targets`.
> Mark app extensions as not top level

- examples/cc/test/fixtures/bwb_project_spec.json
- examples/cc/test/fixtures/bwx_project_spec.json
- examples/rules_ios/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwb_project_spec.json
- examples/sanitizers/test/fixtures/bwx_project_spec.json
- test/fixtures/generator/bwb_project_spec.json
- test/fixtures/generator/bwx_project_spec.json
- tools/generators/legacy/src/DTO/Project.swift
- tools/generators/pbxproject_prefix/README.md
- tools/generators/pbxproject_prefix/src/Generator/Arguments.swift
- xcodeproj/internal/project_options.bzl
Since `ProjectOptions` is only set once per project, the spec is only slightly larger by not sending the default value. This simplifies the logic that has to change if we ever change the default, and is a slight Starlark CPU use reduction.
> Set default for `developmentRegion` in one place

- buildbuddy.yaml
Somewhere along the way I disabled this. Oops.
> Bring back `examples/integration` fixture validation

- examples/integration/iOSApp/Test/BUILD
- examples/integration/iOSApp/Test/ObjCUnitTests/BUILD
- examples/integration/iOSApp/Test/SwiftUnitTests/BUILD
- examples/integration/iOSApp/Test/UITests/BUILD
- examples/rules_ios/iOSApp/Test/MixedUnitTests/BUILD
- examples/rules_ios/iOSApp/Test/ObjCUnitTests/BUILD
- examples/rules_ios/iOSApp/Test/SwiftUnitTests/BUILD
- examples/rules_ios/iOSApp/Test/UITests/BUILD
#2196 has surfaced an issue related to tests actually running as part of the CI checks. There's timeouts happening and we might want to investigate that better (and potentially decide if we even want to run tests or not). From a project generation perspective we don't necessarily have to run the tests.
For those reasons, this PR makes tests `manual`. Planning to do the same with the new tests being added in #2196 once this lands.
> Make iOS tests in examples manual

- xcodeproj/BUILD
I have the need to generate [stardoc](https://github.com/bazelbuild/stardoc) documentation for our rules that currently import `rules_xcodeproj`. For this reason, I need to set up the full transitive set of dependencies between Starlark files. This change will make it easier for other consumers to also depend on this public `bzl_library` target.
> Add public bzl_library for xcodeproj files

- tools/generators/lib/PBXProj/src/Identifiers.swift
> Fix formatting of `Identifiers.Project.buildConfiguration()`

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- tools/params_processors/swift_compiler_params_processor.py
- xcodeproj/internal/opts.bzl
Trying to rely on `OTHER_SWIFT_FLAGS` as much as possible.
> Remove special handling for `SWIFT_COMPILATION_MODE`

- tools/generators/legacy/src/Generator/CreateFilesAndGroups.swift
- tools/generators/legacy/src/Generator/Environment.swift
- tools/generators/legacy/src/Generator/Generator.swift
- tools/generators/legacy/test/CreateFilesAndGroupsTests.swift
- tools/generators/legacy/test/GeneratorTests.swift
Should have changed this with 8dbd5eb59cfb53b5ee7dc7b593a693beb497ec15.
> Properly set development region in `PBXProject.knownRegions`

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- tools/params_processors/swift_compiler_params_processor.py
- xcodeproj/internal/opts.bzl
Trying to rely on `OTHER_SWIFT_FLAGS` as much as possible.
> Remove special handling for `SWIFT_OPTIMIZATION_LEVEL`

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- tools/generators/legacy/src/Generator/CreateFilesAndGroups.swift
- xcodeproj/internal/bazel_integration_files/create_lldbinit.sh
When adding support for `--experimental_sibling_repository_layout`, it’s less confusing to see `".."` than `"."` for the prefix.
> Include leading `.` in `RESOLVED_REPOSITORIES` prefixes

- tools/generators/legacy/src/Generator/CreateFilesAndGroups.swift
This is less confusing, slightly more efficient, and fixes one incorrect calculation around generated and external resource file file list paths.
> Improve `filePathStr` and `fileListPathStr` handling

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- tools/params_processors/swift_compiler_params_processor.py
- xcodeproj/internal/opts.bzl
Reverts 9d4e1d7e9436b4b2ea8d39d9669ecf2c62da956d.
Xcode sets some stuff related to `SWIFT_COMPILATION_MODE` after where it places `OTHER_SWIFT_FLAGS` values, so we need to let Xcode handle this.
> Add back special handling for `SWIFT_COMPILATION_MODE `

- test/internal/opts/process_compiler_opts_tests.bzl
- tools/params_processors/swift_compiler_params_processor.py
- xcodeproj/internal/opts.bzl
Reverts 77a5ac6ffc0946ea953b753e11a886d77fd47375.
Xcode sets `-swift-version` after where it places `OTHER_SWIFT_FLAGS` values, so we need to let Xcode handle this.
> Add back special handling for `-swift-version`

- xcodeproj/internal/templates/installer.sh
- xcodeproj/internal/templates/runner.sh
- xcodeproj/repositories.bzl
This makes it so the generator package will persist across reboots and for a longer period of time. macOS can clean up periodically contents in `/tmp`. This can cause situations where for example a project is generated and the following day the package directory contents won’t exist anymore causing build failures.
> Move generator package directory to /var/tmp

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- tools/generators/legacy/src/Generator/SetTargetConfigurations.swift
I noticed that Xcode/SourceKit was mangling `-Xcc -working-directory=/var/tmp/_bazel_brentley/1e8d40aef6426414f84d16828a838b81/rules_xcodeproj.noindex/indexbuild_output_base/execroot/__main__` as `-Xcc -working-directory -Xcc =/var/tmp/_bazel_brentley/1e8d40aef6426414f84d16828a838b81/rules_xcodeproj.noindex/indexbuild_output_base/execroot/__main__`, so we might as well use the other version.
> Use non-`=` version of `-working-directory`

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- tools/generators/legacy/src/Generator/SetTargetConfigurations.swift
- tools/generators/legacy/test/Fixtures.swift
This allows them to be properly tracked by Xcode.
> Use `$(BAZEL_OUT)` for compile params files

- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- tools/params_processors/swift_compiler_params_processor.py
- xcodeproj/internal/opts.bzl
Regressed BwX with cbb742be7d4a1ae3e884d517e68f290d85d13d5f.
Also choosing to make paths absolute always, similar to the other ones.
> Fix `-F` handling

- xcodeproj/internal/bazel_integration_files/calculate_output_groups.py
Currently not supported, but building previously would silently fail instead of erroring out.
> Properly error out when using an `.xcworkspace`

- tools/swiftc_stub/main.swift
We won’t see the warnings, and we should fix this if it breaks. Should only break on Xcode upgrades, so I think it’s the correct call.
> Make `swiftc_stub` error out instead of warning

- BUILD
- MODULE.bazel
- distribution/BUILD
- xcodeproj/BUILD
- xcodeproj/dev_extensions.bzl
- xcodeproj/extensions.bzl
- xcodeproj/repositories.bzl
This removes all dependencies that are only needed for compiling tools, which we don’t do with the release archive.
> Remove unnecessary dependencies from release archive

- xcodeproj/internal/bazel_integration_files/process_bazel_build_log.py
We sometimes receive complains from our developers due to the fact that a tool invoked through a custom rule or such fails without a descriptive error. Most of the times, this can be controlled by prefixing all error messages with `error: ` when being executed from inside Xcode, but in some cases it's not. For those cases, the current output in Xcode is pretty cryptic:
Many engineers don't seem to be aware that it's possible to reveal more information in the report navigator. For this reason, I propose adding an error message that suggests to do if no error was parsed in the log. The result is the following:
In case there are errors parsed instead (such as a compiler error), we don't do anything.
I'm happy to hear what people think about this change, and if others have encountered a …
> Format error in Xcode when there are no diagnostics parsed

- xcodeproj/internal/templates/bazel_build.sh
- xcodeproj/internal/templates/runner.sh
Start to migrate to https://github.com/bazelbuild/apple_support/pull/222. We will need the `USE_CLANG_CL` version until we no longer support earlier `apple_support` versions.
> Set `--repo_env=XCODE_VERSION` as well

- xcodeproj/internal/opts.bzl
Doesn’t work still when the compiler plugin is unfocused though.
> Fix Swift macros with BwX mode

- examples/integration/platform_mappings
- examples/integration/platform_mappings-bzlmod
- shared.bazelrc
Not supported with Xcode 14.3+.
> Stop using i386 for watchOS

- buildbuddy.yaml
5.4.0 doesn’t work with newer macOS versions.
> Use Bazel 5.4.1 for Bazel 5

- tools/generators/files_and_groups/src/FilesAndGroups.swift
- tools/generators/lib/GeneratorCommon/src/ParsableCommand+Extensions.swift
- tools/generators/pbxproj_prefix/src/PBXProjPrefix.swift
Because we want to pass labels as arguments, which can start with `@`, we need to adjust our params file parsing to only check the first argument, and only if we have a single argument. This is more performant as well.
> Adjust params file parsing

- xcodeproj/internal/pbxproj_partials.bzl
Only `--colorize` benefits from this right now, but future partials will have flags that are reused many times, so having them extracted and frozen will help memory efficiency.
> Extract flag names in `pbxproj_partials.bzl`

- tools/generators/BUILD
- tools/generators/files_and_groups/src/ElementCreator/CreateVersionGroup.swift
- tools/generators/files_and_groups/src/ElementCreator/ElementCreatorArguments.swift
- tools/generators/files_and_groups/src/ElementCreator/ElementCreatorEnvironment.swift
- tools/generators/files_and_groups/src/ElementCreator/ReadSelectedModelVersionsFile.swift
- tools/generators/files_and_groups/test/ElementCreator/CreateVersionGroupTests.swift
- tools/generators/selected_model_versions/BUILD
- tools/generators/selected_model_versions/README.md
- tools/generators/selected_model_versions/selected_model_versions.py
- xcodeproj/internal/selected_model_versions.bzl
This is a modified version of `xccurrentversions_parser`, for use with the upcoming partial generators.
> Add `selected_model_versions` generator

- xcodeproj/internal/bazel_integration_files/import_indexstores.sh
All these patterns should only only be replaced at the start of the line since they should always be replacing absolute paths to Xcode. This theoretically improves the regex performance but more importantly should make the regex slightly more clear.
> Restrict DEVELOPER_DIR regex to the start of the line

- xcodeproj/repositories.bzl
This resolves a warning when using newer Swift versions.
> Upgrade swift-collections to “pre 1.0.5”

- xcodeproj/repositories.bzl
The latest version works, we were using apple_support 1.3.1 via `apple_rules_dependencies` accidently.
> Adjust Bazel 5 manual apple_support version override

- xcodeproj/internal/xcodeproj_macro.bzl
Works around a recursion issue if your `BAZEL_REAL` is actually a `bazelisk`-like binary.
> Capture `BAZELISK_SKIP_WRAPPER` as well

- xcodeproj/internal/xcodeproj_rule.bzl
We were overriding them in some cases instead of extending.
> Properly set `additional_bwx_*_files`

- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/AppStore-swift_debug_settings.py
- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py
- examples/rules_ios/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/Profile-swift_debug_settings.py
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/Release-swift_debug_settings.py
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/Profile-swift_debug_settings.py
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/Release-swift_debug_settings.py
- tools/params_processors/swift_debug_settings_processor.py
- tools/params_processors/swift_debug_settings_processor_tests.py
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/lldb_contexts.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
This fixes a regression caused by b59028f0329fb4f0d233ed87c6cabf7c9b8a1689.
This also fixes the order of the swiftmodule includes to match what Xcode generates in BwX mode.
In BwX mode, if this file has any contents, it will use the old way of determining the swiftmodule search paths first, then add any new paths at the end. This is to support the required path remapping, while also picking up testing framework search paths. This does mean that the order is still wrong for BwX mode, but there isn’t anything we can do about that (because we get the values from rules_swift which has already applied a different ordering to them).
> Determine `target.swift-module-search-paths` from params files

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- tools/generators/legacy/src/Generator/AddTargets.swift
- tools/generators/legacy/test/Fixtures.swift
Adds trailing newline and some more newlines between sub-commands.
> Improve whitespace for `Create Compile Dependencies` build phase script

- tools/generators/lib/PBXProj/src/Dictionary+Extensions.swift
- tools/generators/lib/PBXProj/test/DictionaryExtensionTests.swift
Will be used by more than one generator.
> Move `Dictionary.value(for:context:)` to `PBXProj`

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb_targets_spec.json
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb_targets_spec.json
- xcodeproj/internal/bazel_integration_files/copy_outputs.sh
- xcodeproj/internal/xcode_targets.bzl
Regressed with fa0f92e9dccc48da847604633fb1fdb9f0075aa7.
The names of these variables are confusing (`BAZEL_OUTPUTS_PRODUCT` probably should indicate that it can be the name of the archive). We can address that later.
> Fix `copy_outputs.sh` for archives

- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- tools/generators/legacy/src/Generator/SetTargetConfigurations.swift
We only read this value in `calculate_output_groups.py`, and there it’s already treated as a string separated by spaces. By explicitly making it a string, it’s easier to create in the new incremental generators.
> Convert `BAZEL_COMPILE_TARGET_IDS` to a string

- tools/generators/pbxproj_prefix/src/Generator/PBXProjectBuildSettings.swift
We don’t use the capabilities of the dictionary, so no need for the overhead.
> Use an array instead of a dictionary in `pbxProjectBuildSettings()`

- tools/generators/lib/PBXProj/src/Dictionary+Extensions.swift
I didn’t mean to limit it in that way.
> Pull `Dictionary.update` out of the `Key: Comparable` conformance

- tools/generators/pbxproj_prefix/README.md
- tools/generators/pbxproj_prefix/src/Generator/BazelDependenciesBuildSettings.swift
- tools/generators/pbxproj_prefix/src/Generator/PBXProjectBuildSettings.swift
- tools/generators/pbxproj_prefix/test/BazelDependenciesBuildSettingsTests.swift
- tools/generators/pbxproj_prefix/test/PBXProjectBuildSettingsTests.swift
This is more efficient.
Also fixes improperly escaped `INTERNAL_DIR`, `LIBTOOL`, and `SWIFT_EXEC`.
> Manually escape non-dynamic build settings

- tools/generators/lib/PBXProj/test/ConsolidationMapEntryTests.swift
- tools/generators/lib/PBXProj/test/TemporaryDirectory.swift
Will be reused in another test.
> Move `TemporaryDirectory` to its own file

- tools/generators/lib/PBXProj/src/BazelPath.swift
Allows it to be used as a key in a dictionary.
> Conform `BazelPath` to `Comparable`

- tools/generators/lib/PBXProj/src/ConsolidationMapEntry.swift
- tools/generators/lib/PBXProj/src/Identifiers.swift
- tools/generators/pbxproject_targets/src/Generator/DisambiguateTargets.swift
> Use `Data.init` instead of `.data(using:)`

- tools/generators/legacy/src/DTO/Target.swift
- tools/generators/legacy/src/Generator/DisambiguateTargets.swift
- tools/generators/legacy/test/CreateCustomXCSchemesTests.swift
- tools/generators/legacy/test/Target+Testing.swift
- tools/generators/legacy/test/XCSchemeInfo+BuildActionInfoTests.swift
- tools/generators/legacy/test/XCSchemeInfo+LaunchActionInfoTests.swift
- tools/generators/legacy/test/XCSchemeInfo+PrePostActionInfoTests.swift
- tools/generators/legacy/test/XCSchemeInfo+ProfileActionInfoTests.swift
- tools/generators/legacy/test/XCSchemeInfo+TestActionInfoTests.swift
- tools/generators/legacy/test/XCSchemeInfoTests.swift
- tools/generators/legacy/test/XcodeScheme+ExtensionsTests.swift
Because we were using `Set`, the order of `xcodeConfigurations` could vary in `distinguisherKey`. The order is stable from Starlark, so we are using `OrderedSet` to represent this.
> Fix a bug with disambiguating targets with multiple Xcode configurations

- tools/generators/legacy/src/Generator/DisambiguateTargets.swift
- tools/generators/legacy/test/DisambiguateTargetsTests.swift
- tools/generators/pbxproject_targets/src/Generator/DisambiguateTargets.swift
- tools/generators/pbxproject_targets/test/Generator/DisambiguateTargetsTests.swift
This used to be the case, but we regressed along the way.
> Allow same-name, different-productType disambiguated targets

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/c_lib (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/c_lib (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/lib_impl (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/lib_impl (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/lib_swift (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/lib_swift (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/private_lib (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/private_lib (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/private_swift_lib (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/private_swift_lib (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/c_lib (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/c_lib (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/lib_impl (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/lib_impl (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/lib_swift (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/lib_swift (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/private_lib (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/private_lib (x86_64) (AppStore, Debug) (f321a).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/private_swift_lib (x86_64) (AppStore, Debug) (7d2e3).xcscheme
- examples/integration/test/fixtures/bwx.xcodeproj/xcshareddata/xcschemes/private_swift_lib (x86_64) (AppStore, Debug) (f321a).xcscheme
- tools/generators/legacy/src/Generator/DisambiguateTargets.swift
- tools/generators/legacy/test/DisambiguateTargetsTests.swift
- tools/generators/pbxproject_targets/src/Generator/DisambiguateTargets.swift
- tools/generators/pbxproject_targets/test/Generator/DisambiguateTargetsTests.swift
We wouldn’t show architecture or Xcode configurations before.
> Add missing disambiguation when a config hash is shown

- examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- tools/generators/legacy/src/Generator/CreateProject.swift
- tools/generators/legacy/test/CreateProjectTests.swift
- tools/generators/pbxproj_prefix/README.md
- tools/generators/pbxproj_prefix/src/Generator/Environment.swift
- tools/generators/pbxproj_prefix/src/Generator/Generator.swift
- tools/generators/pbxproj_prefix/src/Generator/PBXProjectBuildSettings.swift
- tools/generators/pbxproj_prefix/test/PBXProjectBuildSettingsTests.swift
- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
- xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh
Previously unit files would remap to include the Index Build Bazel output base instead of the Build output base.
> Fix wrong execution root used in Index Build indexstore importing

- tools/generators/files_and_groups/src/ElementCreator/CreateGroup.swift
- tools/generators/files_and_groups/src/ElementCreator/CreateGroupChild.swift
- tools/generators/files_and_groups/src/ElementCreator/CreateSpecialRootGroup.swift
- tools/generators/files_and_groups/test/ElementCreator/CreateGroupTests.swift
- tools/generators/files_and_groups/test/ElementCreator/CreateSpecialRootGroupTests.swift
`bazelPathAndIdentifiers` will be used to map `BazelPath`s to identifiers for `PBXBuildFile` creation. A `PBXBuildFile` won’t need to reference a group, so we don’t need to add those identifiers to `bazelPathAndIdentifiers`.
> Stop including normal groups in `bazelPathAndIdentifiers`

- tools/generators/legacy/src/DTO/Target.swift
- tools/generators/legacy/src/Generator/DisambiguateTargets.swift
- tools/generators/legacy/test/DisambiguateTargetsTests.swift
- tools/generators/legacy/test/Target+Testing.swift
- tools/generators/pbxtargetdependencies/src/Generator/DisambiguateTargets.swift
- tools/generators/pbxtargetdependencies/test/Generator/DisambiguateTargetsTests.swift
A `Target` with multiple Xcode configurations should really be seen as multiple targets that share the same `TargetID`. This change reflects that, fixing a certain disambiguation.
I also used the opportunity to make a better key type, which is more efficient. A future change will prevent having to create this key multiple times.
> Fix disambiguating of targets with multiple Xcode configurations

- tools/generators/legacy/src/Extensions/PBXProductType+Extensions.swift
- tools/generators/pbxtargetdependencies/src/Generator/DisambiguateTargets.swift
Doesn’t need to be as verbose.
> Change “Command Line Tool” disambiguation to “Tool”

- MODULE.bazel
- WORKSPACE
- buildbuddy.yaml
> Upgrade Stardoc to 0.6.1

- test/internal/pbxproj_partials/write_files_and_groups_tests.bzl
- xcodeproj/internal/pbxproj_partials.bzl
This causes the params file to be named `files_and_groups.params` instead of `pbxproject_known_regions.params`, which is a lot less confusing.
> Change order of `files_and_groups` outputs

- test/internal/pbxproj_partials/write_pbxproj_prefix_tests.bzl
- tools/BUILD
- tools/generators/pbxproj_prefix/README.md
- tools/generators/pbxproj_prefix/src/Generator/Arguments.swift
- tools/generators/pbxproj_prefix/src/Generator/BazelDependenciesPartial.swift
- tools/generators/pbxproj_prefix/src/Generator/Environment.swift
- tools/generators/pbxproj_prefix/src/Generator/PBXProjectPrefixPartial.swift
- tools/generators/pbxproj_prefix/test/BazelDependenciesPartialTests.swift
- tools/generators/pbxproj_prefix/test/PBXProjectPrefixPartialTests.swift
- xcodeproj/internal/pbxproj_partials.bzl
More than one generator will need to know what the default Xcode configuration, so we determine it in Starlark.
> Make `defaultXcodeConfiguration` non-optional

- xcodeproj/internal/filelists.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/output_files.bzl
- Removes the use of `ctx`
- Prevents the creation of a params file when it’s not needed
> Clean up `filelists.write`

- examples/cc/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/rules_ios/test/fixtures/bwb_targets_spec.json
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
- test/fixtures/generator/bwb_targets_spec.json
- tools/generators/legacy/src/Generator/SetTargetDependencies.swift
- tools/generators/pbxtargetdependencies/src/Generator/ConsolidationMapsArguments.swift
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/target_properties.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
- Less information sent to generator
- Less memory Starlark memory retained
- Better target consolidation (since it was taking into account removed dependencies)
> Filter BwB dependencies in Starlark

- tools/generators/lib/PBXProj/src/String+Extensions.swift
This allows it to be used on `Substring` as well.
> Move `pbxProjEscaped()` to `StringProtocol`

- docs/bazel.md
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/processed_target.bzl
- xcodeproj/internal/providers.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
This now allows multiple layers of non-Xcode targets to exist between the top-level target and the library. The `product_path` was no longer used, so I removed that as well.
> Simplify/improve `non_xcode_targets` `mergable_xcode_library_targets` calculation

- xcodeproj/internal/non_xcode_targets.bzl
- xcodeproj/internal/output_files.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
After various past optimizations the need for `_create` with a lot of conditionals is no longer needed. Instead most of that code is merged into `_collect_output_files`, and `_merge_output_files` is greatly simplified.
> Simplify `output_files.bzl`

- MODULE.bazel
- examples/cc/.bazelrc
- examples/integration/MODULE.bazel
- shared.bazelrc
This is required with Bazel 7, so changing over now makes adding CI for Bazel 7 easier.
> Use apple_support Xcode toolchain

- MODULE.bazel
- WORKSPACE
- examples/cc/WORKSPACE
- examples/integration/WORKSPACE
- examples/rules_ios/WORKSPACE
- examples/sanitizers/WORKSPACE
- xcodeproj/repositories.bzl
This will be used to check for `ObjcProvider` linker info availability.
> Add bazel_features dependency

- examples/rules_ios/WORKSPACE
> Upgrade `examples/rules_ios` rules_apple to 2.5.0 as well

- examples/cc/MODULE.bazel
- examples/cc/test/fixtures/BUILD
- examples/integration/MODULE.bazel
- examples/integration/test/fixtures/BUILD
- examples/rules_ios/test/fixtures/BUILD
- examples/sanitizers/test/fixtures/BUILD
- test/fixtures/fixtures.bzl
- test/fixtures/generator/BUILD
- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/linker_input_files.bzl
- xcodeproj/internal/xcodeproj_rule.bzl
Info isn’t being populated into it like before, and eventually the provider is going away. So if we don’t find any libraries from it we fallback to the `CcInfo`.
> Add support for Bazel 7 `ObjcProvider` changes

- test/internal/build_settings/get_targeted_device_family_tests.bzl
- xcodeproj/internal/build_settings.bzl
Better for incremental generators.
> Return an empty string from `get_targeted_device_family`

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/top_level_targets.bzl
`{c,cxx}.compile.params` includes `-fmodules` as needed.
> Stop setting `CLANG_ENABLE_MODULES`

- xcodeproj/internal/memory_efficiency.bzl
> Forward transitive `depset` if possible

- xcodeproj/internal/memory_efficiency.bzl
Empty `depset`s evaluate to `False`.
> Simplify `depset.transitive` filtering

- buildbuddy.yaml
While we aren’t explicitly dropping support for it, we are no longer testing it on CI. this allows us to use some newer features in our integration tests.
> Remove Bazel 5 from CI

- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UIFramework.tvOS.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UIFramework.watchOS.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTestSuite.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTestSuite.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests_CommandLineArgs_Scheme.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppUnitTestSuite_Scheme.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppUnitTests_Scheme.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
- examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
- examples/rules_ios/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppMixedUnitTests.xcscheme
- examples/rules_ios/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTestSuite.xcscheme
- examples/rules_ios/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTestSuite_macro.xcscheme
- examples/rules_ios/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTests_macro.xcscheme
- examples/rules_ios/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTestSuite.xcscheme
- examples/rules_ios/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
- tools/generators/legacy/src/Generator/XCSchemeInfo+BuildTargetInfo.swift
- tools/generators/legacy/src/Generator/XCSchemeInfo+TargetInfo.swift
- tools/generators/legacy/test/XCSchemeInfo+BuildTargetInfoTests.swift
- tools/generators/legacy/test/XCSchemeInfo+TargetInfoTests.swift
Fixes #2543.
This is to get the icon of the scheme to match, in order:
- Launch target
- Test target
- Other targets
- (never) Additional targets for Swift UI Previews
This still isn’t 100%, because it doesn’t use info from the other actions, but we can make it better in the incremental generators.
> Change sorting of build action in schemes

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- examples/integration/xcodeproj.bazelrc
We enable it by default in `templates/xcodeproj.bazelrc`, so to actually have more coverage we should disable it. Plus, it doesn’t work with rules_apple 3.0’s macOS imported versioned frameworks.
> Disable tree artifacts for `examples/integration`

- xcodeproj/repositories.bzl
This causes WORKSPACE users that depend on rules_xcodeproj specifying their dependencies to get an updated rules_apple.
> Upgrade `xcodeproj_rules_dependencies` rules_apple to 2.5.0

- xcodeproj/repositories.bzl
This causes WORKSPACE users that depend on rules_xcodeproj specifying their dependencies to get an updated rules_swift.
> Upgrade `xcodeproj_rules_dependencies` rules_swift to 1.11.0

- MODULE.bazel
- WORKSPACE
- test/fixtures/generator/bazel-6/bwb_replacements.txt
- test/fixtures/generator/bazel-6/bwx_replacements.txt
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/external.xcfilelist
- test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
- test/fixtures/generator/bwb_project_spec.json
- test/fixtures/generator/bwb_targets_spec.json
- test/fixtures/generator/bwx.xcodeproj/project.pbxproj
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/external.xcfilelist
- test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
- test/fixtures/generator/bwx_project_spec.json
- test/fixtures/generator/bwx_targets_spec.json
- test/internal/info_plists/get_file_tests.bzl
- test/internal/targets/is_test_bundle_tests.bzl
This will allow us to use newer versions of Bazel 7.
> Upgrade development versions of rules_apple and rules_swift

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- test/fixtures/generator/bwb.xcodeproj/project.pbxproj
- tools/generators/legacy/src/Generator/CreateProject.swift
- tools/generators/legacy/test/CreateProjectTests.swift
- tools/generators/pbxproj_prefix/README.md
- tools/generators/pbxproj_prefix/src/Generator/PBXProjectBuildSettings.swift
- tools/generators/pbxproj_prefix/test/PBXProjectBuildSettingsTests.swift
We can’t use the artifacts it in BwB mode.
> Set `ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS = NO` in BwB mode

- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/output_files.bzl
- xcodeproj/internal/target_properties.bzl
- xcodeproj/internal/xcode_targets.bzl
Fixes #2563.
Top-level swift targets, such as `swift_test` don’t set a value for `SwiftInfo.direct_modules[0].swift`. This makes sense, as downstream targets shouldn’t get any transitive swiftmodules from it. We previously worked around this by manually including transitive direct swiftmodules. This worked fine until compiler plugins, which introduced a new way that transitive swiftmodules could be collected. Thankfully the information we need is in the `compilation_context`.
As part of this change, we now only add the `.swiftmodule` files to `generated`. Previously we would add `.swiftdoc` and the generated header as well. We can’t do that with the information in `compilation_context`. If the swift generated header is used as an input for another target, it will get picked up that way.
> Include all transitive swiftmodules in `bc` output group when needed

- xcodeproj/internal/xcodeproj_macro.bzl
This was setting `temporary_directory = None` on xcodeproj_runner, although it doesn't define it.
Example failure: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1645#018a8918-b94e-4920-97c1-46fee1f6c2e7
Addresses: https://github.com/bazelbuild/bazel/issues/19403
> Remove temporary_directory

- CODEOWNERS
This script can impact how a release could be made.
> Add `tools/bazel` to release code ownership

- CODEOWNERS
Bazel version (or a fork) can impact how a release could be made.
> Add `.bazelversion` to release code ownership

- bazel_7.bazelrc
- tools/bazel
Also removes `bazel_5.bazel`, which should have been dropped with d99e9f020323e5f0497941b9cd41d11699b8180c.
> Update `tools/bazel` to support `bazel_7.bazelrc`

- tools/generators/lib/PBXProj/src/Identifiers.swift
We don’t need the full `Identifiers.Targets.id()` in the upcoming `xcschemes` generator.
> Add `Identifiers.Targets.idWithoutComment()`

- tools/generators/lib/PBXProj/src/ConsolidationMapEntry.swift
- tools/generators/lib/PBXProj/test/ConsolidationMapEntryTests.swift
- tools/generators/pbxtargetdependencies/src/Generator/WriteConsolidationMap.swift
- tools/generators/pbxtargetdependencies/src/Generator/WriteConsolidationMaps.swift
> Remove label from `ConsolidationMapEntry.encode()`

- tools/generators/lib/PBXProj/src/TargetID.swift
Will be used in decoding `extension_point_identifiers_file`.
> Add `Decodable` conformance to `TargetID`

- tools/generators/lib/PBXProj/src/Optional+Extensions.swift
This will allow using things like `String?` directly in `ParsableArguments`.
> Add `ExpressibleByArgument` conformance to `Optional`

- tools/generators/legacy/xcodeproj_targets.bzl
These were only there for fixture testing, and it no longer has a fixture.
> Remove some settings from `//tools/generators/legacy:xcodeproj`

- xcodeproj/internal/bazel_integration_files/process_bazel_build_log.py
Looks like there's an off by 1 error in the log processing. The `BAZEL_OUT` environment variable sets up paths that end with `execroot/repo-name/bazel-out`, and this is causing an extra character to get cut off, which means error log paths produce `execroot/repo-nam/bazel-out` instead of `execroot/repo-name/bazel-out`.
> Fix process build log paths

- tools/generators/lib/PBXProj/src/Dictionary+Extensions.swift
Will prevent string creation if there isn’t an error.
> Use `@autoclosure` with `Dictionary.value()`

- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj_extra_flags.bazelrc
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj_extra_flags.bazelrc
- examples/rules_ios/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj_extra_flags.bazelrc
- shared.bazelrc
We already unset `--bes_backend= --bes_results_url=` for `indexbuild_rules_xcodeproj` in `xcodeproj.bazelrc`.
> Remove unneeded `extra_indexbuild_flags` setting

- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/rules_ios/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- xcodeproj/internal/templates/xcodeproj.bazelrc
For non-Swift targets, this is a huge speedup.
> Disable Bazel sandboxing by default

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- test/internal/opts/process_compiler_opts_tests.bzl
- xcodeproj/internal/opts.bzl
Bazel generates them, so we don't need to have Xcode try again.
> Stop generating dSYMs with Xcode in BwB mode

- buildbuddy.yaml
We would have had this more recently, but it was incorrectly returning an RC build instead of the latest release.
> Test 6.4.0 RCs in CI

- examples/integration/.bazelrc
- examples/integration/bazel_6.bazelrc
- examples/integration/platform_mappings
- examples/integration/platform_mappings-bzlmod_no_repo_map
Bazel 7 now properly supports repository maps in the `platform_mappings` file.
> Only use special `platform_mappings` when using Bzlmod with Bazel 6

- README.md
I've added information on how to manually build the release archive (`bazel build //distribution:release`). As I see this hasn't been mentioned anywhere, so I think README.md is the right place.
> Document how to manually build the release archive

- xcodeproj/repositories.bzl
This upgrades `WORKSPACE` users to rules_swift 1.12.0 and rules_apple 3.0.0.
Users not on Bazel 7.0.0-pre.20230823.4 or newer will most likely need a platform_mappings file. In the `examples/integration` directory are some examples of that file.
> Upgrade `xcodeproj_rules_dependencies` rules_swift and rules_apple

- tools/generators/lib/PBXProj/src/Optional+Extensions.swift
Returning `nil` means a parsing failure, we want `.some(.none)` instead.
> Fix parsing of `Optional` arguments

- examples/integration/MODULE.bazel
- examples/integration/WORKSPACE
- examples/integration/iOSApp/Source/BUILD
The most recent linker version doesn’t support rules_apple 3.0.0 with Xcode 15+. We aren’t losing out on much coverage anymore by doing this, since everything is handled in the `link.params` file with minimal filtering.
> Remove lld linker override

- tools/generators/lib/XCScheme/src/BuildableReference.swift
Needed in order to use `Set` to deduplicate them.
> Add `Hashable` conformance to `BuildableReference`

- tools/generators/legacy/src/Generator/CreateProducts.swift
- tools/generators/legacy/test/Fixtures.swift
Regressed with c744087bfae1271149ec8034e163f2b756252b02, because CI was no longer testing it (which will be enabled in a future change).
> Fix legacy tests

- tools/generators/lib/PBXProj/BUILD
- tools/generators/lib/PBXProj/src/Dictionary+Extensions.swift
Will be used in a future change.
> Add `.value(for:context:)` to `OrderedDictionary` as well

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- tools/generators/legacy/src/DTO/BazelLabel.swift
- tools/generators/legacy/test/BazelLabelTests.swift
Here's a proposal to favor the shorthand form of labels when they are used for Xcode target names,
i.e. `//foo/bar/lib` instead of `//foo/bar/lib:lib`.
That'll in particular make a positive difference when `target_name_mode = "label"` is used, and remove redundancies from names.
Before | After
--- | ---
For context, our project has targets that have long labels.
To give a pseudo-example, it would be more convenient to display in Xcode:
`//apple/Extraterrestrial/RegistrationSummaryTransition`
instead of 
`//apple/Extraterrestrial/RegistrationSummaryTransition:RegistrationSummaryTransition`
Since the shorthand form is synonymous with the full form, I don't expect this to break anything,
and haven't witnessed any issues during testing,
but please correct me if I'm shortsighted or if this …
> Favor shorthand form when using labels for Xcode target names

- shared.bazelrc
`AppleLipo` is newish action in apple_support (https://github.com/bazelbuild/apple_support/blob/45daa81ec696de891ecb5c4d4b6f3bdf99b19e03/lib/lipo.bzl#L62-L70) that creates large binaries, similar to the existing modifications.
> Add `AppleLipo` to `--modify_execution_info`

- test/internal/pbxproj_partials/write_pbxtargetdependencies_tests.bzl
- tools/generators/lib/PBXProj/src/ConsolidationMapEntry.swift
- tools/generators/lib/PBXProj/test/ConsolidationMapEntryTests.swift
- tools/generators/pbxtargetdependencies/src/Generator/CalculateConsolidationMaps.swift
- tools/generators/pbxtargetdependencies/src/Generator/CalculateIdentifiedTargetsMap.swift
- tools/generators/pbxtargetdependencies/src/Generator/ConsolidationMapsArguments.swift
- tools/generators/pbxtargetdependencies/src/Generator/CreateDependencyObjects.swift
- tools/generators/pbxtargetdependencies/src/Generator/CreateTargetAttributesObjects.swift
- tools/generators/pbxtargetdependencies/src/Generator/Environment.swift
- tools/generators/pbxtargetdependencies/src/Generator/Generator.swift
- tools/generators/pbxtargetdependencies/src/Generator/GeneratorArguments.swift
- tools/generators/pbxtargetdependencies/src/Generator/IdentifyTargets.swift
- tools/generators/pbxtargetdependencies/src/Generator/InnerIdentifyTargets.swift
- tools/generators/pbxtargetdependencies/src/Generator/Target.swift
- tools/generators/pbxtargetdependencies/test/Generator/CalculateConsolidationMapsTests.swift
- tools/generators/pbxtargetdependencies/test/Generator/CalculateIdentifiedTargetsMapTests.swift
- tools/generators/pbxtargetdependencies/test/Generator/ConsolidateTargetsTests.swift
- tools/generators/pbxtargetdependencies/test/Generator/ConsolidationMapsArgumentsTests.swift
- tools/generators/pbxtargetdependencies/test/Generator/CreateDependencyObjectsTests.swift
- tools/generators/pbxtargetdependencies/test/Generator/CreateTargetAttributesObjectsTests.swift
- tools/generators/pbxtargetdependencies/test/Generator/IdentifiedTarget+Testing.swift
- tools/generators/pbxtargetdependencies/test/Generator/InnerIdentifyTargetsTests.swift
- xcodeproj/internal/pbxproj_partials.bzl
This will be used by `pbxnativetargets` to generate the needed `Embed App Extensions` build phase for watchOS apps with watchKit extensions.
> Encode watchKit extension information into `ConsolidationMapEntry`

- tools/generators/files_and_groups/src/Generator/CreateBuildFileObject.swift
- tools/generators/files_and_groups/test/Generator/CreateBuildFileObjectTests.swift
- tools/generators/lib/PBXProj/src/BuildPhase.swift
- tools/generators/lib/PBXProj/src/Identifiers.swift
- tools/generators/lib/PBXProj/test/IdentifiersTests.swift
This was only needed for BwX support.
> Remove `Headers` build phase from incremental generators

- xcodeproj/internal/bazel_integration_files/import_indexstores.sh
This increases the odds of a previous long running import to succeed.
> Move `import_indexstores.sh` early exit to before kill

- test/internal/pbxproj_partials/write_files_and_groups_tests.bzl
- test/internal/pbxproj_partials/write_pbxproj_prefix_tests.bzl
- test/internal/pbxproj_partials/write_pbxtargetdependencies_tests.bzl
- test/mock_actions.bzl
This also changes the format of declared files to a `struct`, to better mimic `File`. This is needed in order to handle actions that use declared directories, like the upcoming `xcschemes` generator.
> Add support for `actions.declare_directory` to `mock_actions`

- tools/generators/legacy/src/Generator/XCSchemeInfo+LaunchActionInfo.swift
- tools/generators/legacy/test/XCSchemeInfo+LaunchActionInfoTests.swift
If you have a non-launchable target as a launch target in the scheme, you will get this error:
```
ERROR: Internal precondition failure:
tools/generators/legacy/src/Generator/XCSchemeInfo+LaunchActionInfo.swift:23: An XCSchemeInfo.LaunchActionInfo should have a launchable XCSchemeInfo.TargetInfo value.
```
If you have many schemes, it is difficult to find the root cause of the problem based on the error.
These changes should simplify it.
```
ERROR: Internal precondition failure:
tools/generators/legacy/src/Generator/XCSchemeInfo+LaunchActionInfo.swift:23: An XCSchemeInfo.LaunchActionInfo should have a launchable XCSchemeInfo.TargetInfo value: <label of the target>.
```
Let me know if you see a better way to formalize the error.
> Make the launchable target error more detailed

- xcodeproj/internal/top_level_targets.bzl
- Wraps `getattr` result with `list()` for when getting `extensions`.
- Logic below assumes `extension_targets` is mutable.
- When both `extensions` and `extension` are present, it fails with `attempting to change a frozen list`.
> Make mutable copy of extensions when processing top-level target

- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/output_files.bzl
- xcodeproj/internal/top_level_targets.bzl
Fixes #2691.
Though, don’t transitively build them (top-level targets will implicitly do that).
This ensures that non-Swift library targets compile when built directly in Xcode.
> Build static library for library targets in Xcode

- tools/generators/lib/PBXProj/src/ConsumeArgs.swift
- tools/generators/pbxtargetdependencies/src/Generator/ConsolidationMapArguments.swift
In `target_build_settings` we won’t have a `URL`, so we now allow that to be `nil`. To improve the error message, we now also pass in a name.
> Adjust `consumeArg()` to support more use cases

- tools/generators/lib/PBXProj/src/BazelLabel.swift
- tools/generators/lib/PBXProj/test/BazelLabelTests.swift
Porting  61b158cfad7b13961d3185fef58ef9fac3e2e571 to incremental generation mode.
> Favor shorthand form when using labels for Xcode target names in incremental generation mode

- tools/generators/lib/PBXProj/src/ReadTargetSwiftDebugSettingsFile.swift
- tools/generators/lib/PBXProj/src/String+Extensions.swift
- tools/generators/lib/PBXProj/src/TargetSwiftDebugSettings.swift
- tools/generators/lib/PBXProj/src/WriteTargetSwiftDebugSettings.swift
- tools/generators/lib/PBXProj/test/TargetSwiftDebugSettingsTests.swift
This will be used by `target_build_settings` and `swift_debug_settings`.
> Add `TargetSwiftDebugSettings` to `PBXProj`

- examples/integration/WORKSPACE
- examples/integration/WORKSPACE.bzlmod
Fixes a new Bazel HEAD requirement.
> Use a label for `new_local_repository.build_file`

- docs/BUILD
I don’t believe this is required anymore.
> Remove `no-sandbox` from `stardoc` targets

- CODEOWNERS
This can impact the release archive in subtle ways.
> Add `.bazelignore` to `CODEOWNERS`

- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb_targets_spec.json
- xcodeproj.bazelrc
We already have it in `examples/integration` for fixture coverage.
> Remove global `--define=apple.experimental.tree_artifact_outputs=0`

- shared.bazelrc
We no longer have `generator` fixtures.
> Adjust `--deleted_packages`

- xcodeproj/internal/xcodeproj_legacy_aspect.bzl
- xcodeproj/internal/xcodeprojinfos.bzl
Besides some code cleanup, this will allow a future change to move `XcodeProjInfo` into a `xcodeprojinfo.bzl` file.
> Factor `create_xcodeprojinfo` into a Starlark module

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/linker_input_files.bzl
This attributes are used outside of the `compilation_providers` module.
> Rename some `compilation_providers` attributes

- xcodeproj/internal/legacy_xcodeprojinfos.bzl
- xcodeproj/internal/xcodeproj_legacy_aspect.bzl
In preparation of incremental generation mode.
> Rename `xcodeprojinfos` to `legacy_xcodeprojinfos`

- xcodeproj/internal/app_icons.bzl
- xcodeproj/internal/automatic_target_info.bzl
- xcodeproj/internal/build_settings.bzl
- xcodeproj/internal/info_plists.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/legacy_xcodeprojinfos.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/output_files.bzl
- xcodeproj/internal/resource_target.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/unsupported_targets.bzl
- xcodeproj/internal/xcodeproj_legacy_aspect.bzl
End goal is to remove use of `ctx`.
> Pass `rule_attr` and `rule_kind` instead of accessing `ctx`

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/legacy_xcodeprojinfos.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/unsupported_targets.bzl
> Split `compilation_providers` return in two

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/linker_input_files.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/unsupported_targets.bzl
`is_top_level` can be passed into `linker_input_files.collect`. `is_xcode_library_target` isn’t needed.
> Simplify `target_compilation_providers`

- docs/bazel.md
- test/internal/pbxproj_partials/write_pbxtargetdependencies_tests.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/legacy_target_properties.bzl
- xcodeproj/internal/legacy_xcodeprojinfos.bzl
- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/pbxproj_partials.bzl
- xcodeproj/internal/processed_target.bzl
- xcodeproj/internal/resource_target.bzl
- xcodeproj/internal/top_level_targets.bzl
- xcodeproj/internal/unsupported_targets.bzl
- xcodeproj/internal/xcode_targets.bzl
- xcodeproj/internal/xcodeprojinfo.bzl
Less confusing since `transitive_dependencies` also exists.
Also rename `target_properties.bzl` to `legacy_target_properties.bzl`, in preparation of incremental generation mode.
> Rename `dependencies` to `direct_dependencies`

- xcodeproj/internal/library_targets.bzl
- xcodeproj/internal/product.bzl
- xcodeproj/internal/resource_target.bzl
- xcodeproj/internal/top_level_targets.bzl
This is a step closer to being able to co-exist with incremental generation mode code.
> Clean up `products.bzl`

- xcodeproj/internal/compilation_providers.bzl
- xcodeproj/internal/input_files.bzl
- xcodeproj/internal/legacy_xcodeprojinfos.bzl
- xcodeproj/internal/top_level_targets.bzl
Allows for some retained memory reduction. This is mainly going to be leveraged by incremental generation mode, but we get a small benefit now for test targets.
> Conditionally propagate `compilation_providers`

- tools/generators/pbxproj_prefix/src/Generator/BazelDependenciesPartial.swift
- tools/generators/pbxproj_prefix/test/BazelDependenciesPartialTests.swift
Non-generated source file tracking is only needed for BwX mode, which incremental generation mode doesn’t support.
> Remove `external.xcfilelist` from incremental generation

- shared.bazelrc
No longer available in Bazel 8.
> Remove `--experimental_strict_conflict_checks`

- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_targets_spec.json
- examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwx_targets_spec.json
- test/internal/target/process_top_level_properties_tests.bzl
- xcodeproj/internal/bazel_integration_files/copy_outputs.sh
- xcodeproj/internal/product.bzl
- xcodeproj/internal/resource_target.bzl
- xcodeproj/internal/top_level_targets.bzl
Part of #2641.
This gets us most of the way to fixing Xcode Previews when not using tree artifacts. The last thing needed is adding these products to an output group for Xcode previews, otherwise unfocused frameworks aren’t extracted.
> Extract bundles in Bazel instead of `copy_outputs.sh`

- xcodeproj/internal/input_files.bzl
I’m not sure if this really affects anything, but noticed it while working on incremental generation.
> Use correct transitive deps in `resource_bundle_labels`

- tools/generators/xcschemes/src/Generator/CreateAutomaticSchemeInfo.swift
- tools/generators/xcschemes/src/Generator/CreateAutomaticSchemeInfos.swift
- tools/generators/xcschemes/src/Generator/CreateCustomSchemeInfos.swift
> Remove `default` cases for `PBXProductType` handling

- test/internal/xcschemes/info_constructors_tests.bzl
- test/internal/xcschemes/infos_from_json_tests.bzl
- test/internal/xcschemes/utils.bzl
- test/internal/xcschemes/write_schemes_tests.bzl
- tools/generators/lib/XCScheme/src/CreateLaunchAction.swift
- tools/generators/lib/XCScheme/src/CreateProfileAction.swift
- tools/generators/lib/XCScheme/src/Runnable.swift
- tools/generators/lib/XCScheme/test/CreateLaunchActionTests.swift
- tools/generators/lib/XCScheme/test/CreateProfileActionTests.swift
- tools/generators/xcschemes/src/Generator/CreateAutomaticSchemeInfo.swift
- tools/generators/xcschemes/src/Generator/CreateCustomSchemeInfos.swift
- tools/generators/xcschemes/src/Generator/CreateScheme.swift
- tools/generators/xcschemes/src/Generator/SchemeInfo.swift
- tools/generators/xcschemes/test/CreateAutomaticSchemeInfoTests.swift
- xcodeproj/internal/xcschemes/xcscheme_infos.bzl
- xcodeproj/internal/xcschemes/xcscheme_labels.bzl
- xcodeproj/internal/xcschemes/xcschemes.bzl
- xcodeproj/internal/xcschemes/xcschemes_execution.bzl
Adds a new `xcschemes.launch_path` API for creating an Xcode `PathRunnable`. A `launch_path` is different than a `launch_target` because it does not need to be a product within the Bazel workspace. It can be used to launch pre-built binaries, applications, etc. while debugging in Xcode.
Closes #2783
> Add support for PathRunnable in schemes

- buildbuddy.yaml
Now that Bazel 7 is released, we need new jobs to cover Bazel 6.
> Add “Previous LTS” CI jobs

- xcodeproj/internal/pbxproj_partials.bzl
While refactoring some of the incremental generation stuff these flags stopped existing.
> Remove unused constants

- docs/usage.md
- xcodeproj/internal/templates/installer.sh
- xcodeproj/internal/templates/runner.sh
There aren’t specs to collect in incremental generation mode. Also, the usefulness of this feature has drastically declined; there’s usually better ways to debug issues.
> Remove `--collect_specs` support

- xcodeproj/internal/legacy_xcode_targets.bzl
- xcodeproj/internal/processed_targets/legacy_library_targets.bzl
- xcodeproj/internal/processed_targets/legacy_top_level_targets.bzl
- xcodeproj/internal/product.bzl
- xcodeproj/internal/resource_target.bzl
- xcodeproj/internal/xcodeproj_legacy_rule.bzl
In preparation of incremental generation mode.
> Rename `xcode_targets` to `legacy_xcode_targets`

- tools/generators/pbxtargetdependencies/src/Generator/CreateTargetAttributesContent.swift
- tools/generators/pbxtargetdependencies/src/Generator/CreateTargetAttributesObjects.swift
- tools/generators/pbxtargetdependencies/test/Generator/CreateTargetAttributesContentTests.swift
- tools/generators/pbxtargetdependencies/test/Generator/CreateTargetAttributesObject+Testing.swift
- tools/generators/pbxtargetdependencies/test/Generator/CreateTargetAttributesObjectsTests.swift
> Stop setting a comment with `TestTargetID`

- tools/generators/lib/PBXProj/src/Identifiers.swift
- tools/generators/pbxtargetdependencies/src/Generator/CreateTargetAttributesObjects.swift
- tools/generators/pbxtargetdependencies/test/Generator/CreateTargetAttributesObjectsTests.swift
> Stop setting a comment for `TargetAttributes` keys

- xcodeproj/internal/templates/incremental_installer.sh
A last minute refactor broke it for initial installs.
> Fix incremental installer

- examples/rules_ios/.bazelversion
Until rules_ios supports Bazel 7+.
> Use Bazel 6.4.0 with `examples/rules_ios`

- test/update_all_fixtures.sh
This ensures that we continue to update the BwX version of `examples/integration`.
> Use Bazel 6.4.0 when updating fixtures

- bazel_6.bazelrc
- shared.bazelrc
We don’t need it anymore with Bazel 7+.
> Move `--crosstool_top` setting to `bazel_6.bazelrc`

- tools/generators/files_and_groups/src/ElementCreator/CreateFileElement.swift
We handle core data stuff in a different path.
> Remove `xcdatamodel` from incremental generation `folderTypeFileExtensions`

- tools/generators/pbxnativetargets/src/Generator/CalculateSharedBuildSettings.swift
- tools/generators/pbxnativetargets/test/Generator/CalculateSharedBuildSettingsTests.swift
Fixes #2848.
UI test require codesigning to enable debugging.
> Codesign UI tests in incremental generation mode

- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- examples/rules_ios/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
- xcodeproj/internal/templates/xcodeproj.bazelrc
Projects with large C/C++ target command-lines can fail to generate due without using params files. While the targets themselves might use params files, currently `Action.args` won't unless `--experimental_use_cpp_compile_action_args_params_file` is set.
https://github.com/bazelbuild/bazel/issues/20746 would allow us to remove the need for this flag.
> Add `--experimental_use_cpp_compile_action_args_params_file` to baseline `xcodeproj.bazelrc`

- xcodeproj/internal/pbxproj_partials.bzl
- xcodeproj/internal/xcodeproj_incremental_rule.bzl
Source files are tracked as build files by Xcode, so building targets that directly use generated source files will fail the first time they are built if we don't track them.
> Track generated source files in incremental generation mode

- tools/import_indexstores/ImportIndexstores.swift
- tools/import_indexstores/SubProcess.swift
Because of a known issue with `url.allLines`, if the file doesn’t exist the stream hangs. We now correctly report an error instead of hanging when that happens.
This change also includes a silence to the `kill: 69492: No such process` outputs in the logs.
> Fix hang in `import_indexstores`

- bazel_8.bazelrc
Works around the flag flipping at HEAD, until rules_apple and rules_swift are updated.
> Set `--noincompatible_objc_provider_remove_linking_info` for now

- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
- xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh
- xcodeproj/internal/files/incremental_input_files.bzl
- xcodeproj/internal/files/incremental_output_files.bzl
- xcodeproj/internal/files/incremental_resources.bzl
- xcodeproj/internal/processed_targets/incremental_library_targets.bzl
- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
Fixes #2852.
This is a pretty big shift away from how we used to do it.
With the baggage of BwX mode gone we don’t have to track generated files in the same way. After removing that tracking we can depend on building the product for each target (i.e. the `bp` output group) to transitive generate all files needed to compile that target.
In a BwtB world though we need to make sure we still download all of those inputs, which is where `--experimental_remote_download_regex` comes in. I’ve added all of the file types that I currently know of to the regex, but it’s brittle and may require more from the user. The flag supports multiple uses, so a user can fix this on their own as well.
There are four main benefits with this new way (which is good, because the above is a pretty big downside):
1. …
> Depend on `--experimental_remote_download_regex` for Index Build input collection in incremental generation mode

- docs/bazel.md
- test/internal/xcschemes/info_constructors_tests.bzl
- test/internal/xcschemes/infos_from_json_tests.bzl
- test/internal/xcschemes/utils.bzl
- tools/generators/lib/XCScheme/test/CreateLaunchActionTests.swift
- tools/generators/lib/XCScheme/test/CreateProfileActionTests.swift
- tools/generators/xcschemes/src/Generator/CreateCustomSchemeInfos.swift
- tools/generators/xcschemes/src/Generator/CreateScheme.swift
- tools/generators/xcschemes/src/Generator/SchemeInfo.swift
- xcodeproj/internal/xcschemes/xcscheme_infos.bzl
- xcodeproj/internal/xcschemes/xcscheme_labels.bzl
- xcodeproj/internal/xcschemes/xcschemes.bzl
- xcodeproj/internal/xcschemes/xcschemes_execution.bzl
Follow up to #2785 which added `launch_path`. After using this more I realized we can also support `pre`/`post` actions for this attribute.
> Support pre/post actions with `launch_path`

- tools/generators/files_and_groups/src/ElementCreator/CreateFileElement.swift
- tools/generators/files_and_groups/src/ElementCreator/CreateLocalizedFileElement.swift
This was a noticeable hotspot in a real world large project.
> Generate file elements without `.joined()`

- tools/generators/files_and_groups/src/ElementCreator/ElementCreatorCalculatePartial.swift
- tools/generators/files_and_groups/test/ElementCreator/ElementCreatorCalculatePartialTests.swift
Maybe not now, but definitely in the future because of async changes, the order can be non-deterministic. The sorting doesn't have a large cost here either.
> Sort objects in elements partial

- tools/generators/files_and_groups/src/Generator/CalculateTargetFilesPartial.swift
- tools/generators/files_and_groups/test/Generator/CalculateTargetFilesPartialTests.swift
The order can be non-deterministic because of concurrency. The sorting doesn't have a large cost here either.
> Sort build files objects

- buildbuddy.yaml
`latest-1` resolves to 7.0.0 instead of 6.4.0 for some reason, so we now use the `MAJOR.x` flavor instead.
> Use better version specification

- MODULE.bazel
This version is needed by rules_swift, so we might as well upgrade as well.
> Upgrade bazel_features to 1.3.0

- xcodeproj/internal/processed_targets/legacy_library_targets.bzl
- xcodeproj/internal/processed_targets/legacy_top_level_targets.bzl
Apple no longer accepts bitcode and the newest Bazel and rules_apple don’t either.
> Remove bitcode support

- bazel_8.bazelrc
Not a valid option at HEAD, and no longer needed.
> Remove `--noincompatible_objc_provider_remove_linking_info`

- xcodeproj/internal/templates/bazel_build.sh
This can be useful to know where stuck builds get stuck at, since it could be in `calculate_output_groups.py`, a `tools/bazel` wrapper, or in `bazel` itself.
> Log when the Bazel build is starting

- examples/integration/iOSApp/Source/BUILD
- examples/integration/iOSApp/Source/localizable.bzl
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
- examples/integration/test/fixtures/bwb_targets_spec.json
- tools/generators/lib/PBXProj/src/ConsumeArgs.swift
- tools/generators/pbxnativetargets/src/Generator/TargetArguments.swift
- xcodeproj/internal/pbxproj_partials.bzl
Fixes #2904.
We fix our handling by using a null-character terminator instead of encoding the number of paths. This is because at analysis time we can’t rely on the number of elements in a `depset`, as they might expand to more elements at execution if any of the elements are tree artifacts.
Added an example by Wiley that exercises the previous failure case.
> Fix tree artifact `File` handling in incremental generation

- MODULE.bazel
- examples/integration/MODULE.bazel
- xcodeproj/repositories.bzl
This fixes Bazel head compatibility as `apple_cc_toolchain` was removed.
> Upgrade WORKSPACE macro and dev rules_apple & apple_support version

- xcodeproj/internal/build_settings.bzl
The rules_swift PR with the new swift_proto_library rule just merged:
[https://github.com/bazelbuild/rules_swift/pull/1140](https://github.com/bazelbuild/rules_swift/pull/1140)
The provider for the new rules is backwards compatible, but now users of the rule can define their own module names,
or if they don't, the name is derived from the swift proto library target, not the proto library target, because multiple proto libraries can now be compiled into a single swift proto library.
rules_xcodeproj has logic to attempt to derive this module name which will be wrong for the new rules. This PR adds a couple of lines to read the module name from the SwiftProtoInfo if it was set. The new rules would actually have worked without this if the module_name attribute was set because of the earlier …
> Implement support for new swift_proto_library rule

- tools/generators/pbxnativetargets/src/Generator/TargetArguments.swift
- xcodeproj/internal/files/incremental_input_files.bzl
- xcodeproj/internal/incremental_xcode_targets.bzl
- xcodeproj/internal/pbxproj_partials.bzl
- xcodeproj/internal/xcodeproj_incremental_rule.bzl
With incremental generation we only support BwB mode, so there doesn’t need to be a distinction between resources and extra files. In a follow-up change I’ll do a similar thing for `resource_folders` (by making a new `extra_folders` attribute). This reduces the number of arguments sent to `pbxnativetargets`, since only `srcs` and `non_arc_srcs` were actually read there.
> Roll incremental generation mode `resources` into `extra_files`

- tools/generators/pbxnativetargets/src/Generator/CreateXcodeConfigurations.swift
Specifically when using the `apple.skip_codesign_simulator_bundles` feature.
> Fix more code signing of UI tests with incremental generation

- examples/rules_ios/iOSApp/Source/AssetsPrecompiled.xcassets/Contents.json
- examples/rules_ios/iOSApp/Source/AssetsPrecompiled.xcassets/PrecompiledAccentColor.colorset/Contents.json
- examples/rules_ios/iOSApp/Source/BUILD
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb_project_spec.json
Related to #2914.
This diff adds a `precompiled_apple_resource_bundle` to the rules_ios example.
> Add precompiled_apple_resource_bundle in rules_ios example

- test/internal/pbxproj_partials/write_target_build_settings_tests.bzl
- tools/generators/pbxnativetargets/src/Generator/CreateXcodeConfigurations.swift
- tools/generators/target_build_settings/src/Generator/ProcessArgs.swift
- xcodeproj/internal/pbxproj_partials.bzl
- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
This seems to be a remnant from when incremental generation mode was going to support BwX mode. Now we default to not signing, and this additional logic isn’t needed and is error prone.
> Remove incremental generation mode extra `CODE_SIGNING_ALLOWED` logic

- bazel_6.bazelrc
- shared.bazelrc
> Set `--experimental_action_cache_store_output_metadata` only with Bazel 6

- tools/generators/files_and_groups/src/ElementCreator/CreateFileElement.swift
- tools/generators/files_and_groups/src/Xcode.swift
- tools/generators/files_and_groups/test/ElementCreator/CreateFileElementTests.swift
BUILD.bazel and .bzl files are not being recognized as a text.script.python in Xcode when using the incremental generator.
Replacing lastKnownFileType with explicitFileType for these extensions fixed the issue.
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/7773955/7cc23b81-5a24-42d0-92f1-bf4241199ad5)  | ![image](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/7773955/2eb3e4ec-1f6f-4467-9591-726122db67bc) |
> Set `explicitFileType` for bazel and bzl extensions

- xcodeproj/internal/templates/runner.sh
Since bazelisk only supports one path for the wrapper script, and `BAZELISK_SKIP_WRAPPER` is only set when the wrapper script is used, we currently can safely default this value.
> Work around when bazelisk is called recursively during project generation

- xcodeproj/internal/bazel_integration_files/calculate_output_groups.py
This ensures that the `newest 'buildRequest.json' file updated after X seconds.` displays before a potentially slow other operation in the script.
> Flush timing output from `calculate_output_groups.py`

- docs/usage.md
- xcodeproj/internal/templates/runner.sh
Also fixes the regex used to match what we changed `build_build.sh` to use.
This is to optimize bandwidth usage of cache warming calls.
> Stop setting `--experimental_remote_download_regex` by default with command-line API

- examples/integration/BUILD
Platform mappings aren't required anymore from what I remember
> Update cache warm example comment

- xcodeproj/internal/bazel_integration_files/copy_outputs.sh
It appears that the `TARGET_DEVICE_PLATFORM_NAME` check didn't account for `iphonesimulator` platform name which was causing unit tests running on a test host to not reflect changes made in source code.
> Remove `TARGET_DEVICE_PLATFORM_NAME` matching from `Info.plist` touching

- docs/bazel.md
- test/internal/xcschemes/info_constructors_tests.bzl
- test/internal/xcschemes/infos_from_json_tests.bzl
- test/internal/xcschemes/utils.bzl
- test/internal/xcschemes/write_schemes_tests.bzl
- tools/BUILD
- tools/generators/lib/XCScheme/src/CommandLineArguments.swift
- tools/generators/lib/XCScheme/src/CreateTestAction.swift
- tools/generators/lib/XCScheme/src/EnvironmentVariables.swift
- tools/generators/lib/XCScheme/test/CreateLaunchActionTests.swift
- tools/generators/lib/XCScheme/test/CreateProfileActionTests.swift
- tools/generators/lib/XCScheme/test/CreateTestActionTests.swift
- tools/generators/xcschemes/src/Generator/CreateAutomaticSchemeInfo.swift
- tools/generators/xcschemes/src/Generator/CreateCustomSchemeInfos.swift
- tools/generators/xcschemes/src/Generator/CreateScheme.swift
- tools/generators/xcschemes/src/Generator/SchemeInfo.swift
- tools/generators/xcschemes/test/CreateAutomaticSchemeInfoTests.swift
- tools/generators/xcschemes/test/CreateAutomaticSchemeInfosTests.swift
- xcodeproj/internal/xcschemes/xcscheme_infos.bzl
- xcodeproj/internal/xcschemes/xcschemes.bzl
- xcodeproj/internal/xcschemes/xcschemes_execution.bzl
This allows having multiple arguments under a single checkbox in Xcode.
Also changes `enabled` and `skipped` to `isEnabled` and `isSkipped` to match Swift API naming guidelines.
> Add `literal_string` arg to `xcschemes.arg`

- xcodeproj/internal/incremental_xcodeprojinfos.bzl
Regressed with 6f65b40b1c04fc6aa0e8910e8d1597954de95777.
> Fix xcscheme generation when using test suites

- xcodeproj/internal/logging.bzl
- xcodeproj/repositories.bzl
Matches what Bazel does: https://github.com/bazelbuild/bazel/blob/c031fab778ea1c5df2101c20521aec7c9cd9c02b/src/main/java/com/google/devtools/build/lib/runtime/UiEventHandler.java#L506-L508
> Make Starlark warnings not bold

- tools/BUILD
- tools/unique_directories/BUILD
- tools/unique_directories/unique_directories.py
- xcodeproj/internal/files/incremental_input_files.bzl
- xcodeproj/internal/incremental_xcode_targets.bzl
- xcodeproj/internal/pbxproj_partials.bzl
- xcodeproj/internal/templates/incremental_installer.sh
- xcodeproj/internal/xcodeproj_incremental_rule.bzl
A couple of optimizations:
- We create the list of generated directories with Bazel, allowing it to be cached
- The generated directories are the unique leaf directories, no longer including any intermediate parent directories. This is accomplished using a trie.
> Reduce work that incremental generation mode installer does for generated directories

- xcodeproj/internal/incremental_xcodeprojinfos.bzl
Per the docs on `should_generate`, it should only be used if `is_supported`.
> Properly calculate unsupported `is_focused`

- xcodeproj/internal/files/incremental_input_files.bzl
Besides for being more memory efficient, this actually fixes an edge case where before some extra files were added for unfocused unsupported targets (e.g. a modulemap like rule that is referenced in a categorized attribute).
In the future we should probably rethink the “uncategorized files become extra files if the target is listed in a categorized attribute downstream” logic. I believe it was originally to show inputs of custom code gen rules, but I think that can be handled differently.
> Stop collecting uncategorized files for unfocused targets

- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
1. Removes a use of `XcodeProjAutomaticTargetProcessingInfo.infoplists`
2. Uses the merged version, which can work around issues when people list multiple files in `infoplists
3. Pre-creates some `Info.plist` files, so the scheme icon and editor starts working sooner
> Use adjusted `Info.plist` for `extension_infoplists` in incremental generation mode

- xcodeproj/internal/automatic_target_info.bzl
`collect_uncategorized_files` is determined by the type of rule, not related to if we should create an Xcode target. Related, we should rename `is_supported` to `can_generate_xcode_target` or something in a future change.
> Stop collecting uncategorized files for source-less library targets

- xcodeproj/internal/incremental_xcodeprojinfos.bzl
We never want to include tool targets in the generated project.
> Skip processing `exec` configuration targets in incremental generation mode

- xcodeproj/internal/automatic_target_info.bzl
We collect these in legacy generation mode.
> Collect `codesign_inputs` as extra files in incremental generation mode

- xcodeproj/internal/files/incremental_input_files.bzl
I forgot that `categorized_files` was itself a `dict`…
> Reuse `categorized_files` instead of creating a new `exclude_headers` `dict`

- xcodeproj/internal/files/incremental_input_files.bzl
- xcodeproj/internal/processed_targets/incremental_library_targets.bzl
- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
This ensures that if an attribute is listed both in `XcodeProjAutomaticTargetProcessingInfo.extra_files` and another attribute, the other one takes precedence.
Also removes the `if id` check, since this flow will always have a non-`None` `id`.
> Adjust order of `file_handlers` registration in incremental generation mode

- xcodeproj/internal/xcodeproj_macro.bzl
Missed in 0c3ad2bcddd84c91e7b61546918e08810de04a4f.
> Make `build_mode = "bazel"` when set to `None` or `""`

- test/internal/xcschemes/write_schemes_tests.bzl
- xcodeproj/internal/xcschemes/xcschemes_execution.bzl
Fixes #2990.
Including the test host can break some people’s workflows (e.g. a test host that is set to only compile for a certain target environment). Also, the test host is implicitly included in the scheme at the right action.
Other transitive dependencies are still built in the wrong action. In a future change we need to have test-based targets have their transitive dependencies listed under the test action, not run.
> Stop including test hosts in schemes when `adjust_schemes_for_swiftui_previews = True`

- test/internal/xcschemes/infos_from_json_tests.bzl
- xcodeproj/internal/xcschemes/xcscheme_infos.bzl
The `launch_path` does not have an `extension_host` attr
> Fix don't attempt to get extension_host for launch_path

- tools/generators/xcschemes/src/Generator/CreateAutomaticSchemeInfo.swift
- tools/generators/xcschemes/src/Generator/CreateCustomSchemeInfos.swift
- tools/generators/xcschemes/src/Generator/CreateScheme.swift
- tools/generators/xcschemes/src/Generator/SchemeInfo.swift
- tools/generators/xcschemes/test/CreateAutomaticSchemeInfoTests.swift
- tools/generators/xcschemes/test/SchemeInfo+Testing.swift
This means that if a target is listed as a Profile action, its `transitivePreviewReferences` will also be Profile actions.
> Set the correct actions for `transitivePreviewReferences`

- MODULE.bazel
This improves the error experience for Bzlmod users using something less than Bazel 6.3.0.
> Add `module.bazel_compatibility` to reflect our minimum supported Bazel version

- bazel_8.bazelrc
It no longer exists at Bazel HEAD.
> Remove `--noincompatible_struct_has_no_methods`

- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
> Fix missing `BAZEL_PACKAGE_BIN_DIR` for non-Swift targets in incremental generstion mode

- docs/bazel.md
- xcodeproj/internal/xcschemes/xcschemes.bzl
While going through the documentation, I noticed two missing \` characters. This pull request adds the missing \` characters and fixes the markdown highlighting for those values.
> Fix markdown highlighting in xcschemes.diagnostics descriptions

- examples/integration/iOSApp/BUILD
- examples/integration/iOSApp/info.yaml
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/integration/test/fixtures/generated/xcodeproj_bwb/BUILD
- examples/integration/xcodeproj_targets.bzl
- xcodeproj/internal/xcodeproj_incremental_rule.bzl
Fixes #3009. Closes #3010.
Also added an example.
> Fix handling of multiple `associated_extra_files` per target in incremental generation mode

- tools/generators/pbxnativetargets/src/Generator/CalculateSharedBuildSettings.swift
- tools/generators/pbxnativetargets/src/Generator/CreateXcodeConfigurations.swift
- tools/generators/pbxnativetargets/test/Generator/CalculateSharedBuildSettingsTests.swift
Fixes #2979.
Xcode has a bug where if we don't include device platforms in app extension targets, then it will fail to install the hosting application.
> Expand `SUPPORTED_PLATFORMS` for application extensions

- xcodeproj/internal/automatic_target_info.bzl
This allows us to collect the headers in `extra_files`, and potentially remove `CcInfo` based header collection altogether.
> Explicitly handle `{cc,objc}_import` rules

- xcodeproj/internal/automatic_target_info.bzl
This is needed in order to adjust our `CcInfo` header collection logic in a future change.
> Collect more “headers” in `extra_files`

- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
Add the `--keep_going` flag to builds when the "Continue building after errors" flag is set. Maybe there's a better place to add this, but I think it would be nice to respect the setting in the IDE.
> Respect "Continue building after errors" setting

- examples/integration/test/fixtures/generated/xcodeproj_bwb/BUILD
- examples/integration/xcodeproj_targets.bzl
- xcodeproj/internal/xcodeproj_incremental_rule.bzl
- xcodeproj/internal/xcodeproj_legacy_rule.bzl
- xcodeproj/internal/xcodeproj_macro.bzl
Fixes #3021.
We fake a `labed_keyed_list_dict` by JSON encoding the list into a string and use `label_keyed_string_dict`.
> Fix `associated_extra_files` when multiple targets own the same file

- tools/import_indexstores/ImportIndexstores.swift
Remapping of external sources in the index is done by replacing the path with `xcodeOutputBase`, which is built by removing paths from `xcodeExecutionRoot`. However, when `split()` is called, the leading `/` from `xcodeExecutionRoot` is lost, which was causing `index-import` to not translate these files correctly.
> Fix mistranslation of external sources

- buildbuddy.yaml
There are at least two issues causing CI to be 🔴 atm:
1. [See example](https://mnf.buildbuddy.io/invocation/92c4f0ed-72f3-4cf7-a941-43ae28448acb?target=%2F%2FLib%3Agen_Lib.swift&targetStatus=3#@1). Repro:
```sh
cd examples/integration
bazel clean && USE_BAZEL_VERSION=last_green bazel build //Lib:gen_Lib.swift
```
2. [See example](https://mnf.buildbuddy.io/invocation/f51fedc6-8204-4707-8954-a1ea1f40bf35#@191). Repro:
```sh
bazel clean && USE_BAZEL_VERSION=last_green bazel build //test/internal/bazel_labels:normalize_tests_test_2
```
I confirmed that https://github.com/bazelbuild/bazel/commit/dd2464a5933e0a5a6765024573832717b71989bf is the last commit that does not hit the issues above. Commit https://github.com/bazelbuild/bazel/commit/3fddc7f38ace43981d839ed4558b8a457caf41fb is the first …
> Force `USE_BAZEL_VERSION` to working SHA until last_green is fixed

- test/update_all_fixtures.sh
Similar to: https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/3029
Currently the `./test/update_all_fixtures.sh` script is failing with error (in `main`):
```sh
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@@rules_apple~//apple/internal:environment_plist_macos, config=BuildConfigurationKey[b9d3bb9e7707500dae32d8b693576ca2a5d5e2f8c0d56fe0957bab54bf751df7]}' (requested by nodes 'ConfiguredTargetKey{label=//GRPC:echo_client, config=BuildConfigurationKey[b9d3bb9e7707500dae32d8b693576ca2a5d5e2f8c0d56fe0957bab54bf751df7]}', 'ConfiguredTargetKey{label=//GRPC:echo_client.merged_infoplist, config=BuildConfigurationKey[b9d3bb9e7707500dae32d8b693576ca2a5d5e2f8c0d56fe09 …
```
> Force bazel_version in `update_all_fixtures.sh` to working SHA

- MODULE.bazel
- examples/rules_ios/MODULE.bazel
- examples/rules_ios/WORKSPACE
Also bump the Stardoc `bazel_skylib` dep to the [first version containing @@bazel_skylib~//lib:modules.bzl](https://github.com/bazelbuild/bazel-skylib/commit/553c08dc60d550b7ec70ba80ecd91b8f6e563877) to fix [this CI failure](https://mnf.buildbuddy.io/invocation/6d48b88b-9c2d-40c4-b1ec-84630ab6585c#@4).
> Bump rules_ios to 4.6.0

- tools/generators/target_build_settings/src/Generator/ProcessSwiftArgs.swift
Incremental project generation mode was not setting swift debug settings when top level target (e.g. ios application) is an Obj-c target. This change should fix the issue. 
Before : lldb > `settings show target.swift-extra-clang-flags` is empty 
After : lldb > `settings show target.swift-extra-clang-flags` is not empty
> Fix incremental project generation swift debugging

- tools/swiftc_stub/main.swift
Xcode 16b3 changed `-v` to `--version` when "discovering" `swiftc`
¯\\_(ツ)\_\/¯
> Support swiftc version invocation used in Xcode 16b3 and greater

- xcodeproj/internal/automatic_target_info.bzl
This currently results in oddly named internal targets, because we can’t read the `SwiftInteropInfo` on the `_clang` target, and because we don’t perform target merging. By implementing target merging for `mixed_language_library` (in a future change) we will sidestep the `SwiftInteropInfo` issue (though it’s still an issue in general we will want to address).
> Add initial support for rules_swift’s `mixed_language_library`

- xcodeproj/internal/files/incremental_output_files.bzl
> Remove `id` from `direct_outputs`

- xcodeproj/repositories.bzl
This dependency has been renamed, and the archive has since been regenerated. Consequently, the new archive contains the new folder prefix.
> xctest-dynamic-overlay → swift-issue-reporting

- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
- xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh
- xcodeproj/internal/templates/runner.sh
Ensures the right files are always downloaded, everywhere.
> Align the various `--experimental_remote_download_regex` flags

- xcodeproj/internal/templates/bazel_build.sh
- xcodeproj/internal/templates/runner.sh
In order for Xcode builds to work with custom environment variables you need to use `xcodeproj.bazel_env`. This just takes the extra step of filtering out all other environment variables, ensuring more analysis cache hits. You can already do this in your own `tools/bazel`, but now people can get the benefit regardless.
This change is needed for shared outputs bases to be performant.
> Filter environment variables when building with Bazel

- xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh
- xcodeproj/internal/templates/bazel_build.sh
No longer needed since we now filter out all environment variables for `bazel build`.
> Stop un-exporting environment variables

- tools/generators/target_build_settings/src/Generator/ProcessSwiftArgs.swift
- xcodeproj/internal/processed_targets/incremental_library_targets.bzl
- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
- xcodeproj/internal/processed_targets/incremental_unsupported_targets.bzl
- xcodeproj/internal/processed_targets/mergeable_infos.bzl
This prevents settings which are specific to a particular Swift module compilation, such as clang module maps in a mixed-language library, from getting accumulated with the public settings. Before this change using `mixed_language_library` would result in module redefinition errors in lldb.
I’m not sure if this has a chance of not setting some flags that would need to be set. In local testing everything worked, but as with all things lldb, wider user testing is needed. Ideally long term we can use serialized debug info instead (and/or explicit modules).
**Note:** For this to work the best, the single dep of a top-level target needs to be a `swift_library` or `mixed_language_target`. This change might result in lldb regressions for custom setups that don't meet that requirement.
> Use only the debug settings from the most-downstream Swift target

- xcodeproj/internal/templates/bazel_build.sh
- xcodeproj/internal/templates/runner.sh
Needed for ssh-based git operations.
> Pass through `SSH_AUTH_SOCK` to Bazel

- xcodeproj/internal/files/incremental_input_files.bzl
- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
Without this change, unfocused `*_framework` targets would have their outputs shown as generated inputs in the project.
> Fix unfocused framework target input files filtering

- tools/generators/files_and_groups/src/Generator/ReadFilePathsFile.swift
- xcodeproj/internal/files/incremental_resources.bzl
- xcodeproj/internal/incremental_xcode_targets.bzl
This effectively adds support for the `apple_precompiled_resource_bundle` rule, which extensively uses the `processed` resource type.
This is only supported by the incremental generation mode.
> Add proper support for the `processed` resource type

- xcodeproj/internal/files/incremental_resources.bzl
The current way matches how Xcode bundles structured resources, and we did it this way for BwX mode. But representing these resources as folders has a few downsides:
1. More files can appear in Xcode than are actually referenced as inputs, because Bazel works on the level of files, not directories
2. The work to translate the files to folder paths isn’t free
3. The translation of files to folder paths broke with rules_apple’s recent runfiles support
In a future change I’ll remove all of the code around `.isFolder`, since folder-type files can go down the `file_path` path.
> Represent structured resources as files instead of folders in Xcode

- MODULE.bazel
- xcodeproj/internal/incremental_xcodeprojinfos.bzl
- xcodeproj/internal/legacy_xcodeprojinfos.bzl
Fixes #3056
This PR implements a gap introduced when bazelbuild/rules_apple#2476 was introduced, where expandable env settings on test rules would not be expanded into the xcscheme during generation. There are a couple of things that reviewers should be aware of before proceeding with this change:
- This change is not considerate of the rules_apple being used, meaning that it assumes the developer is using at least version [3.6.0](https://github.com/bazelbuild/rules_apple/releases/tag/3.6.0) (when the breaking changes in #2476 were introduced). This is not good and should be considered a blocker, but I don't know how to address this with the tools offered by the ruleset or Bazel.
- This change as-implemented requires regeneration of the xcschemes if the configured value of the "Make" …
> Expand "Make" variables inside of values in the env dictionary on test rules

- examples/integration/ExtensionKitExtension/Info.plist
Need a valid `EXExtensionPointIdentifier` to install the app.
> Fix ExtensionKit example

- test/internal/xcschemes/infos_from_json_tests.bzl
- xcodeproj/internal/xcschemes/xcscheme_infos.bzl
When using custom schemes with "same_as_run" for the profile action, I noticed that the build target's pre/post build actions were being duplicated in the generated scheme because we copy the whole build target into the profile action (incl post_actions and pre_actions).
This just copies the `id` from the build target instead.
> Remove duplicate post/pre actions

- docs/usage.md
- xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
- xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh
- xcodeproj/internal/files/legacy_output_files.bzl
- xcodeproj/internal/templates/runner.sh
This flag in Bazel 7.0 is no longer experimental so you get the following warning:
```
WARNING: Option 'experimental_remote_download_regex' is deprecated: Use --remote_download_regex instead
```
We can update to the non-experimental flag as we now only support Bazel 7+.
> Fix non-experimental remote_download_regex flag

- xcodeproj/internal/files/incremental_output_files.bzl
- xcodeproj/internal/files/legacy_output_files.bzl
- xcodeproj/internal/indexstore_filelists.bzl
Now that we can use `--remote_download_regex` we no longer need the weird hack that `indexstore_filelists.write` was doing to force the indexstores to download. Plus there are times when we don’t want to download the indexstores, like when cache warming on CI.
> Simplify indexstore `.filelist` creation

- xcodeproj/internal/templates/runner.sh
Needed to support building on Linux.
> Don’t require `xcode-select` or `DEVELOPER_DIR` to run

- test/internal/pbxproj_partials/write_target_build_settings_tests.bzl
- xcodeproj/BUILD
- xcodeproj/internal/pbxproj_partials.bzl
- xcodeproj/internal/processed_targets/incremental_library_targets.bzl
- xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
- xcodeproj/internal/processed_targets/mixed_language_library_targets.bzl
- xcodeproj/internal/xcodeproj_incremental_aspect.bzl
Currently needed for generating a project on RBE.
> Optionally allow `WriteTargetBuildSettings` to use remote cache or RBE

- xcodeproj/internal/templates/legacy_installer.sh
- xcodeproj/internal/templates/runner.sh
Regressed in 017297ba0b16b9c1635c06188b69e314e63fe5e9.
> Fix legacy fixture generation

- xcodeproj/internal/bazel_integration_files/copy_dsyms.sh
- xcodeproj/internal/bazel_integration_files/copy_outputs.sh
- xcodeproj/internal/templates/incremental_installer.sh
- xcodeproj/internal/templates/legacy_installer.sh
15.4's `rsync` has a bug that requires the src to have write permissions. We normally shouldn't do this as it modifies the Bazel output base, so we limit this to only macOS 15.4 (as it’s fixed in 15.5).
Also fixes a slight bug in the `patch_dsym` function.
> Fix `rsync` on macOS 15.4

- docs/usage.md
- xcodeproj/compile_only_aspect.bzl
Adds an aspect that can be used to skip actions which are not compilation related. This is useful for warming projects in CI to maintain a Bazel remote cache for users to use. It is also useful when compilation actions are the only thing that need to be validated as it allows skipping potentially longer actions like bundling, signing, etc.
Example usage: `bazel run //:LocalDevCacheWarming_xcodeproj -- 'build --aspects=//:compile_only_aspect.bzl%compile_only_aspect --output_groups=compiles $_GENERATOR_LABEL_'`
> Add `compile_only` aspect

- MODULE.bazel
- examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/integration/test/fixtures/bwb_project_spec.json
- examples/rules_ios/MODULE.bazel
- examples/rules_ios/WORKSPACE
- examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
- examples/rules_ios/test/fixtures/bwb_project_spec.json
- test/internal/pbxproj_partials/write_pbxproj_prefix_tests.bzl
- tools/BUILD
- tools/generators/legacy/src/DTO/Project.swift
- tools/generators/legacy/src/Generator/CreateProject.swift
- tools/generators/legacy/src/Generator/Environment.swift
- tools/generators/legacy/src/Generator/Generator.swift
- tools/generators/legacy/test/CreateProjectTests.swift
- tools/generators/legacy/test/Fixtures.swift
- tools/generators/legacy/test/GeneratorTests.swift
- tools/generators/pbxproj_prefix/README.md
- tools/generators/pbxproj_prefix/src/Generator/Arguments.swift
- tools/generators/pbxproj_prefix/src/Generator/Environment.swift
- tools/generators/pbxproj_prefix/src/Generator/Generator.swift
- tools/generators/pbxproj_prefix/src/Generator/PBXProjectBuildSettings.swift
- tools/generators/pbxproj_prefix/test/PBXProjectBuildSettingsTests.swift
- tools/import_indexstores/ImportIndexstores.swift
- xcodeproj/internal/files/legacy_input_files.bzl
- xcodeproj/internal/files/legacy_output_files.bzl
- xcodeproj/internal/pbxproj_partials.bzl
- xcodeproj/internal/xcodeproj_incremental_rule.bzl
- xcodeproj/internal/xcodeproj_legacy_rule.bzl
- xcodeproj/repositories.bzl
Similar to: https://github.com/bazelbuild/rules_swift/pull/1504
Part of #3160
This PR updates the index-import dependency to include both version 5.8 and 6.1 as the hash algorithm changed in Swift 6.1.
To make this change backwards compatible we switch to the 5.8 version on Xcode 16.2 and under.
> Support index-import on all Xcode 16.x versions

- xcodeproj/compile_only_aspect.bzl
We are running some additional targets which are not Apple / Swift specific but still required and the build was failing since there was no "compiles" output group.
I could add those rules to the list in the aspect definition. However I fear that it would set the bad example and the list would probably grow a lot over time.
> Skip targets without "compiles" output group in compile_only aspect

- xcodeproj/internal/bazel_integration_files/copy_dsyms.sh
- xcodeproj/internal/bazel_integration_files/copy_outputs.sh
- xcodeproj/internal/templates/incremental_installer.sh
- xcodeproj/internal/templates/legacy_installer.sh
This should fix writable permissions issues on all versions of macOS that we support.
> Use `--perms` with `rsync`

- MODULE.bazel
- xcodeproj/repositories.bzl
Update to latest `index-import` version In order to fix [this issue](https://github.com/MobileNativeFoundation/index-import/issues/135) with `libzstd.1.dylib`
```
ERROR: /Users/user.name/development/iOSApp/Sources/ios/SomeDirectory/ModuleName/BUILD.bazel:7:14: Compiling Swift module //Sources/ios/SomeDirectory/ModuleName:ModuleName failed: (Exit 6): worker failed: error executing SwiftCompile command (from target //Sources/ios/SomeDirectory/ModuleName:ModuleName)
(cd /private/var/tmp/_bazel_user.name/6a5e437287601edde41b207a856d8f03/rules_xcodeproj.noindex/build_output_base/execroot/_main && \
exec env - \
APPLE_SDK_PLATFORM=iPhoneSimulator \
APPLE_SDK_VERSION_OVERRIDE=18.4 \
PATH=/bin:/usr/bin \
XCODE_VERSION_OVERRIDE=16.3.0.16E140 \ …
```
> Adopt latest index-import version (v6.1.0.1) to fix issue with libzstd.1.dylib

- tools/generators/swift_debug_settings/src/SwiftDebugSettings.swift
- xcodeproj/internal/pbxproj_partials.bzl
Fix argument length errors by switching WriteSwiftDebugSettings to use a param file when needed.
Previously when generating a very large project with 7000+ targets:
```
ERROR: /private/var/tmp/_bazel_jszumski/399f2da8a1f92cab020446a488e7bec6/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj_generated/generator/tools/rules/xcodeproj/bazel-project/BUILD:12:10: Generating bazel-project.xcodeproj Debug-swift_debug_settings.py failed: (Exit -1): universal_swift_debug_settings failed: error executing WriteSwiftDebugSettings command (from target @@rules_xcodeproj_generated//generator/tools/rules/xcodeproj/bazel-project:bazel-project) 
(cd /private/var/tmp/_bazel_jszumski/399f2da8a1f92cab020446a488e7bec6/rules_xcodeproj.noindex/build_output_base/execroot/register && \
exec env - …
```
> Fix argument length error for WriteSwiftDebugSettings

- xcodeproj/internal/bazel_integration_files/copy_dsyms.sh
- xcodeproj/internal/bazel_integration_files/copy_outputs.sh
- xcodeproj/internal/templates/incremental_installer.sh
- xcodeproj/internal/templates/legacy_installer.sh
This works around an issue in macOS 15.4
> Add homebrew paths to `copy_outputs.sh` rsync call

- bazel_9.bazelrc
- examples/integration/tools/bazel
Needed for Bazel 9, until rules_apple is updated.
> Set `--incompatible_use_default_test_toolchain=no` for now

- xcodeproj/internal/bazel_integration_files/process_bazel_build_log.py
**Background**
- **Issue** : Building from Xcode got slower because bazel server got killed by Xcode Index build SIGINT.  
- We've observed that iOS build performance from Xcode are getting slower over time. It's discovered that even the normal build after no code change was causing building analysis cache from scratch. It was because the bazel server was terminated while running index build and because the analysis cache is saved in memory, bazel server for normal build needs to construct analysis cache from scratch. As a result, every time developers try build action, the analysis cache had to be built from scratch (taking a couple minutes in the beginning). 
- **Hypothesis on cause** : SIGINT sent more than once or even SIGTERM/SIGKILL sent by Xcode
- **Why?** 
- Apple engineer told me …
> Add `SIGINT` handler for `process_bazel_build_log.py`

- xcodeproj/internal/bazel_integration_files/BUILD
- xcodeproj/internal/bazel_integration_files/actions.bzl
- xcodeproj/internal/templates/generate_bazel_dependencies.sh
- xcodeproj/internal/templates/xcodeproj.bazelrc
- xcodeproj/internal/xcodeproj_rule.bzl
- xcodeproj/internal/xcodeproj_runner.bzl
Old way is no longer supported as of Bazel 8.
> Use `--@rules_swift//swift:copt` instead of `--swiftcopt`

- xcodeproj/internal/bazel_integration_files/BUILD
- xcodeproj/internal/bazel_integration_files/copy_outputs.sh
Resolves issues signing tests for execution on device. Adding to original fix: https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/2395
> Add Testing.framework to testing frameworks

- MODULE.bazel
- examples/integration/.bazelrc
- examples/integration/CommandLine/Tests/BUILD
- examples/integration/MODULE.bazel
Couple of fixes as macOS 13.0 is now required for Swift test targets.
> Fix issues building swift_test/macos_unit_test in Bazel

- xcodeproj/internal/templates/bazel_build.sh
Fixes:
```
Error: TOOLCHAINS was set to 'com.apple.dt.toolchain.Metal.32023' but the default toolchain was found, that likely means a matching toolchain isn't installed
```
Apparently `$toolchain` either was never set for Metal toolchains in earlier Xcode versions or Xcode didn't complain when it was set in `action_env`. I tested on Xcode 16 and it was never there while it definitely shows up in Xcode 26 Beta 3.
I think version check may not be needed here at all. If yes, please do let me know what would be suggested way of performing the check. I tried calling `xcodebuild -version` but that seem to randomly fail for some people so I removed it.
> Fix Metal toolchains in Xcode 26 betas

- CHANGELOG.md
- docs/BUILD
- docs/bazel.md
- test/BUILD
- test/internal/xcodeproj_extra_files/BUILD
- test/internal/xcodeproj_extra_files/xcodeproj_extra_files_tests.bzl
- xcodeproj/internal/docs/aspect_hints.bzl
- xcodeproj/internal/docs/bazel.header.md
- xcodeproj/internal/files/input_files.bzl
- xcodeproj/internal/providers.bzl
- xcodeproj/xcodeproj_extra_files.bzl
Create an aspect hint to allow dependencies to propagate up extra files that should be include in the Xcode navigator
> Create xcodeproj_extra_files aspect hint

- docs/usage.md
- xcodeproj/compile_only_aspect.bzl
* Collect `CppCompile`
* Add a new `resources` output group, which will cause the resources that will be bundled to be processed (e.g. asset catalog compiles, `Info.plist` processing, entitlement processing, etc.)
> Improve `compile_only_aspect`

- xcodeproj/compile_only_aspect.bzl
In some cases `AppleResourceInfo` won’t have all of its attributes, so we need to use `getattr`.
> Fix `AppleResourceInfo` value extraction in `compile_only_aspect`

- CHANGELOG.md
- xcodeproj/internal/execution_root.bzl
Fixes https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/3215
> Remove private prefix in execution root path
