MobileNativeFoundation/rules_xcodeproj

xcodeproj/internal/build_settings.bzl
xcodeproj/internal/opts.bzl

This will be used in other functions.

Extract and rename `_set_not_empty()`

---

tools/generator/BUILD
tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/repositories.bzl

It's exercised only through tests right now. I'll be adding piece by piece to this before finally hooking it up in a binary.

Add `PBXProject` creation

---

tools/generator/test/CreateProjectTests.swift
tools/generator/test/GeneratorTests.swift

This is in preperation of adding SwiftLint to the repo.

Apply some formatting changes

---

tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator.swift
tools/generator/src/PBXGroup+Extensions.swift
tools/generator/src/Path+Extensions.swift
tools/generator/src/Sorting.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/Target+Testing.swift

They aren't added to the main group yet.

Create files and groups

---

xcodeproj/repositories.bzl

https://github.com/tuist/XcodeProj/pull/667

Update XcodeProj to fix dictionary compares

---

WORKSPACE
third_party/com_github_pointfreeco_swift_custom_dump/type_name.patch

https://github.com/pointfreeco/swift-custom-dump/pull/43

Fix SwiftDump visited labels

---

xcodeproj/internal/target.bzl

Part of #83.
A test showing this working will come later.

Fix product path detection for cc_binary

---

test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
test/fixtures/ios_app/project.xcodeproj/project.pbxproj
test/fixtures/ios_app/project.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/ios_app/spec.json
tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+WriteXcodeProj.swift
tools/generator/src/Generator.swift
tools/generator/test/AddTargetsTests.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/xcodeproj.bzl

Build generated files in Xcode

---

examples/ios_app/ExampleTests/ExampleTests.swift
examples/ios_app/TestingUtils/Answer.swift.stencil
examples/ios_app/TestingUtils/BUILD
examples/ios_app/TestingUtils/Greeting.swift.stencil
examples/ios_app/Utils/Utils.swift
test/fixtures/ios_app/project.xcodeproj/project.pbxproj
test/fixtures/ios_app/spec.json
xcodeproj/internal/input_files_aspect.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj_aspect.bzl

Part of #100.
This allows for easy editing of the inputs.

Include inputs of generated files in the project

---

test/fixtures/generator/project.xcodeproj/project.pbxproj
test/fixtures/generator/spec.json
test/fixtures/ios_app/spec.json
tools/generator/src/DTO.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/src/Inputs.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/ProcessTargetMergesTests.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/target.bzl

Add support for `non_arc_srcs`

---

test/fixtures/ios_app/project.xcodeproj/project.pbxproj
test/fixtures/ios_app/spec.json
xcodeproj/internal/input_files_aspect.bzl
xcodeproj/internal/target.bzl
xcodeproj/providers.bzl

Part of #100.
We now leverage the `input_files_aspect` aspect to automically find inputs.

Include all input files in the generated project

---

tools/generator/test/Fixtures.swift
xcodeproj/internal/target.bzl

Part of #83.
`cc_binary` and `swift_binary` can specify their own sources. When that happens we don't want to merge any of their library depenedencies into them. We might want to go a step futher and only try to merge for the bundling rules, but we can decide on that at a later time.
Also, instead of erroring out when there are multiple static library dependencies, it just no longer tries to merge that top-level target. Though, if it's a bundling target, we still error.

Don't try to merge with srcs or multiple deps

---

tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Inputs.swift
tools/generator/src/PBXProductType+Extensions.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/ProcessTargetMergesTests.swift
xcodeproj/internal/input_files_aspect.bzl
xcodeproj/internal/target.bzl
xcodeproj/providers.bzl

Add initial support for `hdrs` and `textual_hds`

---

examples/cc/BUILD
examples/cc/lib/BUILD
examples/cc/lib/lib.c
examples/cc/lib/lib.h
examples/cc/lib/private.h
examples/cc/tool/BUILD
examples/cc/tool/main.c
examples/cc/xcodeproj_targets.bzl
test/fixtures/BUILD
test/fixtures/cc/BUILD
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/project.xcodeproj/project.xcworkspace/contents.xcworkspacedata
test/fixtures/cc/project.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
test/fixtures/cc/project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
test/fixtures/cc/spec.json
test/xcodeproj_tests.bzl

Part of https://github.com/buildbuddy-io/rules_xcodeproj/issues/83.

Add a pure C based example

---

test/fixtures/cc/spec.json
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/SearchPaths.swift
xcodeproj/internal/target.bzl

Part of #69, #82, #83, and #84.

Add support for `includes`

---

examples/cc/lib/BUILD
examples/cc/lib/lib.c
test/fixtures/cc/project.xcodeproj/project.pbxproj
test/fixtures/cc/spec.json
xcodeproj/internal/target.bzl

Also adds a header-only `objc_library` target as an integration test.

Add non-Xcode target files to `extra_files`

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/PBXProductType+Extensions.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/SetTargetConfigurations.swift

Set `LD_RUNPATH_SEARCH_PATHS` build setting

---

xcodeproj/repositories.bzl

Upgrade rules_swift and rules_apple

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
examples/ios_app/third_party/BUILD

Add an `apple_static_framework_import` example

---

tools/generator/src/FilePath.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Sorting.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj.bzl

Part of #75.
This is needed in order to bundle unstructured resources.

Add support for folder `FilePath`s

---

examples/ios_app/Example/BUILD
examples/ios_app/Example/ContentView.swift
examples/ios_app/Example/en.lproj/Localizable.strings
examples/ios_app/Example/es.lproj/Localizable.strings
examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
tools/generator/src/FilePath.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+CreateProject.swift
tools/generator/src/Path+Extensions.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/Fixtures.swift

Add support for localized files

---

tools/generator/src/Path+Extensions.swift

Part of https://github.com/buildbuddy-io/rules_xcodeproj/issues/70.

Fix xcframework imports

---

tools/generator/src/Generator+AddTargets.swift

This fixes builds when there are no generated modulemaps.

Only create a "Fix Modulemaps" script if there are generated modulemaps

---

tools/generator/src/Generator.swift

Fixes an illegal instruction failure.

Update invalid merge logging removing the force unwrap expressions

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
examples/ios_app/test/fixtures/project.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+SetTargetConfigurations.swift

Fixes https://github.com/buildbuddy-io/rules_xcodeproj/issues/238
| Before                    | After                   |
| ------------------------- |-------------------------|
| <img width="972" alt="Screenshot 2022-04-06 at 11 14 34 PM" src="https://user-images.githubusercontent.com/3658887/162072858-8c353abd-76ff-4efd-a02f-95b03fc6fdc2.png"> | <img width="366" alt="Screenshot 2022-04-06 at 11 10 52 PM" src="https://user-images.githubusercontent.com/3658887/162072874-64adae6a-4671-426a-9a7b-998a312ee460.png"> |

Fix UIDeviceFamily warning by patching Info.plist

---

examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
test/fixtures/cc/spec.json
test/fixtures/command_line/spec.json
test/fixtures/generator/spec.json
test/internal/target/process_libraries_tests.bzl
test/internal/target/process_top_level_properties_tests.bzl
tools/generator/src/DTO.swift
tools/generator/src/Environment.swift
tools/generator/src/Generator+AddTargets.swift
tools/generator/src/Generator+CreateFilesAndGroups.swift
tools/generator/src/Generator+CreateProducts.swift
tools/generator/src/Generator+ProcessTargetMerges.swift
tools/generator/test/CreateProductsTest.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/ProcessTargetMergesTests.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/providers.bzl
xcodeproj/internal/resource_bundle_products.bzl
xcodeproj/internal/target.bzl
xcodeproj/internal/xcodeproj.bzl

Fix linking for `apple_static_framework_import`

---

examples/ios_app/CoreUtilsObjC/BUILD
examples/ios_app/CoreUtilsObjC/CoreUtils/Answers.h
examples/ios_app/CoreUtilsObjC/CoreUtils/CoreUtils.pch
examples/ios_app/test/fixtures/project.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/spec.json
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/src/Inputs.swift
xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/providers.bzl

Add support for `pch` attribute

---

README.md
doc/faq.md

Add FAQ and link to it in README.md

---

xcodeproj/internal/installer.template.sh

This path should have changed with #319.

Fix one time setup check

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
xcodeproj/internal/target.bzl
xcodeproj/internal/targets.bzl

This will be handled by output groups in the near future.

Remove unused `outputs`

---

xcodeproj/internal/linker_input_files.bzl

Add support for `objc_import`

---

tools/generator/src/Generator+AddBazelDependenciesTarget.swift

Refactor `addBazelDependenciesTarget` some more

---

.github/workflows/check_pr_title.yml

GitHub Action: [opinionated-commit-message](https://github.com/marketplace/actions/opinionated-commit-message)

Add GitHub Action workflow to check PR titles

---

examples/ios_app/CoreUtilsObjC/Answers.mm
examples/ios_app/CoreUtilsObjC/BUILD
examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx_spec.json
xcodeproj/internal/target.bzl

This adds support for `sdk_dylibs` which are passed to the linker as `-l` flags.

Add support for sdk_dylibs

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddBazelDependenciesTarget.swift

The output of this command can be completely silenced.

Silence Info.plist patching warning

---

tools/generator/src/PBXTarget+Extensions.swift

I was wrong, Xcode just doesn't support this.
Closes #371.

Remove comment about removing slashes

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/xcodeproj.bzl

This will be used to populate the `TEST_WORKSPACE` environment variable in a subsequent PR.

Add Bazel workspace name to the project JSON and DTO

---

tools/generator/BUILD

This helps us dogfood Building with Bazel more.

Change `generator`'s `build_mode` to `bazel`

---

xcodeproj/internal/library_targets.bzl
xcodeproj/internal/target.bzl

Moves library target logic into library_targets.bzl

Split out library target logic from target.bzl

---

tools/generator/src/Generator+AddTargets.swift

Consolidated targets (targets that represent more than one configuration at once, such as Simulator _and_ Device)  won't have direct access to `target.product`, as it's tied to a specific configuration. This change is in prep of that.

Reduce use of `target.product`

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
test/internal/platform/generate_platform_information_tests.bzl
tools/generator/src/DTO.swift
tools/generator/src/Generator+SetTargetConfigurations.swift
tools/generator/test/DisambiguateTargetsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/SetTargetConfigurations.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/platform.bzl

This value will be more dynamic with consolidated targets.

Set `SUPPORTED_PLATFORMS` in `generator`

---

tools/generator/src/Generator+SetTargetConfigurations.swift

This is needed for the consolidated targets work.

Extract `buildSetting` manipulation into two methods

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator+AddTargets.swift
tools/generator/test/Fixtures.swift

With consolidated targets certain configurations might not produce a Swift generated header.

Add variable check to `Copy Swift Generated Header` Run Script

---

xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/target.bzl

Split out more logic from target.bzl

Split out non xcode target logic from target.bzl

---

test/internal/target/calculate_configuration_tests.bzl
test/internal/target/process_top_level_properties_tests.bzl
xcodeproj/internal/xcodeproj_aspect.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Resolves #136.
Split out final logic from target.bzl

Split out final logic from target.bzl

---

xcodeproj/internal/installer.template.sh
xcodeproj/internal/updater.template.sh

This works around https://github.com/bazelbuild/bazel/issues/4327.

Remove spaces from scheme names in fixtures

---

tools/generator/src/BuildSettingConditional.swift
tools/generator/src/DTO.swift
tools/generator/test/BuildSettingConditionalTests.swift

This will be needed by consolidated targets.

Sort `BuildSettingConditional` by `Platform.OS` as well

---

doc/faq.md
examples/multiplatform/iOSApp/BUILD
examples/multiplatform/tvOSApp/BUILD
examples/multiplatform/watchOSApp/BUILD
examples/multiplatform/watchOSAppExtension/BUILD
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx_spec.json
xcodeproj/experimental.bzl
xcodeproj/internal/provisioning_profiles.bzl
xcodeproj/internal/xcode_provisioning_profile.bzl

Add experimental rule to specify Xcode Managed provisioning profiles

---

examples/ios_app/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/ios_app/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwb.xcodeproj/project.pbxproj
test/fixtures/tvos_app/bwx.xcodeproj/project.pbxproj
tools/generator/src/Environment.swift
tools/generator/src/Generator+AddBazelDependenciesTarget.swift
tools/generator/src/Generator.swift
tools/generator/test/GeneratorTests.swift

Fixes an issue caused by #534.

Fix BwB indexing for projects that don't have a macOS target

---

test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
xcodeproj/internal/default_input_file_attributes_aspect.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/providers.bzl

This is needed for future work around resource file input collection.

Adjust uncategorized input collection

---

xcodeproj/internal/input_files.bzl

This is no longer needed with the resource file collection rework.

Remove `_SUSPECT_GENERATED_EXTENSIONS` check

---

xcodeproj/internal/output_files.bzl

This will be used by Focused Project logic in the near future.

Expose `parse_swift_info_module` and `swift_to_list` from `output_files.bzl`

---

xcodeproj/internal/output_files.bzl

This will be used by future Focused Project work.

Add `output_files.to_swift_list`

---

xcodeproj/internal/input_files.bzl

This will be used by future Focused Projects work.

Allow adding extra generated files to `input_files.merge`

---

xcodeproj/internal/default_automatic_target_processing_aspect.bzl

Fixes issues with `ios_static_framework` and the like.

Assume less about attributes based on provider

---

xcodeproj/internal/non_xcode_targets.bzl

We need the processed Info.plist to determine the configuration of the resource bundle. Resource bundles also don't really "work" without an Info.plist, so it's not too much of an ask to require a simple Info.plist to be set.

Add error when `apple_resource_bundle` doesn't have Info.plist in BwX

---

xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Part of #70.
There is no way currently for us to support this property.

Raise error when using `bundle_only` with BwX

---

xcodeproj/internal/linker_input_files.bzl

Instead of doing all of the `File` collection in `linker_input_files.to_dto`, we collect the files eagerly and only convert them to `file_path_dto` at the end. This will allow us to pass `linker_input_files` into `input_files` to collect generated linker inputs.

Refactor `linker_input_files` to enable future `File` collection

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO/Project.swift
tools/generator/src/DTO/SchemeAutogenerationMode.swift
tools/generator/src/Generator/CreateXCSchemes.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/test/CreateXCSchemesTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/xcodeproj.bzl

Add `scheme_autogeneration_mode` with support for `none`, `auto`, and `all`

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
xcodeproj/internal/resources.bzl

This is needed to support static framework resources.

Set `force_group_creation = True` for unstructured resources

---

WORKSPACE
examples/multiplatform/iOSApp/BUILD
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/external.xcfilelist
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/external.xcfilelist
test/fixtures/multiplatform/bwx_spec.json

Add `apple_static_xcframework_import` example

---

test/internal/bazel_labels/BUILD.bazel
test/internal/bazel_labels/normalize_tests.bzl
test/internal/bazel_labels/parse_tests.bzl
xcodeproj/internal/bazel_labels.bzl

Add tests for `bazel_labels.normalize` and some clean up

---

xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/non_xcode_targets.bzl

Single element tuples were actually just strings 😬.

Ensure that attr name sequences are actually sequences

---

tools/generator/test/Fixtures.swift

This will be used for some later App Extensions specific changes

Add WatchKit Extension to fixtures

---

test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
tools/generator/src/Extensions/PBXProductType+Extensions.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift

Remove incorrect Watch Application compile sources phase

---

test/fixtures/generator/BUILD
xcodeproj/internal/fixtures.bzl

Add `schemes` to `xcodeproj_fixture` macro

---

examples/multiplatform/iOSApp/iOSApp.swift
tools/generator/src/DTO/FilePath.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/PopulateMainGroup.swift
tools/generator/src/Generator/ProcessTargetMerges.swift
tools/generator/src/Generator/WriteXcodeProj.swift

`swiftformat --config .swiftformat --rules trailingSpace --verbose .`

Apply `trailingSpace` rule from `swiftformat`

---

tools/generator/src/DTO/BuildSetting.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/Main.swift
tools/generator/src/Generator/SetTargetConfigurations.swift

`swiftformat --config .swiftformat --rules hoistPatternLet --verbose .`

Apply `hoistPatternLet` rule for `swiftformat`

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
examples/multiplatform/BUILD
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO/Target.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/test/Fixtures.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/top_level_targets.bzl

Add support for embedding extensions

---

tools/generator/test/Fixtures.swift

This will be used to show later improvements to WidgetKit Extensions.

Add WidgetKit Extension to fixtures

---

test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift

Similar to 7c88b988914c995fd22a0dc3fc14f259927c8332.

Set `EXCLUDED_SOURCE_FILE_NAMES` as a string as well

---

xcodeproj/internal/opts.bzl

Fix handling of `$location()/$rootpath()` in copts

---

examples/multiplatform/BUILD
examples/multiplatform/iMessageApp/Assets.xcassets/AppIcon.appiconset/Contents.json
examples/multiplatform/iMessageApp/Assets.xcassets/Contents.json
examples/multiplatform/iMessageApp/BUILD
examples/multiplatform/iMessageApp/Base.lproj/MainInterface.storyboard
examples/multiplatform/iMessageApp/ExtensionAssets.xcassets/Contents.json
examples/multiplatform/iMessageApp/ExtensionAssets.xcassets/iMessage App Icon.stickersiconset/Contents.json
examples/multiplatform/iMessageApp/Info.extension.plist
examples/multiplatform/iMessageApp/Info.plist
examples/multiplatform/iMessageApp/MessagesViewController.swift
examples/multiplatform/xcodeproj_targets.bzl
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-28ac48b4d0bf/examples/multiplatform/iMessageApp/iMessageAppExtension.LinkFileList
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-e7c08a7bb9db/examples/multiplatform/iMessageApp/iMessageAppExtension.LinkFileList
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.copied.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/infoplists.fixed.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/infoplists.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/targets/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-787a8770ecb8/examples/multiplatform/iMessageApp/iMessageAppExtension.LinkFileList
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/targets/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-6fabcb83ef01/examples/multiplatform/iMessageApp/iMessageAppExtension.LinkFileList
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
test/fixtures/multiplatform/bwx_spec.json

Add iMessage App example

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO/Target.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/test/Fixtures.swift
tools/generator/test/Target+Testing.swift
xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/top_level_targets.bzl

Add support for App Clips

---

xcodeproj/internal/xcodeproj_aspect.bzl

Declare our use of the cpp toolchain

---

.github/workflows/check_pr_title.yml

I'm being helpful! :3 (See failing check on #760)

Add "symlink" to additional-verbs allow list

---

examples/ios_app/test/fixtures/bwb_spec.json
examples/ios_app/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/macos_app/bwx_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx_spec.json
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
test/fixtures/tvos_app/bwb_spec.json
test/fixtures/tvos_app/bwx_spec.json
tools/generator/src/DTO/Target.swift
xcodeproj/internal/processed_target.bzl

Part of #237.
This is progress towards reducing the size of the `spec.json` file.

Stop setting default values for `Target` DTO in `spec.json`

---

xcodeproj/internal/linker_input_files.bzl

This will make a future change easier, which requires knowing all of the libraries for all targets, not just top level ones.

Extract common library collection code

---

test/fixtures/generator/BUILD
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/Generator_App.xcscheme
test/fixtures/generator/bwx_spec.json
tools/generator/BUILD
tools/generator/xcodeproj_targets.bzl
xcodeproj/internal/fixtures.bzl

Pass along `scheme_autogeneration_mode` to fixture rule

---

test/utils.bzl
xcodeproj/internal/compilation_providers.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/opts.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/target_search_paths.bzl
xcodeproj/internal/top_level_targets.bzl

This will allow us to de-stringify `_xcode_target`.

Use frozen types in `_xcode_target` arguments

---

xcodeproj/internal/providers.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Should have been removed with 63a0c1ceefb0bb4044f1fb789be1f0f18d281fcf.

Remove unused `XcodeProjInfo.target_libraries`

---

test/fixtures/simple/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurationsTests.swift

We need to only set the overlays if they are created.

Fix VFS overlays for simple projects

---

xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/processed_target.bzl
xcodeproj/internal/providers.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

BwX Focused Projects can be broken otherwise.

Fix transitive dependency calculation

---

examples/command_line/Tests/SwiftGreetingsTests.swift
examples/command_line/lib/BUILD
examples/command_line/lib/lib.swift
examples/command_line/lib/private_lib.swift
test/fixtures/command_line/bwb.xcodeproj/project.pbxproj
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-01f14ffe769b/examples/command_line/Tests/LibSwiftTests.__internal__.__test_bundle.link.params
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-01f14ffe769b/examples/command_line/tool/tool.link.params
test/fixtures/command_line/bwb.xcodeproj/xcshareddata/xcschemes/private_swift_lib.xcscheme
test/fixtures/command_line/bwb_spec.json
test/fixtures/command_line/bwx.xcodeproj/project.pbxproj
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-3e9e205cb29c/examples/command_line/Tests/LibSwiftTests.__internal__.__test_bundle.link.params
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min11.0-applebin_macos-darwin_x86_64-dbg-ST-3e9e205cb29c/examples/command_line/tool/tool.link.params
test/fixtures/command_line/bwx.xcodeproj/xcshareddata/xcschemes/private_swift_lib.xcscheme
test/fixtures/command_line/bwx_spec.json

This is needed to test some upcoming LLDB improvements.

Add `swift_library` to `private_deps`

---

tools/generator/src/DTO/Platform.swift
tools/generator/src/Generator/DisambiguateTargets.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Target+Testing.swift

We will need the `Platform.OSVersion.fullVersion` property in lldb changes.

Add `Platform.OSVersion`

---

xcodeproj/internal/installer.template.sh

Create symlinks during project generation

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/cc/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/macos_app/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/macos_app/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/simple/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/tvos_app/bwx.xcodeproj/rules_xcodeproj/swift_debug_settings.py
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/test/Fixtures.swift

Also remove the fallback, as it's not needed.

Fix some issues with `swift_debug_settings.py`

---

tools/generator/src/DTO/Platform.swift
tools/generator/src/Extensions/Platform+Extensions.swift
tools/generator/src/Generator/DisambiguateTargets.swift
tools/generator/src/Generator/SemanticVersion.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/SemanticVersionTests.swift
tools/generator/test/Target+Testing.swift

Replace `Platform.OSVersion` with `SemanticVersion`

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/cc/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/macos_app/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/macos_app/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/simple/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
test/fixtures/tvos_app/bwx.xcodeproj/rules_xcodeproj/bazel/create_lldbinit.sh
xcodeproj/internal/bazel_integration_files/create_lldbinit.sh

Found while investigating #858.

Fix typo in `create_lldbinit.sh`

---

examples/ios_app/test/fixtures/bwb_spec.json
test/fixtures/command_line/bwb_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/macos_app/bwb_spec.json
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/tvos_app/bwb_spec.json
tools/generator/src/DTO/LLDBContext.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
xcodeproj/internal/lldb_contexts.bzl

This will allow filtering values from it.

Pass `LLDBContext.Clang.opts` as an array

---

xcodeproj/internal/input_files.bzl

This allows the project to contain the input files for rules like `precompiled_apple_resource_bundle`.

Include generated resource bundle input files

---

doc/faq.md
tools/generator/xcodeproj_targets.bzl

- Add comment to `tools/generator/xcodeproj_targets.bzl`.
- Add sections to `doc/faq.md`.

Document `tools/generator` custom Xcode scheme function

---

third_party/com_github_pointfreeco_swift_custom_dump/BUILD
third_party/com_github_tuist_xcodeproj/BUILD
tools/BUILD
tools/extensionpointidentifiers_parser/BUILD
tools/generator/BUILD
tools/generator/test/BUILD
tools/xccurrentversions_parser/BUILD
xcodeproj/BUILD
xcodeproj/internal/BUILD
xcodeproj/internal/bazel_integration_files/BUILD

Missed with bda0e72283358be6c3e01118afacd16bcbe53505.

Remove unused `all_files` `filegroup`s

---

doc/rules-xcodeproj.md
shared.bazelrc
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx_spec.json
test/internal/xcode_schemes/model_tests.bzl
tools/generator/src/DTO/XcodeScheme.swift
tools/generator/src/Extensions/XCScheme+Extensions.swift
tools/generator/src/Generator/XCSchemeInfo+TestActionInfo.swift
tools/generator/test/XCScheme+ExtensionsTests.swift
tools/generator/test/XCSchemeInfo+TestActionInfoTests.swift
tools/generator/test/XcodeSchemeTests.swift
tools/generator/xcodeproj_targets.bzl
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcode_schemes_internal.bzl

Support custom command line args and environment variables for test action

---

doc/rules-xcodeproj.md
test/internal/xcode_schemes/model_tests.bzl
xcodeproj/internal/xcode_schemes.bzl

Allow `xcode_schemes.build_action` to accept `string` `targets`

---

xcodeproj/internal/xcodeproj_macro.bzl

Bug introduced with 51ec0f82416a26f801ba7f8331572ec12ae7714e.

Fix `toplevel_cache_buster`

---

examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/cc/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/command_line/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/command_line/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/macos_app/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/macos_app/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/simple/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/tvos_app/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/tvos_app/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/bazel_integration_files/xcodeproj.bazelrc

Fixes #470.
This fixes Test Issue navigation in BwB mode.

Set `--features=apple.swizzle_absolute_xcttestsourcelocation`

---

xcodeproj/internal/output_files.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Generate all versions of Info.plist for a given target when building

---

examples/multiplatform/macOSApp/Test/UITests/BUILD
examples/multiplatform/macOSApp/Test/UITests/UITests.swift
examples/multiplatform/macOSApp/Test/UITests/UITestsLaunchTests.swift
examples/multiplatform/xcodeproj_targets.bzl
test/fixtures/multiplatform/bwb.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/multiplatform/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min15.0-applebin_macos-darwin_x86_64-dbg-ST-e33b8db88e1c/examples/multiplatform/macOSApp/Test/UITests/macOSAppUITests.link.params
test/fixtures/multiplatform/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
test/fixtures/multiplatform/bwb_spec.json
test/fixtures/multiplatform/bwx.xcodeproj/project.pbxproj
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/multiplatform/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min15.0-applebin_macos-darwin_x86_64-dbg-ST-450091386d5c/examples/multiplatform/macOSApp/Test/UITests/macOSAppUITests.link.params
test/fixtures/multiplatform/bwx.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
test/fixtures/multiplatform/bwx_spec.json

Adds a ui test to the macOS example

Add UITest for MacOS example

---

examples/integration/macOSApp/Source/BUILD
test/fixtures/integration/bwb.xcodeproj/project.pbxproj
test/fixtures/integration/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/integration/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/integration/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min12.0-applebin_macos-darwin_x86_64-dbg-ST-4f8ba90877f7/examples/integration/macOSApp/Source/macOSApp.link.params
test/fixtures/integration/bwb_spec.json
test/fixtures/integration/bwx.xcodeproj/project.pbxproj
test/fixtures/integration/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/integration/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min12.0-applebin_macos-darwin_x86_64-dbg-ST-b3ff25aa4da2/examples/integration/macOSApp/Source/macOSApp.link.params
test/fixtures/integration/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min15.0-applebin_macos-darwin_x86_64-dbg-ST-450091386d5c/examples/integration/macOSApp/Source/macOSApp.link.params
test/fixtures/integration/bwx_spec.json

This level is too high for our examples

Fix minimum_os_version for macOSApp

---

examples/integration/macOSApp/Test/UITests/BUILD
test/fixtures/integration/bwb.xcodeproj/project.pbxproj
test/fixtures/integration/bwb.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/integration/bwb.xcodeproj/rules_xcodeproj/swift_debug_settings.py
test/fixtures/integration/bwb.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min12.0-applebin_macos-darwin_x86_64-dbg-ST-4f8ba90877f7/examples/integration/macOSApp/Test/UITests/macOSAppUITests.link.params
test/fixtures/integration/bwb_spec.json
test/fixtures/integration/bwx.xcodeproj/project.pbxproj
test/fixtures/integration/bwx.xcodeproj/rules_xcodeproj/generated.xcfilelist
test/fixtures/integration/bwx.xcodeproj/rules_xcodeproj/targets/macos-x86_64-min12.0-applebin_macos-darwin_x86_64-dbg-ST-b3ff25aa4da2/examples/integration/macOSApp/Test/UITests/macOSAppUITests.link.params
test/fixtures/integration/bwx_spec.json

This value was too high, matches the value for the app itself

Update minimum_os_version for macOS UITest

---

.bazelignore
buildbuddy.yaml
examples/integration/.bazelignore
examples/ios_app/.bazelignore

And run them after spec validations, for quicker feedback on those.

Also run example tests

---

xcodeproj/internal/xcodeproj_rule.bzl

Fixes #1030.
This doesn't do the full replacement in Starlark, but it could probably do so in the future.

Apply label replacement in Starlark as well

---

xcodeproj/repositories.bzl

Update to https://github.com/tuist/XcodeProj/commit/b7e93122d08e59497211ea12f4da73e6a4d7d598

Bump `com_github_tuist_xcodeproj`

---

examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/ios_app/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/ios_app/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/cc/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/cc/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/simple/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/simple/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh

This should be a no-op for behavior. I was editing this trying to fix another issue.

Optimize vfs overlay creation

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
test/fixtures/cc/bwb.xcodeproj/project.pbxproj
test/fixtures/cc/bwb_spec.json
test/fixtures/cc/bwx_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
test/fixtures/simple/bwb.xcodeproj/project.pbxproj
test/fixtures/simple/bwb_spec.json
test/fixtures/simple/bwx_spec.json
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/product.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Fixes #1028.
This allows the Memory Graph debugger to work with them.

Codesign `*_binary` rules

---

xcodeproj/internal/opts.bzl

This is applied automatically by Xcode as needed.

Ignore `-enable-bare-slash-regex`

---

xcodeproj/internal/top_level_target.bzl
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/xcodeproj.bzl

This will allow for better ruleset documentation in the future.

Extract `top_level_target` to a new file

---

xcodeproj/internal/xcodeproj_rule.bzl

Fixes #1090.
Before this change, in BwX mode, if an automatically unfocused target was only part of some dependency trees (e.g. a dep of a unit test, but not the test host), then its dependencies would correctly be marked as a unfocused target's dependency, and be set to be compiled with Bazel, but they wouldn't appear in every output group they needed to be in (e.g. the test host's).
Now if a target is supposed to be built with Bazel because it's an automatically unfocused target's dependency, they will appear in the output group of all dependent targets.

Include unfocused dependencies in every output group

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/runner.template.sh

This is three changes:
- On the command-line, set `--xcode_version` to whatever `xcode-select` is set to
- In Xcode, set `--xcode_version` to `$XCODE_PRODUCT_BUILD_VERSION`
- For both, set `--repo_env=USE_CLANG_CL= $XCODE_PRODUCT_BUILD_VERSION` to work around https://github.com/bazelbuild/bazel/issues/8902

Ensure Bazel uses the correct Xcode version when compiling

---

xcodeproj/internal/installer.template.sh

This prevents analysis cache trashing.

Set `--repo_env=USE_CLANG_CL` in installer as well

---

test/internal/opts/process_compiler_opts_tests.bzl
xcodeproj/internal/opts.bzl

Add support for STRICT_SWIFT_CONCURRENCY

---

.swiftlint.yml
examples/integration/iOSApp/Source/iOSApp.swift
examples/integration/macOSApp/Source/macOSApp.swift
examples/integration/tvOSApp/Source/tvOSApp.swift
examples/integration/watchOSAppExtension/watchOSApp.swift
tools/generator/src/DTO/Target+LinkerFlags.swift
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/SetTargetConfigurations.swift

Disable all SwiftLint rules that cause errors for now

---

tools/generator/src/Extensions/PBXProductType+Extensions.swift
tools/generator/src/Generator/AddTargets.swift

This fixes an issue with upcoming framework support.

Stop embedding frameworks in other frameworks

---

xcodeproj/internal/compilation_providers.bzl
xcodeproj/internal/top_level_targets.bzl

This will be used in future framework support.

Retrieve `ObjcProvider` from `AppleDynamicFrameworkInfo`

---

tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/SetTargetConfigurationsTests.swift

This is the BwX side of b6144935ad30cb933d92f9c5579426f4868f93c2.

Adjust `LD_RUNPATH_SEARCH_PATHS` for BwX framework SwiftUI Previews

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
xcodeproj/internal/bazel_integration_files/calculate_output_groups.py

This broke with 0f465a52e9d5e659b32e9e7dc5fddead7c3ee9b3.

Fix SwiftUI Preview target id selection

---

xcodeproj/internal/compilation_providers.bzl
xcodeproj/internal/top_level_targets.bzl

Fix linking for `*_dynamic_framework` targets

---

xcodeproj/internal/output_files.bzl

Allow `module.clang` to be `None`

---

xcodeproj/internal/top_level_targets.bzl

Be more lenient in detecting framework bundle paths

---

examples/integration/Lib/BUILD

Missed with `ad48750685645dffc097edf0dd2ee92dbd4b68a6`.

Remove unused targets

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/calculate_output_groups.py
xcodeproj/internal/bazel_integration_files/calculate_output_groups.py

I've seen a build that stuck for several minutes, add this to help
with debugging.

Add some debug info to build request file log messages

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
xcodeproj/internal/bazel_integration_files/bazel_build.sh

Remove labels from target pattern

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/bazel_build.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/bazel_integration_files/bazel_build.sh
xcodeproj/internal/xcodeproj.template.bazelrc

Also apply ubsan when alongside other ones if applicable.

Apply sanitizer features to both normal and SwiftUI Previews builds

---

examples/cc/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
examples/simple/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/SwiftBin.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
tools/generator/src/Extensions/XCScheme+Extensions.swift

This could create symlinks inside of the Xcode bundle before.

Fix sanitizer symlink creation

---

docs/bazel.md
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
test/fixtures/generator/bwx_spec.json
test/internal/xcode_schemes/model_tests.bzl
tools/generator/src/DTO/XcodeScheme.swift
tools/generator/src/Extensions/XCScheme+Extensions.swift
tools/generator/src/Generator/XCSchemeInfo+TestActionInfo.swift
tools/generator/test/XCScheme+ExtensionsTests.swift
tools/generator/test/XcodeScheme+ExtensionsTests.swift
tools/generator/xcodeproj_targets.bzl
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcode_schemes_internal.bzl

Test actions also support configuring diagnostics.

Add support for `test_action.diagnostics`

---

tools/generator/src/Generator/SetTargetConfigurations.swift

Trying to make it an implementation detail of `FilePathResolver`

Remove another use of `xcodeGeneratedFiles`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/SetTargetConfigurations.swift

This is in preparation of `PROJECT_DIR` changing.

Set `forceFullBuildSettingPath: true` in more locations

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/xcodeproj.bazelrc
xcodeproj/internal/xcodeproj.template.bazelrc

Fixed a regression from c936bdae2ce6c17a1c3ac6159d34cbae1ce7c9ef.

Silence outputs in logs

---

examples/simple/BUILD

BwB doesn't show off the "simple-ness".

Use BwX for the `examples/simple`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

Mainly in preparation of extracting parts to another script.

Apply some code cleanup to `generate_bazel_dependencies.sh`

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
examples/simple/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
test/fixtures/generator/bwx.xcodeproj/rules_xcodeproj/bazel/generate_bazel_dependencies.sh
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

Preparation to extract `bazel_build.sh`.

Apply more reformatting to `generate_bazel_dependencies.sh`

---

examples/cc/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
examples/simple/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/SwiftBin.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
tools/generator/src/Extensions/XCScheme+Extensions.swift

This was still creating a `lib` symlink inside of the Xcode bundle.

Fix symlink creation

---

examples/cc/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
examples/sanitizers/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
examples/simple/test/fixtures/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
test/fixtures/generator/bwb.xcodeproj/rules_xcodeproj/bazel/copy_outputs.sh
xcodeproj/internal/bazel_integration_files/copy_outputs.sh

Regressed with 5aec77f2831a70164406d461811bedab7a46e6aa.

Fix BwB SwiftUI Preview framework copying

---

examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/SetTargetConfigurations.swift

This fixes a regression introduced by 5aec77f2831a70164406d461811bedab7a46e6aa.

Fully qualify BwX framework `FRAMEWORK_SEARCH_PATHS`

---

xcodeproj/internal/runner.template.sh

This allows it to apply to both branches.

Move newline in runner script

---

examples/integration/BUILD
examples/integration/test/fixtures/BUILD
examples/integration/xcodeproj_targets.bzl

This was missed in the final changes
for test env support

Use a constant for scheme gen mode

---

examples/cc/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AppClip.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineTool.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/CommandLineToolTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/WidgetExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iMessageAppExtension.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppObjCUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppSwiftUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/iOSAppUnitTests_Scheme.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/macOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUITests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/tvOSAppUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSApp.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppExtensionUnitTests.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/watchOSAppUITests.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/AddressSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ThreadSanitizer.xcscheme
examples/sanitizers/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/UndefinedBehaviorSanitizer.xcscheme
examples/simple/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/SwiftBin.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/swiftc.xcscheme
tools/generator/src/Extensions/XCScheme+Extensions.swift

https://github.com/buildbuddy-io/rules_xcodeproj/pull/1291#issuecomment-1277609592

Do symlink even better

---

xcodeproj/internal/installer.template.sh

We can calculate the path to the inner `bazel-out` from the outer one.

Remove extra `bazel info` call

---

test/fixtures/generator/bwb.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx.xcodeproj/xcshareddata/xcschemes/generator.xcscheme
test/fixtures/generator/bwx_spec.json
tools/generator/xcodeproj_targets.bzl

Recent changes made them out of date.

Adjust generator launch arguments

---

tools/generator/src/FilePathResolver.swift

Saves about 2 seconds in a large real world project.

Memoize `FilePathResolver` results

---

xcodeproj/internal/installer.template.sh
xcodeproj/internal/updater.template.sh
xcodeproj/internal/xcodeproj_rule.bzl

We can use the new `_is_fixture` attribute.

Remove ` --for_fixture` flag

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddTargets.swift
xcodeproj/internal/bazel_integration_files/BUILD
xcodeproj/internal/bazel_integration_files/copy_outputs.sh

This allows them to be smaller, but also allows us to change behavior based on the type of product. A future change will adjust watchOS 2 excludes.

Split `exclude.rsynclist` into multiple files

---

xcodeproj/internal/xcodeproj_rule.bzl

`focused_targets` is the same thing.

Remove redundant `targets` `dict`

---

xcodeproj/internal/xcodeproj_rule.bzl

This will be used in another spot soon.

Extract `include_lldb_context`

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/product.bzl
xcodeproj/internal/target_search_paths.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Also convert larger structs into more focused ones.
These changes are needed to move target merging into Starlark.

Consolidate DTO functions into `xcode_targets`

---

xcodeproj/internal/bazel_integration_files/process_bazel_build_log.py

Fixes #1378.
In some cases, when using `--features=swift.vfsoverlay`, the errors will use an absolute path instead of a relative one. Now in `process_bazel_build_log.py` we handle this case as well.

Process execution root prefixed build errors correctly

---

xcodeproj/internal/bazel_integration_files/process_bazel_build_log.py

Fix capitalization of error messages

---

xcodeproj/internal/bazel_integration_files/bazel_build.sh

Use parameter expansion to remove the use of `../`. Also remove errant extra path.

Standardize and correct indexing `$output_base`

---

xcodeproj/internal/files.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Fixes a regression with 21ef03717da50d11c0716b29b7f6f5ff804305f7.

Preserve previous quote behavior for build setting paths

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
examples/sanitizers/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwx_spec.json
examples/simple/test/fixtures/bwb_spec.json
examples/simple/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/SearchPaths.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/xcode_targets.bzl

Set header search paths in Starlark

---

examples/integration/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwb_spec.json
examples/simple/test/fixtures/bwb_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/LLDBContext.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
xcodeproj/internal/lldb_contexts.bzl

Set lldb context header search paths in Starlark

---

examples/integration/test/fixtures/bwb_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/LLDBContext.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
xcodeproj/internal/lldb_contexts.bzl

Set lldb modulemap paths in Starlark

---

examples/cc/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/sanitizers/test/fixtures/bwb_spec.json
examples/simple/test/fixtures/bwb_spec.json
test/fixtures/generator/bwb_spec.json
tools/generator/src/Generator/SetTargetConfigurations.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Set `BAZEL_OUTPUTS_PRODUCT` in Starlark

---

examples/integration/test/fixtures/bwb_spec.json
tools/generator/src/DTO/LLDBContext.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
xcodeproj/internal/files.bzl
xcodeproj/internal/lldb_contexts.bzl

Set lldb context framework search paths in Starlark

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/product.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Needed to later convert this to use Starlark based file path resolution.

Refactor `_product_to_dto`

---

examples/integration/test/fixtures/bwb_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/LLDBContext.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/lldb_contexts.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Set lldb swiftmodule includes in Starlark

---

tools/generator/src/DTO/Platform.swift

Forgot to remove with 6a5f59baa345c29ca01772bfe845683a7bb97af6.

Remove unused `Platform.swiftTriple`

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx_spec.json
test/fixtures/generator/bwb_spec.json
test/fixtures/generator/bwx_spec.json
tools/generator/src/DTO/LinkerInputs.swift
tools/generator/src/DTO/Target+LinkerFlags.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/xcode_targets.bzl

Resolve static library linkopt paths in Starlark

---

examples/cc/test/fixtures/bwb_spec.json
examples/cc/test/fixtures/bwx_spec.json
examples/integration/test/fixtures/bwb.xcodeproj/rules_xcodeproj/external.xcfilelist
examples/integration/test/fixtures/bwb_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/external.xcfilelist
examples/integration/test/fixtures/bwx_spec.json
tools/generator/src/DTO/LinkerInputs.swift
tools/generator/src/DTO/Target+LinkerFlags.swift
tools/generator/test/Fixtures.swift
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/xcode_targets.bzl

Resolve force load linkopt paths in Starlark

---

tools/generator/src/DTO/LinkerInputs.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/test/Fixtures.swift

We already include these files in `extraFiles`.

Remove unneeded `LinkerInputs.nonGenerated`

---

xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh
xcodeproj/internal/runner.template.sh

This fixes breakpoints when only the linked binary would be downloaded.

Download archive files when using BwtB

---

tools/generator/src/Extensions/Sorting.swift

We now cache the sorting keys.

Optimize element sorting

---

tools/generator/src/Generator/CreateFilesAndGroups.swift

Super minor improvement in speed.

Optimize component calculation

---

README.md

Add Spotify to list of projects using rules_xcodeproj

---

README.md

Thank you for the great ruleset!

Include Robinhood as consumers

---

xcodeproj/internal/installer.template.sh
xcodeproj/internal/runner.template.sh
xcodeproj/internal/xcodeproj_runner.bzl

This makes it more compatible with various bazel wrappers.

Rename `--bazelrc` to `--xcodeproj_bazelrc`

---

examples/cc/test/fixtures/bwb_project_spec.json
examples/cc/test/fixtures/bwx_project_spec.json
examples/integration/test/fixtures/bwb_project_spec.json
examples/integration/test/fixtures/bwx_project_spec.json
test/fixtures/generator/bwb_project_spec.json
test/fixtures/generator/bwx_project_spec.json
xcodeproj/internal/xcodeproj_rule.bzl

Sometimes differences in Bazel versions can cause these to be ordered differently.

Sort fixture `extra_files`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/simple/test/fixtures/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/AddTargets.swift

Stop processing `link.params` when not needed

---

buildbuddy.yaml

This will allow more actions per Workflow Mac.

Adjust Workflow resource requests and arm64 assignments

---

xcodeproj/internal/bazel_integration_files/create_lldbinit.sh

Regressed with 6934ecaf002828ab2487a079b5b8017a7046dc3b.

Fix `$RESOLVED_EXTERNAL_REPOSITORIES` handling

---

xcodeproj/internal/xcodeproj_rule.bzl

Regressed with a7cc6e1de67cf4b12cc4839c76b76f7a062ea0ab.

Fix `xl` output group calculation

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/Fixtures.swift
tools/params_processors/link_params_processor.py
xcodeproj/internal/product.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

One less thing we let the generator decide. Next we need to set `TEST_HOST` in Starlark.

Allow `-bundle_loader` in `link.params`

---

xcodeproj/internal/bazel_integration_files/bazel_build.sh

Regressed with df9425a497a1b871885573cef2882d9dd75dcf11.

Fix BwX Index Build failure

---

xcodeproj/internal/opts.bzl

This is to ensure we don't hit the BwX mode relative path bug.

Apply path remapping for all Swift flags

---

xcodeproj/internal/xcode_targets.bzl

This will make it easier to stop setting `FRAMEWORK_SEARCH_PATHS` in a future change.

Refactor BwX framework search path handling

---

examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx_targets_spec.json
tools/params_processors/link_params_processor.py
xcodeproj/internal/xcode_targets.bzl

This sets the rpath entries from the source of truth (`-F` in link commands).

Set BwX framework SwiftUI Previews rpaths in `link.params`

---

examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb_targets_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_targets_spec.json
xcodeproj/internal/output_files.bzl
xcodeproj/internal/product.bzl
xcodeproj/internal/resource_target.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcode_targets.bzl

Fixes #1586.
Regressed with 0ad6162d7c97e218d07c4892b864ceaaff150e5a.

Fix incorrect BwB copy path for macOS tests

---

test/internal/bazel_labels/normalize_tests.bzl
xcodeproj/internal/bazel_labels.bzl

Also adjusts tests to work with bzlmod enabled.

Fix `bazel_labels.normalize(bazel_labels.normalize())`

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwb_targets_spec.json
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx_targets_spec.json
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_targets_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx_targets_spec.json
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb_targets_spec.json
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx_targets_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_targets_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_targets_spec.json
test/internal/opts/process_compiler_opts_tests.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/opts.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcode_targets.bzl

This will bloat the project a little bit, at the defines will be in both `OTHER_CFLAGS` and `OTHER_CPLUSPLUSFLAGS`, but I'll be addressing that in a followup PR.

Stop setting `GCC_PREPROCESSOR_DEFINITIONS`

---

examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb_targets_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_targets_spec.json
xcodeproj/internal/top_level_targets.bzl

Regressed with 021c78f968cb5d484b48624b587f9c44a7a20207.

Fix stale BwB installs

---

tools/params_processors/link_params_processor.py
xcodeproj/internal/xcode_targets.bzl

This removes the second-to-last use of it.

Stop using `framework_includes` for `generated_search_paths`

---

xcodeproj/internal/default_automatic_target_processing_aspect.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Handle rules_ios's `apple_framework.vendored_xcframeworks`

---

README.md

We use this project to build our iOS app at Ten Ten  :)

Add Ten Ten to users list

---

third_party/com_github_michaeleisel_jjliso8601dateformatter/BUILD
tools/BUILD
tools/extensionpointidentifiers_parser/BUILD
tools/generator/BUILD
tools/params_processors/BUILD
tools/swiftc_stub/BUILD
tools/xccurrentversions_parser/BUILD
xcodeproj/BUILD
xcodeproj/internal/BUILD
xcodeproj/internal/bazel_integration_files/BUILD

This is in preparation of using `rules_pkg`.

Adjust `release_files` excludes

---

BUILD
MODULE.bazel
WORKSPACE

Use rules_pkg instead of `genrule`

---

BUILD
third_party/BUILD
third_party/com_github_michaeleisel_jjliso8601dateformatter/BUILD
tools/BUILD
tools/extensionpointidentifiers_parser/BUILD
tools/generator/BUILD
tools/params_processors/BUILD
tools/swiftc_stub/BUILD
tools/xccurrentversions_parser/BUILD
xcodeproj/BUILD
xcodeproj/internal/BUILD
xcodeproj/internal/bazel_integration_files/BUILD

Allows for using `renames` in the future.

Improve rules_pkg usage

---

.bcr/presubmit.yml
distribution/BUILD
distribution/opt_wrapper.bzl
tools/generator/BUILD
tools/generator/BUILD.release.bazel

Use a prebuilt `universal_generator` with release.tar.gz

---

examples/cc/test/fixtures/bwb_project_spec.json
examples/cc/test/fixtures/bwx_project_spec.json
examples/integration/test/fixtures/bwb_project_spec.json
examples/integration/test/fixtures/bwx_project_spec.json
examples/sanitizers/test/fixtures/bwb_project_spec.json
examples/sanitizers/test/fixtures/bwx_project_spec.json
test/fixtures/generator/bwb_project_spec.json
test/fixtures/generator/bwx_project_spec.json
tools/generator/src/DTO/Project.swift
xcodeproj/internal/xcodeproj_rule.bzl

Use single letter json keys in `project_spec.json`

---

examples/integration/test/fixtures/bwb_project_spec.json
examples/integration/test/fixtures/bwx_project_spec.json
tools/generator/src/DTO/Project.swift
xcodeproj/internal/xcodeproj_rule.bzl

Default `Project.schemeAutogenerationMode` to `.all`

---

examples/cc/test/fixtures/bwb_project_spec.json
examples/cc/test/fixtures/bwx_project_spec.json
examples/integration/test/fixtures/bwb_project_spec.json
examples/integration/test/fixtures/bwx_project_spec.json
examples/sanitizers/test/fixtures/bwb_project_spec.json
examples/sanitizers/test/fixtures/bwx_project_spec.json
test/fixtures/generator/bwb_project_spec.json
test/fixtures/generator/bwx_project_spec.json
tools/generator/src/DTO/Project.swift
tools/generator/src/Generator/CreateProject.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/CreateProjectTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift
xcodeproj/internal/xcodeproj_rule.bzl

Move all project level build settings into `generator`

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ExampleNestedResources.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/ExampleResources.xcscheme
examples/integration/test/fixtures/bwb.xcodeproj/xcshareddata/xcschemes/OnlyStructuredResources.xcscheme
examples/integration/test/fixtures/bwb_project_spec.json
examples/integration/test/fixtures/bwb_targets_spec.json
xcodeproj/internal/input_files.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/target_properties.bzl
xcodeproj/internal/top_level_targets.bzl

Part of #1457.
This allows the targets to be focused or unfocused.

Generate resource bundle targets in BwB mode

---

README.md

Add rules support to README

---

README.md

Add a little more flair to the README

---

README.md

Add BazelCon video to README

---

xcodeproj/internal/bazel_integration_files/BUILD
xcodeproj/internal/filelists.bzl
xcodeproj/internal/installer.template.sh
xcodeproj/internal/product.bzl

Fix `cp -c` issue with other volumes

---

README.md

Fix relative links in README.md

---

xcodeproj/internal/bazel_labels.bzl

Use `native.package_relative_label` if available

---

examples/integration/CommandLine/CommandLineTool/BUILD
examples/integration/CommandLine/external/BUILD.tpl

These should have been removed a long time ago.

Remove references to rules_cc

---

xcodeproj/internal/xcodeproj_rule.bzl

Prepping for multiple Xcode configuration support. Also probably fixes an issue with the `extra_files` logic.

Refactor target merging

---

xcodeproj/internal/installer.template.sh

Regressed in ff51b809b50ae96cdabbe02925f4391087dd0a91.

Properly delete old files in `.xcodeproj/rules_xcodeproj/bazel`

---

tools/generator/src/Generator/ConsolidateTargets.swift
tools/generator/test/ConsolidateTargetsTests.swift

When we fail to consolidate all targets, we still allow consolidation of whichever targets _can_ consolidate. Also, instead of preventing all dependent targets from consolidating, they are re-evaluated, and maybe they can partially consolidate as well.
This is needed for multi-Xcode configuration targets, because otherwise the various configurations wouldn’t be able to consolidate if there were conditional dependencies in other variations.

Consolidate more targets

---

bazel_6.bazelrc
buildbuddy.yaml
examples/integration/bazel_6.bazelrc
shared.bazelrc
test/update_all_fixtures.sh
xcodeproj/internal/runner.template.sh

This way will work with a future change to how the runner works.

Change how we adjust flags for fixtures

---

tools/generator/src/Generator/SetTargetConfigurations.swift

By appending to a prefix array and then inserting that array once, we only incur O(n) once instead of multiple times.

Refactor flag code to only call `insert()` once

---

xcodeproj/internal/app_icons.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/linker_input_files.bzl
xcodeproj/internal/top_level_target.bzl
xcodeproj/internal/xcode_schemes.bzl
xcodeproj/internal/xcode_schemes_internal.bzl
xcodeproj/internal/xcodeproj_macro.bzl
xcodeproj/internal/xcodeproj_rule.bzl

When profiling, the cost of `sets`’s intermediate `struct` creation stood out.

Use raw `dict` instead of `sets`

---

tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/src/Generator/SetTargetConfigurations.swift
tools/generator/test/GeneratorTests.swift
tools/generator/test/SetTargetConfigurationsTests.swift

On a large project this reduces generation from 19s to 13s on my machine.

Set target configurations in parallel

---

tools/generator/src/Generator/Generator.swift

Currently this is only a minor speed up. We might be able to add concurrency inside the function later.

Run `createFilesAndGroups()` in parallel to other functions

---

tools/generator/src/Generator/CreateFilesAndGroups.swift

Less casts, and sets it up for easier future refactoring.

Split `groups` into the various versions

---

xcodeproj/internal/xcodeproj_runner.bzl

It should append to the existing values, not replace.

Fix handling of `//command_line_option:features` in `xcode_configurations`

---

xcodeproj/internal/opts.bzl

There were pieces that were only needed by one of the CC or Swift paths. This makes it more efficient.

Refactor out `_process_base_compiler_opts`

---

README.md

Adding Snap to the list of users of rules_xcodeproj

Add Snap to users list

---

CODEOWNERS
MAINTENANCE.md

This is an initial version of the document. It will be expanded with the release process, details on how we work, etc. in future revisions.

Add `MAINTENANCE.md`

---

xcodeproj/internal/bazel_integration_files/calculate_output_groups.py
xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh

Fix `calculate_output_groups.py` for Xcode 14.3

---

xcodeproj/internal/bazel_integration_files/copy_outputs.sh

Part of #1922.
This is needed to allow for Bazel-set rpaths (BwB or unfocused BwX targets) to work.

Symlink binaries instead of copying them

---

xcodeproj/internal/default_automatic_target_processing_aspect.bzl

This makes some code paths more efficient.

Add `apple_resource_group` to `default_automatic_target_processing_aspect`

---

examples/cc/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/AppStore-swift_debug_settings.py
examples/integration/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py
examples/sanitizers/test/fixtures/bwx.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py
xcodeproj/internal/xcodeproj_rule.bzl

When adding multiple configurations this broke.

Fix BwX `swift_debug_settings.py` generation

---

tools/generator/src/Generator/CreateFilesAndGroups.swift

This is also a refactor leading up to being able to remove `FilePath.type`.

Be slightly more efficient with file list creation

---

tools/generator/src/DTO/FilePath.swift
tools/generator/src/FilePathResolver.swift
tools/generator/src/Generator/AddBazelDependenciesTarget.swift
tools/generator/src/Generator/AddTargets.swift
tools/generator/src/Generator/CreateFilesAndGroups.swift
tools/generator/src/Generator/Environment.swift
tools/generator/src/Generator/Generator.swift
tools/generator/src/Generator/WriteXcodeProj.swift
tools/generator/test/AddTargetsTests.swift
tools/generator/test/CreateFilesAndGroupsTests.swift
tools/generator/test/Fixtures.swift
tools/generator/test/GeneratorTests.swift

Progress towards being able to remove `FilePath.type`.

Remove `FilePath.PathType.internal`

---

xcodeproj/internal/xcodeproj_rule.bzl

Only focus target merge src if dest is focused

---

xcodeproj/BUILD
xcodeproj/internal/xcodeproj_runner.bzl
xcodeproj/repositories.bzl

This will allow us to have multiple projects in the same repo, in a future change.

Remove generator alias

---

xcodeproj/internal/xcodeproj_rule.bzl

Small clarity increase and loop reduction.

Remove extra `extra_files` loop

---

xcodeproj/internal/default_automatic_target_processing_aspect.bzl

We now use constants in more places, allowing Starlark to not allocate new instances, drastically saving on memory consumption. Future changes will clean up the `AppleBundleInfo in target and target[AppleBundleInfo].binary` path, which still builds up an `xcode_targets` dynamically.

Improve memory efficiency of `_default_automatic_target_processing_aspect_impl`

---

xcodeproj/internal/runner.template.sh

This allows the following command to warm the indexing output base analysis cache:
```
bazel run //:xcodeproj -- --config=indexbuild 'build --nobuild'
```

Set correct output base when using `--config=indexbuild` with the command-line API

---

xcodeproj/internal/input_files.bzl
xcodeproj/internal/resources.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Regressed with d20d87a929f34e58626d30d76c2ed94cf57e45be.

Remove duplicate resources from `spec.json`

---

tools/params_processors/link_params_processor.py

Also rename functions and add comments to make it clear when we should use which.

Quote one more source of linkopts

---

xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh
xcodeproj/internal/output_files.bzl

They were always requested together.

Merge the `bc` and `bg` output groups

---

examples/integration/MODULE.bazel
examples/integration/WORKSPACE

Fixes linking in Xcode 14.3 BwX mode.

Upgrade rules_apple_linker to 0.3.1

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
tools/generator/src/Generator/SetTargetConfigurations.swift

Fix custom bundle extension handling

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwb_targets_spec.json
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx_targets_spec.json
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_targets_spec.json
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx_targets_spec.json
examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/rules_ios/test/fixtures/bwb_targets_spec.json
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb_targets_spec.json
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx_targets_spec.json
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_targets_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_targets_spec.json
test/internal/opts/process_compiler_opts_tests.bzl
tools/generator/src/Generator/CreateProject.swift
tools/generator/test/CreateProjectTests.swift
xcodeproj/internal/opts.bzl

Smaller projects and reduced Starlark memory usage.

Set `SWIFT_VERSION = "5.0"` at the project level

---

examples/README.md

Video: https://vimeo.com/820572803
Code: https://github.com/jpsim/swiftlint-bazel-example

Add SwiftLint custom rules tutorial to external examples list

---

xcodeproj/internal/xcodeprojinfo.bzl

Missed in d2cf7913931d4d57dbcc887fca9e3ad1863449a6.

Pre-filter `transitive_infos` in more places

---

xcodeproj/internal/configuration.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/target_id.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

No need for the intermediate `get_configuration`.

Use `calculate_configuration` directly

---

xcodeproj/internal/library_targets.bzl
xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Instead of in `_create_xcodeprojinfo` and `process_*_target`.

Pre-filter `transitive_infos` once

---

xcodeproj/internal/non_xcode_targets.bzl
xcodeproj/internal/output_files.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl
xcodeproj/internal/xcodeprojinfo.bzl

Remove direct `ctx` access and reorder arguments.

Refactor `xcodeproj_rule.bzl` functions

---

xcodeproj/internal/execution_root.bzl
xcodeproj/internal/xcodeproj_rule.bzl
xcodeproj/internal/xcodeproj_runner.bzl

Extract `_write_execution_root_file` to its own file

---

xcodeproj/internal/bazel_integration_files/BUILD
xcodeproj/internal/bazel_integration_files/actions.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Extract `_write_bazel_build_script` and `_write_create_xcode_overlay_script`

---

tools/generator/src/Generator/CreateFilesAndGroups.swift

Closes #2144.
This fixes issues with symlinks that occur in other places outside of Bazel’s control, like the workspace, generated files, etc.
For a certain large project, this doubles the time that `createFilesAndGroups()` takes (1s to 2s), resulting in total `generator` time going from 8s to 9s.
This also changes symlink resolution to loop, in case a symlink points to another symlink.

Resolve symlinks for all paths

---

tools/generator/test/DefaultLoggerTests.swift
tools/generator/test/SemanticVersionTests.swift

Some minor code cleanup while I was in the area.

Format some tests

---

tools/generator/src/Generator/SemanticVersion.swift
tools/generator/src/Logger.swift

Cleaned up while I was in the area for another reason.

Format some code

---

examples/README.md

I think we forgot to update this when we created the fixtures, cc @mattrobmattrob

Update examples README to mention rule_ios

---

MODULE.bazel
WORKSPACE
buildbuddy.yaml
docs/update_docs.sh

Upgrade stardoc to 0.5.4

---

test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwb_targets_spec.json
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx_targets_spec.json
tools/generators/lib/GeneratorCommon/src/String+Extensions.swift
tools/generators/pbxproj_prefix/src/Generator/Write.swift

This will allow reuse with the other generators.

Extract logic from `Generator.write()`

---

.bcr/metadata.template.json

Update BCR metadata

---

xcodeproj/internal/automatic_target_info.bzl

https://github.com/bazelbuild/rules_swift/pull/1061

Add support for `swift_compiler_plugin` targets

---

MODULE.bazel
WORKSPACE

Needed for newer macOS versions (or something)

Upgrade rules_pkg to 0.9.1

---

tools/generators/BUILD

Forgot this in 712ea5ee3bf187d5979c8a199348caba1355dd22.

Add missing comment to `tools/generators:release_files`

---

tools/generators/files_and_groups/README.md
tools/generators/files_and_groups/test/ElementCreator/CreateMainGroupElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/ElementCreatorCalculatePartialTests.swift
tools/generators/files_and_groups/test/Generator/FilesAndGroupsPartialTests.swift
tools/generators/lib/PBXProj/src/Identifiers.swift
tools/generators/lib/PBXProj/test/IdentifiersTests.swift
tools/generators/pbxproj_prefix/README.md
tools/generators/pbxproj_prefix/test/BazelDependenciesPartialTests.swift
tools/generators/pbxproj_prefix/test/PBXProjectPrefixPartialTests.swift

This is to make way for the next set of generators.

Adjust `Identifier` number scheme

---

xcodeproj/internal/bazel_integration_files/import_indexstores.sh

https://github.com/bazelbuild/apple_support/pull/224

Add support for /PLACEHOLDER_DEVELOPER_DIR remapping

---

xcodeproj/repositories.bzl

Upgrade `index-import` to 5.8.0.1

---

tools/generators/legacy/test/Target+Testing.swift
tools/generators/pbxproj_prefix/test/CompatibilityVersionTests.swift

Missed with a03e5e095d938a32f6187ccc19ce92a1a065571e.

Fix warning

---

examples/cc/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/sanitizers/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwb.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generators/legacy/src/Generator/SetTargetConfigurations.swift

Set `ASAN_OTHER_CFLAGS__YES` as a string

---

tools/generators/lib/PBXProj/src/Identifiers.swift

- Flipped the ordering on `dependency()` and `containerItemProxy()` since dependencies depend on container item proxies, so it’s useful to see the proxies first
- Return more information from `id()`, since that associated information is needed by the generator that calls it

Adjust `Identifiers.Targets`

---

xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh

Additional fix started with 74fda97870e9a5f56c7634cd023929231e6e3644.

Unset tool overrides for BwB Index Build script as well

---

examples/integration/BUILD

Add xcodeproj targets in BwB mode for `examples/integration`

---

examples/cc/test/fixtures/bwx.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwx.xcodeproj/project.pbxproj
test/fixtures/generator/bwx.xcodeproj/project.pbxproj
tools/generators/legacy/src/Generator/SetTargetConfigurations.swift
tools/generators/legacy/test/Fixtures.swift

This was only being set in BwX mode, and thinking about it, I don’t think it’s a good idea to ever set it.

Remove `GENERATE_INFOPLIST_FILE`

---

MODULE.bazel.lock

Add `MODULE.bazel.lock`

---

tools/generators/files_and_groups/src/ElementCreator/ReadSelectedModelVersionsFile.swift
tools/generators/lib/PBXProj/src/URL+Extensions.swift

Makes it easier to diagnose what went wrong.

Add url path to error messages

---

tools/generators/files_and_groups/src/ElementCreator/ElementCreator.swift
tools/generators/files_and_groups/src/Generator/Generator.swift

While implementing the upcoming `PBXBuildFile` changes we needed this further concurrency change.

Adjust `files_and_groups` further for future concurrency changes

---

tools/generators/files_and_groups/src/ElementCreator/CreateFile.swift
tools/generators/files_and_groups/src/ElementCreator/CreateFileElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateGroup.swift
tools/generators/files_and_groups/src/ElementCreator/CreateGroupChild.swift
tools/generators/files_and_groups/src/ElementCreator/CreateGroupElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateSpecialRootGroup.swift
tools/generators/files_and_groups/src/ElementCreator/CreateSpecialRootGroupElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateVariantGroup.swift
tools/generators/files_and_groups/src/ElementCreator/CreateVariantGroupElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateVersionGroup.swift
tools/generators/files_and_groups/src/ElementCreator/CreateVersionGroupElement.swift
tools/generators/files_and_groups/src/ElementCreator/ElementCreator.swift
tools/generators/files_and_groups/src/ElementCreator/ElementCreatorCalculatePartial.swift
tools/generators/files_and_groups/test/ElementCreator/CreateFileElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateFileTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateGroupChildElementsTest.swift
tools/generators/files_and_groups/test/ElementCreator/CreateGroupElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateGroupTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateLocalizedFilesTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateRootElementsTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateSpecialRootGroupElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateSpecialRootGroupTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateVariantGroupElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateVariantGroupTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateVersionGroupElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateVersionGroupTests.swift
tools/generators/files_and_groups/test/ElementCreator/ElementCreatorCalculatePartialTests.swift
tools/generators/files_and_groups/test/ElementCreator/ElementCreatorStubs.swift
tools/generators/lib/PBXProj/src/Object.swift

In a future generator we will need to make use of this smaller common type.

Extract `PBXProj.Object` out of `files_and_groups.Element`

---

xcodeproj/internal/bazel_integration_files/import_indexstores.sh

Regressed with 3bf785dd2561bd99d262bab10476c35a6f42ee52.

Fix importing of Index Build indexes

---

MODULE.bazel
examples/cc/MODULE.bazel
examples/cc/external/MODULE.bazel
examples/integration/MODULE.bazel
xcodeproj/repositories.bzl

Apparently needed for a Stardoc upgrade.

Upgrade (dev-only) Skylib to 1.4.2

---

buildbuddy.yaml
docs/BUILD

Stardoc 0.6.0 doesn’t support Bazel 5.

Don’t build docs in Bazel 5 Workflow

---

MODULE.bazel

Feels like it should have errored out with the wrong name…

Fix override name

---

test/internal/pbxproj_partials/write_files_and_groups_tests.bzl
tools/BUILD
tools/generators/files_and_groups/src/ElementCreator/CreateInternalGroup.swift
tools/generators/files_and_groups/src/ElementCreator/CreateRootElements.swift
tools/generators/files_and_groups/src/ElementCreator/ElementCreator.swift
tools/generators/files_and_groups/src/ElementCreator/ElementCreatorArguments.swift
tools/generators/files_and_groups/src/ElementCreator/ElementCreatorEnvironment.swift
tools/generators/files_and_groups/test/ElementCreator/CreateInternalGroup+Testing.swift
tools/generators/files_and_groups/test/ElementCreator/CreateInternalGroupTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateRootElementsTests.swift
xcodeproj/internal/pbxproj_partials.bzl

This has it match our existing naming.

Rename `project_path` to `install_path`

---

tools/params_processors/link_params_processor.py
xcodeproj/internal/xcode_targets.bzl

We can pass the `link_args` directly to the params processor.

Stop creating intermediate files for link.params processing

---

examples/cc/.bazelrc
examples/cc/MODULE.bazel

Just makes Bazel 7 testing easier.

Use apple_support Xcode toolchain with `examples/cc` as well

---

examples/cc/test/fixtures/bwb_targets_spec.json
examples/cc/test/fixtures/bwx_targets_spec.json
examples/integration/test/fixtures/bwb_targets_spec.json
examples/integration/test/fixtures/bwx_targets_spec.json
examples/rules_ios/test/fixtures/bwb_targets_spec.json
test/fixtures/generator/bwb_targets_spec.json
test/fixtures/generator/bwx_targets_spec.json
xcodeproj/internal/xcodeproj_rule.bzl

Gets in the way of testing when Starlark hash changes.

Don’t sort spec keys

---

xcodeproj/internal/xcodeprojinfo.bzl

Fix `_should_create_provider` for bzlmod

---

tools/generators/files_and_groups/src/ElementCreator/CreateFileElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateGroupElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateIdentifier.swift
tools/generators/files_and_groups/src/ElementCreator/CreateLocalizedFileElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateLocalizedFiles.swift
tools/generators/files_and_groups/src/ElementCreator/CreateVariantGroupElement.swift
tools/generators/files_and_groups/src/ElementCreator/CreateVersionGroup.swift
tools/generators/files_and_groups/src/ElementCreator/ElementCreatorEnvironment.swift
tools/generators/files_and_groups/test/ElementCreator/CreateFileElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateGroupElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateIdentifier+Testing.swift
tools/generators/files_and_groups/test/ElementCreator/CreateLocalizedFileElement+Testing.swift
tools/generators/files_and_groups/test/ElementCreator/CreateLocalizedFileElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateLocalizedFiles+Testing.swift
tools/generators/files_and_groups/test/ElementCreator/CreateLocalizedFilesTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateVariantGroupElementTests.swift
tools/generators/files_and_groups/test/ElementCreator/CreateVersionGroupTests.swift
tools/generators/files_and_groups/test/ElementCreator/ElementCreatorStubs.swift
tools/generators/lib/PBXProj/src/Identifiers.swift
tools/generators/lib/PBXProj/test/IdentifiersTests.swift

Also fixed comments for file element paths.

Fix localized files in `files_and_groups`

---

examples/integration/BUILD

The target names were updated to include build mode.

Update example commands

---

xcodeproj/internal/pbxproj_partials.bzl

`bool(EMPTY_DEPSET) == False`.

Remove unneeded `EMPTY_DEPSET` comprison

---

xcodeproj/internal/input_files.bzl

Mainly preparing for some incremental generator refactoring.

Move `label` assignment in `input_files.collect`

---

tools/generators/lib/PBXProj/src/PBXProductType.swift
tools/generators/pbxtargetdependencies/src/Generator/DisambiguateTargets.swift
xcodeproj/internal/product.bzl
xcodeproj/internal/xcode_targets.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Only WatchKit 2 is supported by rules_apple.

Remove support for WatchKit 1

---

xcodeproj/internal/bazel_integration_files/copy_outputs.sh

Sign device Xcode injected test frameworks

---

buildbuddy.yaml

After all of the pruning of actions, it was a little unbalanced.

Adjust arm64 versus x86 workflows

---

tools/BUILD
tools/extension_point_identifiers_parser/BUILD
tools/extension_point_identifiers_parser/extension_point_identifiers_parser.py
xcodeproj/internal/extension_point_identifiers.bzl
xcodeproj/internal/xcodeproj_rule.bzl

Also make it slightly more efficient in Starlark by using `args` more.

Extract `write_extension_point_identifiers_file` to a `.bzl` file

---

test/internal/pbxproj_partials/write_pbxtargetdependencies_tests.bzl
tools/BUILD
tools/generators/lib/PBXProj/src/ConsolidationMapEntry.swift
tools/generators/lib/PBXProj/test/ConsolidationMapEntryTests.swift
tools/generators/pbxtargetdependencies/src/Generator/CalculateConsolidationMaps.swift
tools/generators/pbxtargetdependencies/src/Generator/ConsolidateTargets.swift
tools/generators/pbxtargetdependencies/src/Generator/ConsolidationMapsArguments.swift
tools/generators/pbxtargetdependencies/src/Generator/Generator.swift
tools/generators/pbxtargetdependencies/src/Generator/GeneratorArguments.swift
tools/generators/pbxtargetdependencies/src/Generator/IdentifyTargets.swift
tools/generators/pbxtargetdependencies/src/Generator/InnerIdentifyTargets.swift
tools/generators/pbxtargetdependencies/src/Generator/Target.swift
tools/generators/pbxtargetdependencies/test/Generator/CalculateConsolidationMapsTests.swift
tools/generators/pbxtargetdependencies/test/Generator/ConsolidateTargetsTests.swift
tools/generators/pbxtargetdependencies/test/Generator/ConsolidationMapsArgumentsTests.swift
tools/generators/pbxtargetdependencies/test/Generator/DisambiguateTargetsTests.swift
tools/generators/pbxtargetdependencies/test/Generator/IdentifiedTarget+Testing.swift
tools/generators/pbxtargetdependencies/test/Generator/InnerIdentifyTargetsTests.swift
xcodeproj/internal/pbxproj_partials.bzl

These will be consumed by future incremental generators.

Add more properties to consolidation maps

---

tools/generators/lib/XCScheme/BUILD
tools/generators/lib/XCScheme/src/BuildableReference.swift
tools/generators/lib/XCScheme/src/CommandLineArguments.swift
tools/generators/lib/XCScheme/src/CreateAnalyzeAction.swift
tools/generators/lib/XCScheme/src/CreateArchiveAction.swift
tools/generators/lib/XCScheme/src/CreateBuildAction.swift
tools/generators/lib/XCScheme/src/CreateLaunchAction.swift
tools/generators/lib/XCScheme/src/CreateProfileAction.swift
tools/generators/lib/XCScheme/src/CreateScheme.swift
tools/generators/lib/XCScheme/src/CreateTestAction.swift
tools/generators/lib/XCScheme/src/EnvironmentVariables.swift
tools/generators/lib/XCScheme/src/ExecutionAction.swift
tools/generators/lib/XCScheme/src/Runnable.swift
tools/generators/lib/XCScheme/src/Xml.swift
tools/generators/lib/XCScheme/test/CreateAnalyzeActionTests.swift
tools/generators/lib/XCScheme/test/CreateArchiveActionTests.swift
tools/generators/lib/XCScheme/test/CreateBuildActionTests.swift
tools/generators/lib/XCScheme/test/CreateLaunchActionTests.swift
tools/generators/lib/XCScheme/test/CreateProfileActionTests.swift
tools/generators/lib/XCScheme/test/CreateSchemeTests.swift
tools/generators/lib/XCScheme/test/CreateTestActionTests.swift

Will be used to create `.xcscheme` files with the incremental generators.

Add `XCScheme` library

---

buildbuddy.yaml

Some issues that are popping up are exclusive to Bzlmod.

Add `Bazel HEAD using WORKSPACE` integration test

---

tools/generators/lib/XCScheme/src/CreateSchemeManagement.swift
tools/generators/lib/XCScheme/test/CreateSchemeManagementTests.swift

Will be used to create `xcschememanagement.plist` files with the incremental generators.

Add `CreateSchemeManagement` to `XCScheme`

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_targets_spec.json
xcodeproj/internal/top_level_targets.bzl

Missed with ebfdddee547d3a2dcfbf0d5e638573785281dcc9.

Stop setting `dwarf-with-dsym` in one more location

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_targets_spec.json
examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/rules_ios/test/fixtures/bwb_targets_spec.json
xcodeproj/internal/output_files.bzl

Stop copying over frameworks in BwB mode

---

xcodeproj/internal/bazel_integration_files/calculate_output_groups.py

This might not fix it 100%, but before this change, at least on Xcode 15, it would find an updated `.xcbuilddata` folder, which then gets deleted, and then hang waiting to find `build-request.json`. Now we ensure that we can do a full parse before exiting `_wait_for_value`.

Fix hanging `calculate_output_groups.py`

---

examples/integration/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/integration/test/fixtures/bwb_targets_spec.json
examples/rules_ios/test/fixtures/bwb.xcodeproj/project.pbxproj
examples/rules_ios/test/fixtures/bwb_targets_spec.json
xcodeproj/internal/output_files.bzl

Regressed with 5fdfa5c540b188244ac7c17e7b11063217b62745.

Copy over non-static frameworks, fixing framework Xcode previews

---

test/internal/pbxproj_partials/write_pbxtargetdependencies_tests.bzl
test/internal/platforms/platforms_to_dto_tests.bzl
xcodeproj/internal/pbxproj_partials.bzl
xcodeproj/internal/platforms.bzl

In preparation for some incremental generation changes.

Clean up `platforms.bzl`

---

xcodeproj/internal/bazel_integration_files/calculate_output_groups.py

Regressed with a6827855554a0849750d08f83976ce53966665cf.

Move `calculate_output_groups.py` JSON parsing error reporting

---

xcodeproj/internal/templates/installer.sh

Fixes #2697.
Breakpoints or other user specific stuff is in there.

Don’t delete `.xcodeproj/xcuserdata`

---

tools/generators/lib/PBXProj/src/String+Extensions.swift

It’s used in a couple generators.

Add `nullsToNewlines` to `PBXProj`

---

test/internal/pbxproj_partials/write_pbxtargetdependencies_tests.bzl
tools/BUILD
tools/generators/pbxtargetdependencies/README.md
tools/generators/pbxtargetdependencies/src/Generator/DisambiguateTargets.swift
tools/generators/pbxtargetdependencies/src/Generator/Generator.swift
tools/generators/pbxtargetdependencies/src/Generator/GeneratorArguments.swift
tools/generators/pbxtargetdependencies/src/Generator/IdentifyTargets.swift
tools/generators/pbxtargetdependencies/src/Generator/TargetNameMode.swift
tools/generators/pbxtargetdependencies/test/Generator/DisambiguateTargetsTests.swift
xcodeproj/internal/pbxproj_partials.bzl

Porting 03f00bb03c4614a93e5aed80d8e8254c4a1454a2 to incremental generation mode.

Add `xcodeproj.target_name_mode` support to incremental generation

---

MODULE.bazel
examples/integration/MODULE.bazel
xcodeproj/repositories.bzl

Fixes a staleness bug when Bazel versions change.

Upgrade bazel_features to 1.1.1

---

.bazelignore
examples/integration/.bazelignore
examples/rules_ios/.bazelignore
examples/sanitizers/.bazelignore

Preparation for a Bazel 7 Skymeld regression + fix: https://github.com/bazelbuild/bazel/commit/e1fbc8349850145a12136d2488e0ca70e46fc8e9.

Add `.git` to `.bazelignore`

---

MODULE.bazel
examples/integration/MODULE.bazel

No impact on users, just for better test coverage.

Upgrade dev version of skylib to 1.5.0

---

distribution/BUILD
examples/integration/WORKSPACE
test/internal/xcschemes/infos_from_json_tests.bzl
test/internal/xcschemes/write_schemes_tests.bzl
xcodeproj/internal/unsupported_targets.bzl
xcodeproj/internal/xcodeproj_legacy_aspect.bzl

Upcoming change will fix the detection regression.

Fix missed buildifier lints

---

xcodeproj/internal/compilation_providers.bzl
xcodeproj/internal/input_files.bzl
xcodeproj/internal/legacy_xcodeprojinfos.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/unsupported_targets.bzl

Mainly a refactor to allow for coexisting incremental generation mode code.

Move `implementation_compilation_context` into `target_compilation_providers`

---

xcodeproj/internal/compilation_providers.bzl
xcodeproj/internal/library_targets.bzl
xcodeproj/internal/top_level_targets.bzl
xcodeproj/internal/unsupported_targets.bzl

Preparation for incremental generation mode.

Factor `implementation_compilation_context` collection into separate function

---

buildbuddy.yaml

Disable Bazel 7 rules_ios CI

---

BUILD
MODULE.bazel
tools/extension_point_identifiers_parser/BUILD
tools/generators/selected_model_versions/BUILD
tools/params_processors/BUILD
tools/xccurrentversions_parser/BUILD

Use rules_python

---

tools/generators/lib/PBXProj/src/Identifiers.swift
tools/generators/pbxproj_prefix/README.md
tools/generators/pbxproj_prefix/src/Generator/BazelDependenciesPartial.swift
tools/generators/pbxproj_prefix/test/BazelDependenciesPartialTests.swift

I saw Xcode renaming this for us.

Fix id comment for `Generate Bazel Dependendencies` script

---

xcodeproj/internal/automatic_target_info.bzl

Include cmake sources as extra files

---

README.md

BwX mode is going away, so we don’t want to call attention to it.

Remove BwX mention in `README.md`

---

xcodeproj/repositories.bzl

Will run into this in a future change.

Add missing `DequeModule` dependency

---

tools/params_processors/incremental_link_params_processor.py
xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl

Rehash of https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/1862 for `incremental_link_params_processor.py`
In a step for cache population for a massive application we get "Argument list too long" also from `incremental_link_params_processor`. (command: `bazel run //:name.xcodeproj -- --generator_output_groups=all_targets build`)
```
Action failed to execute: java.io.IOException: Cannot run program "...//rules_xcodeproj.noindex/build_output_base/execroot/register"): error=7, Argument list too long
...
BAZEL ERROR
ERROR: .../BUILD.bazel:373:19: Generating bazel-out/*/*-App.rules_xcodeproj.link.params failed: (Exit -1): incremental_link_params_processor failed: error executing command (from target *-App)
```

Use sub-params file for incremental link params processor

---

xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl

Prevent `xcschemes` error when listing a merged target in `library_targets`

---

xcodeproj/internal/files/incremental_input_files.bzl
xcodeproj/internal/files/incremental_resources.bzl

Fixes #2914.
I don’t believe we need to make this even more generalized and process all extra files.

Fix processing of folder-type uncategorized resources with incremental generation

---

docs/bazel.md
docs/usage.md
xcodeproj/internal/automatic_target_info.bzl
xcodeproj/internal/xcodeprojinfo.bzl

https://github.com/orgs/community/discussions/16925

Update warning blocks for new GitHub syntax

---

xcodeproj/internal/incremental_xcode_targets.bzl
xcodeproj/internal/xcodeproj_incremental_rule.bzl

Regressed with 7399108d66a35e5147970067151ba685861d58fd.

Fix handling of resource bundles with incremental generation mode

---

examples/integration/tools/bazel

Resistant to configuration changes.

Use `cquery --output files` for determining `repository_override`

---

xcodeproj/internal/xcodeproj_macro.bzl

Remove extra trailing newlines and adds as prefix to one.

Clean up some Starlark warnings and errors

---

xcodeproj/internal/files/incremental_resources.bzl

Use a dictionary for ignored resource fields

---

MODULE.bazel

Upgrade dev rules_swift

---

README.md

added amo in projects using rules_xcodeproj

Add amo to projects using rules_xcodeproj

---

xcodeproj/internal/processed_targets/incremental_top_level_targets.bzl
xcodeproj/internal/processed_targets/mergeable_infos.bzl

Will be used in `mixed_language_library` support.

Extract `mergeable_infos` module

---

test/mock_actions.bzl
xcodeproj/internal/pbxproj_partials.bzl

Better Bazel version compatibility.

Change `.repo_name` to `.workspace_name`

---

xcodeproj/internal/bazel_integration_files/generate_bazel_dependencies.sh
xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh

Regressed with 59303f55e135cb9fe51dc2923bb65ef99d200641.

Fix missed `$INDEXING_PROJECT_DIR__NO` removal

---

tools/generators/target_build_settings/src/Generator/ProcessSwiftArgs.swift

Skip -const-gather-protocols-file to fix index compilation

---

test/internal/pbxproj_partials/write_files_and_groups_tests.bzl
tools/generators/files_and_groups/src/Generator/ReadGeneratedFilePathsFile.swift
xcodeproj/internal/files/incremental_input_files.bzl
xcodeproj/internal/files/incremental_resources.bzl
xcodeproj/internal/incremental_xcode_targets.bzl
xcodeproj/internal/pbxproj_partials.bzl
xcodeproj/internal/xcodeproj_incremental_rule.bzl

In f20bd24fda09f479adb6b29a6d1f7257774d782c I forgot to account for generated resource files.

Properly handle generated processed resources

---

xcodeproj/internal/files/incremental_input_files.bzl

Regressed in caae410fcd827b4bcc7ae8b794773ce07a1ceb8b.

Fix missing BUILD files in Project navigator

---

examples/integration/GRPC/BUILD
examples/integration/MODULE.bazel

Add protobuf dep to `examples/integration`

---

CHANGELOG.md
CONTRIBUTING.md
distribution/release_notes_template.md

Going forward we will update this file instead of adding a changelog to the release notes.

Add `CHANGELOG.md`
